//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MPDocument, MRMarimbaLayer;

@interface TVSSMarimbaView : UIView
{
}

+ (Class)layerClass;	// IMP=0x0000000100002e2c
@property(readonly, nonatomic) MRMarimbaLayer *marimbaLayer;
@property(readonly, nonatomic) MPDocument *document;
- (id)layer;	// IMP=0x0000000100002e40
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100002d9c

@end

