//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVNPRoutingDestination.h"

#import "MPVolumeControllerDelegate.h"

@class MPAVEndpointRoute, MPVolumeController, NSString, TVNPEndpointRouteConnection;

@interface TVNPEndpointRoutingDestination : TVNPRoutingDestination <MPVolumeControllerDelegate>
{
    MPAVEndpointRoute *_endpointRoute;	// 96 = 0x60
    TVNPEndpointRouteConnection *_routeConnection;	// 104 = 0x68
    MPVolumeController *_volumeController;	// 112 = 0x70
    id <NSCopying> _routeConnectionObserverToken;	// 120 = 0x78
    unsigned long long _connectionState;	// 128 = 0x80
}

+ (unsigned long long)_playbackStateForMPCPlaybackState:(long long)arg1;	// IMP=0x0000000100003234
+ (id)keyPathsForValuesAffectingPaired;	// IMP=0x00000001000027f0
+ (id)keyPathsForValuesAffectingDisconnected;	// IMP=0x00000001000027d4
+ (id)keyPathsForValuesAffectingConnected;	// IMP=0x00000001000027b8
@property(nonatomic) unsigned long long connectionState; // @synthesize connectionState=_connectionState;
@property(readonly, nonatomic) id <NSCopying> routeConnectionObserverToken; // @synthesize routeConnectionObserverToken=_routeConnectionObserverToken;
@property(readonly, nonatomic) MPVolumeController *volumeController; // @synthesize volumeController=_volumeController;
@property(readonly, nonatomic) TVNPEndpointRouteConnection *routeConnection; // @synthesize routeConnection=_routeConnection;
@property(readonly, nonatomic) MPAVEndpointRoute *endpointRoute; // @synthesize endpointRoute=_endpointRoute;
- (void).cxx_destruct;	// IMP=0x00000001000032b8
- (void)_metadataDidChange:(id)arg1 forKeys:(id)arg2;	// IMP=0x0000000100002e64
- (void)_updateVolume;	// IMP=0x0000000100002ca8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100002bc4
- (void)volumeController:(id)arg1 volumeValueDidChange:(float)arg2;	// IMP=0x0000000100002b4c
- (void)volumeController:(id)arg1 volumeControlAvailableDidChange:(_Bool)arg2;	// IMP=0x0000000100002ad4
- (void)connectAndPair;	// IMP=0x0000000100002abc
- (void)togglePlayPause;	// IMP=0x0000000100002aa4
- (void)refreshPropertiesWithRoute:(id)arg1;	// IMP=0x00000001000028c8
- (void)setVolumeLevel:(id)arg1;	// IMP=0x000000010000280c
- (_Bool)isDisconnected;	// IMP=0x0000000100002794
- (_Bool)isConnected;	// IMP=0x0000000100002770
- (_Bool)isPaired;	// IMP=0x0000000100002758
@property(nonatomic) _Bool isCurrentDestination; // @dynamic isCurrentDestination;
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0000000100002600
- (id)initWithEndpointRoute:(id)arg1;	// IMP=0x00000001000021ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

