//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface TVNPNowPlayingProgressView : UIView
{
    float _progress;	// 8 = 0x8
}

@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(readonly, nonatomic, getter=_progressCenter) struct CGPoint progressCenter;
- (struct CGSize)_fillSize;	// IMP=0x000000010000caec
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;	// IMP=0x000000010000cad4
- (void)tintColorDidChange;	// IMP=0x000000010000ca74
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x000000010000c85c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010000c7ec

@end

