//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVNPBaseRouteCollectionViewCell.h"

@class TVNPRoute;

@interface TVNPRouteCollectionViewCell : TVNPBaseRouteCollectionViewCell
{
    TVNPRoute *_route;	// 8 = 0x8
}

@property(retain, nonatomic) TVNPRoute *route; // @synthesize route=_route;
- (void).cxx_destruct;	// IMP=0x00000001000072dc
- (void)_updateMultiSelectionState;	// IMP=0x0000000100007288
- (void)_updateVolumeState;	// IMP=0x00000001000071e0
- (void)_updateMusicBarState;	// IMP=0x0000000100007088
- (void)volumeSliderValueChanged:(id)arg1;	// IMP=0x0000000100007018
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100006e10
- (void)prepareForReuse;	// IMP=0x0000000100006b28
- (void)dealloc;	// IMP=0x0000000100006ad8

@end

