//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@class NSMutableArray, NSMutableDictionary, PBSDisplayAssistantPresentationRequest, PBSDisplayMode, TVDADataReporter, TVSStateMachine;

@interface TVDANavigationController : UINavigationController
{
    TVDADataReporter *_reporter;	// 8 = 0x8
    NSMutableArray *_seenStepDisplayModePairs;	// 16 = 0x10
    int _numVideoResetSeenInCableCheck;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
    NSMutableArray *_steps;	// 40 = 0x28
    NSMutableArray *_queuedMeasurers;	// 48 = 0x30
    id <TVDAMeasurer> _measurerCurrentlyMeasuring;	// 56 = 0x38
    unsigned long long _currentStepIndex;	// 64 = 0x40
    NSMutableDictionary *_takenMeasurements;	// 72 = 0x48
    PBSDisplayAssistantPresentationRequest *_presentationRequest;	// 80 = 0x50
}

@property(nonatomic) int numVideoResetSeenInCableCheck; // @synthesize numVideoResetSeenInCableCheck=_numVideoResetSeenInCableCheck;
@property(retain, nonatomic) PBSDisplayAssistantPresentationRequest *presentationRequest; // @synthesize presentationRequest=_presentationRequest;
@property(retain, nonatomic) NSMutableDictionary *takenMeasurements; // @synthesize takenMeasurements=_takenMeasurements;
@property(nonatomic) unsigned long long currentStepIndex; // @synthesize currentStepIndex=_currentStepIndex;
@property(retain, nonatomic) id <TVDAMeasurer> measurerCurrentlyMeasuring; // @synthesize measurerCurrentlyMeasuring=_measurerCurrentlyMeasuring;
@property(retain, nonatomic) NSMutableArray *queuedMeasurers; // @synthesize queuedMeasurers=_queuedMeasurers;
@property(retain, nonatomic) NSMutableArray *steps; // @synthesize steps=_steps;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void).cxx_destruct;	// IMP=0x000000010000c354
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010000ba28
- (void)_handleMenuPress:(id)arg1;	// IMP=0x000000010000ba24
- (void)_updateInternalLabelIfNeededForViewController:(id)arg1;	// IMP=0x000000010000b8bc
- (void)_dismissDisplayAssistant;	// IMP=0x000000010000b850
- (void)_pushViewControllerForStep:(id)arg1;	// IMP=0x000000010000b140
- (void)_pushSpinnerViewController;	// IMP=0x000000010000b080
- (void)_goBackToPreviousStepForAction:(id)arg1;	// IMP=0x000000010000a96c
- (id)_nextStepFromCalculatingMeasurements;	// IMP=0x0000000100009f80
- (void)_runAction:(id)arg1;	// IMP=0x0000000100009b40
- (void)_measureAction:(id)arg1;	// IMP=0x00000001000096ec
- (void)_measureStep:(id)arg1;	// IMP=0x00000001000092b4
- (void)_attemptToRunMeasurer:(id)arg1;	// IMP=0x0000000100008f78
- (void)_enqueueMeasurer:(id)arg1;	// IMP=0x0000000100008e40
- (void)_executeNextQueuedMeasurerIfAny;	// IMP=0x0000000100008cf0
- (void)_startFromFirstStep;	// IMP=0x00000001000089a0
- (id)_nextStepByAdvancing;	// IMP=0x0000000100008924
- (void)_initialiseStateMachine;	// IMP=0x0000000100006d70
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100006cf0
- (void)setViewControllers:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100006c40
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100006b54
- (void)viewDidLoad;	// IMP=0x00000001000069cc
@property(readonly, nonatomic) long long assistantSource;
@property(readonly, nonatomic) long long assistantKind;
@property(readonly, nonatomic) PBSDisplayMode *destinationDisplayMode;
@property(readonly, nonatomic) PBSDisplayMode *sourceDisplayMode;
- (void)dealloc;	// IMP=0x0000000100006648
- (id)initWithPresentationRequest:(id)arg1;	// IMP=0x0000000100006448

// Remaining properties
@property(nonatomic) __weak id <TVDANavigationControllerDelegate> delegate; // @dynamic delegate;

@end

