//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface TVSBSLevelBarView : UIView
{
    NSArray *_boxes;	// 8 = 0x8
    unsigned long long _numLevels;	// 16 = 0x10
    unsigned long long _level;	// 24 = 0x18
}

+ (struct CGRect)_boundsForNumLevels:(unsigned long long)arg1;	// IMP=0x0000000100005ba8
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(readonly, nonatomic) unsigned long long numLevels; // @synthesize numLevels=_numLevels;
- (void).cxx_destruct;	// IMP=0x0000000100005d60
- (void)_updateLevels;	// IMP=0x0000000100005bd4
- (void)layoutSubviews;	// IMP=0x0000000100005a34
- (id)initWithNumLevels:(unsigned long long)arg1;	// IMP=0x0000000100005860
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100005814
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000057d0

@end

