//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSBulletinServiceDelegate.h"
#import "TVPABluetoothRemotePairingDelegate.h"
#import "TVSBluetoothManagerDelegate.h"

@class NSString, PBSBulletin, TVPABluetoothRemotePairingAgent, TVPADeviceEnforcementAgent;

@interface TVPeripheralAgentService : NSObject <PBSBulletinServiceDelegate, TVPABluetoothRemotePairingDelegate, TVSBluetoothManagerDelegate>
{
    int _proximityNotifyToken;	// 8 = 0x8
    _Bool _proximityNotifyTokenIsValid;	// 12 = 0xc
    int _mfiAuthNotifyToken;	// 16 = 0x10
    _Bool _mfiAuthNotifyTokenIsValid;	// 20 = 0x14
    struct __IOHIDManager *_externalDeviceHIDManager;	// 24 = 0x18
    id <PBSBulletinServiceInterface> _bulletinService;	// 32 = 0x20
    PBSBulletin *_bulletin;	// 40 = 0x28
    TVPABluetoothRemotePairingAgent *_bluetoothRemotePairingAgent;	// 48 = 0x30
    TVPADeviceEnforcementAgent *_deviceEnforcementAgent;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x0000000100009f8c
@property(retain, nonatomic) TVPADeviceEnforcementAgent *deviceEnforcementAgent; // @synthesize deviceEnforcementAgent=_deviceEnforcementAgent;
@property(retain, nonatomic) TVPABluetoothRemotePairingAgent *bluetoothRemotePairingAgent; // @synthesize bluetoothRemotePairingAgent=_bluetoothRemotePairingAgent;
@property(retain) PBSBulletin *bulletin; // @synthesize bulletin=_bulletin;
@property(retain, nonatomic) id <PBSBulletinServiceInterface> bulletinService; // @synthesize bulletinService=_bulletinService;
- (void).cxx_destruct;	// IMP=0x000000010000c2b0
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x000000010000c1c4
- (void)_presentPeripheralHUD:(long long)arg1;	// IMP=0x000000010000bd3c
- (void)_startListeningForExternalDeviceConnection;	// IMP=0x000000010000bad8
- (void)_enforcementAgentWillDisconnectDeviceNotification:(id)arg1;	// IMP=0x000000010000ba64
- (void)_bluetoothRemotePowerSourceLimitedSourceNotification:(id)arg1;	// IMP=0x000000010000b9cc
- (void)_checkBatteryLevelForRemote:(id)arg1;	// IMP=0x000000010000b524
- (void)_bluetoothRemoteDidDetectUserPresenceNotification:(id)arg1;	// IMP=0x000000010000b4a0
- (void)_bluetoothRemoteDidDisconnectNotification:(id)arg1;	// IMP=0x000000010000af68
- (void)_bluetoothRemoteDidConnectNotification:(id)arg1;	// IMP=0x000000010000aa38
- (void)_dismissPairingAgent;	// IMP=0x000000010000a958
- (void)pairingAgentDidTimeout:(id)arg1;	// IMP=0x000000010000a94c
- (void)pairingAgentDidPairRemote:(id)arg1;	// IMP=0x000000010000a940
- (void)bluetoothManager:(id)arg1 didCompleteDeviceDisconnection:(id)arg2 error:(id)arg3;	// IMP=0x000000010000a820
- (void)bluetoothManager:(id)arg1 didCompleteDeviceConnection:(id)arg2 error:(id)arg3;	// IMP=0x000000010000a730
- (void)start;	// IMP=0x000000010000a148
- (void)dealloc;	// IMP=0x000000010000a074

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

