//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionDataSource.h"

@class NSArray, NSMutableDictionary, NSMutableOrderedSet;

@interface GKDashboardMultiplayerDataSource : GKCollectionDataSource
{
    _Bool _automatchAddedToMinInHeader;	// 8 = 0x8
    _Bool _addingEnabled;	// 9 = 0x9
    _Bool _removingEnabled;	// 10 = 0xa
    _Bool _autoMatching;	// 11 = 0xb
    long long _minPlayers;	// 16 = 0x10
    long long _maxPlayers;	// 24 = 0x18
    long long _automatchPlayers;	// 32 = 0x20
    CDUnknownBlockType _playersChangedHandler;	// 40 = 0x28
    NSArray *_participants;	// 48 = 0x30
    NSMutableDictionary *_playerStatus;	// 56 = 0x38
    NSMutableOrderedSet *_players;	// 64 = 0x40
    NSMutableOrderedSet *_orderedPlayerIDList;	// 72 = 0x48
}

@property(retain, nonatomic) NSMutableOrderedSet *orderedPlayerIDList; // @synthesize orderedPlayerIDList=_orderedPlayerIDList;
@property(retain, nonatomic) NSMutableOrderedSet *players; // @synthesize players=_players;
@property(retain, nonatomic) NSMutableDictionary *playerStatus; // @synthesize playerStatus=_playerStatus;
@property(retain, nonatomic) NSArray *participants; // @synthesize participants=_participants;
@property(copy, nonatomic) CDUnknownBlockType playersChangedHandler; // @synthesize playersChangedHandler=_playersChangedHandler;
@property(nonatomic) _Bool autoMatching; // @synthesize autoMatching=_autoMatching;
@property(nonatomic) _Bool removingEnabled; // @synthesize removingEnabled=_removingEnabled;
@property(nonatomic) _Bool addingEnabled; // @synthesize addingEnabled=_addingEnabled;
@property(nonatomic) _Bool automatchAddedToMinInHeader; // @synthesize automatchAddedToMinInHeader=_automatchAddedToMinInHeader;
@property(nonatomic) long long automatchPlayers; // @synthesize automatchPlayers=_automatchPlayers;
@property(nonatomic) long long maxPlayers; // @synthesize maxPlayers=_maxPlayers;
@property(nonatomic) long long minPlayers; // @synthesize minPlayers=_minPlayers;
- (_Bool)collectionView:(id)arg1 canFocusItemAtIndexPath:(id)arg2;	// IMP=0x0000000100008470
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010000845c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100008330
- (void)setAutoMatching:(_Bool)arg1 withVisibleCells:(id)arg2;	// IMP=0x0000000100008044
- (_Bool)participantShouldBeRemovable:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100007f70
- (void)setParticipantsWithPlayers:(id)arg1 automatchPlayerCount:(long long)arg2 andStatuses:(id)arg3;	// IMP=0x00000001000079d8
- (id)participantAtIndex:(long long)arg1;	// IMP=0x00000001000079c0
- (id)participantForAutoMatchNumber:(long long)arg1;	// IMP=0x000000010000787c
- (id)participantForPlayer:(id)arg1;	// IMP=0x0000000100007730
- (void)failedToInvitePlayers;	// IMP=0x000000010000757c
- (id)playersInvited;	// IMP=0x000000010000756c
- (id)playersToBeInvited;	// IMP=0x000000010000755c
- (id)readyPlayers;	// IMP=0x000000010000754c
- (id)playersWithStatus:(long long)arg1;	// IMP=0x00000001000073e8
- (id)guestPlayers;	// IMP=0x00000001000073c4
- (id)currentPlayers;	// IMP=0x00000001000073ac
- (void)finishRevertingPlayers;	// IMP=0x0000000100007194
- (void)setStatus:(long long)arg1 forPlayers:(id)arg2;	// IMP=0x0000000100006bb8
- (_Bool)shouldRevertStatus:(long long)arg1;	// IMP=0x0000000100006ba8
- (void)removePlayers:(id)arg1;	// IMP=0x0000000100006a34
- (void)addPlayers:(id)arg1 withStatus:(long long)arg2 replaceAutomatches:(_Bool)arg3;	// IMP=0x00000001000067f0
- (void)addPlayers:(id)arg1 withStatus:(long long)arg2;	// IMP=0x00000001000067e0
- (long long)maxAvailablePlayers;	// IMP=0x00000001000067a0
- (struct _NSRange)playerRange;	// IMP=0x000000010000662c
- (_Bool)havePendingPlayers;	// IMP=0x00000001000064c8
- (long long)statusForPlayer:(id)arg1;	// IMP=0x000000010000646c
- (long long)itemCount;	// IMP=0x0000000100006454
- (void)_updateParticipantsAnimated:(_Bool)arg1;	// IMP=0x0000000100005bd8
- (void)restoreOrderOfPlayers;	// IMP=0x00000001000059f0
- (void)updateParticipantsAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000058dc
- (void)updateParticipantsAnimated:(_Bool)arg1;	// IMP=0x00000001000058cc
- (void)loadDataWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100005838
- (void)setupCollectionView:(id)arg1;	// IMP=0x0000000100005788
- (void)dealloc;	// IMP=0x00000001000056dc
- (id)init;	// IMP=0x0000000100005524

@end

