//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKDynamicButton.h"

@interface GKDashboardFocusButton : GKDynamicButton
{
}

- (void)removeTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned long long)arg3;	// IMP=0x000000010000a9c0
- (void)addTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned long long)arg3;	// IMP=0x000000010000a97c
- (_Bool)canBecomeFocused;	// IMP=0x000000010000a924
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;	// IMP=0x000000010000a7f4
- (void)awakeFromNib;	// IMP=0x000000010000a694

@end

