/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:43 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMEnvironmentPreferences.h>

@interface ACMExternalEnvironmentPreferences : ACMEnvironmentPreferences
+(id)externalEnvironmentSpecifications;
-(id)myAppleIDURL;
-(id)authenticateURLString;
-(id)defaultPublicKeyString;
-(id)environmentSpecificationForRealm:(id)arg1 ;
-(id)verifyTicketURLString;
-(id)getTrustedDevicesURLString;
-(id)generateAndSendSecCodeURLString;
-(id)verifySecurityCodeURLString;
-(id)serverHosts;
-(id)serverAttemptsDelays;
@end

