/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:46 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTDataProviderHeroApp.h>

@interface RTDataProviderHeroApp_Embedded : RTDataProviderHeroApp
-(void)populateDataProviderWithHandler:(/*^block*/id)arg1 ;
-(void)_fetchPredictedApplicationsAtLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)_processLocationApplicationPredictions:(id)arg1 ;
@end

