/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:45 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, RTMapItem;

@interface RTHistoryEntryPlaceDisplay : NSObject {

	NSDate* _usageDate;
	RTMapItem* _mapItem;

}

@property (nonatomic,readonly) NSDate * usageDate;               //@synthesize usageDate=_usageDate - In the implementation block
@property (nonatomic,readonly) RTMapItem * mapItem;              //@synthesize mapItem=_mapItem - In the implementation block
-(RTMapItem *)mapItem;
-(id)initWithUsageDate:(id)arg1 mapItem:(id)arg2 ;
-(NSDate *)usageDate;
-(id)init;
-(id)description;
@end

