/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:46 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class RTMotionActivity;

@interface RTMotionActivityManagerNotificationActivity : RTNotification {

	RTMotionActivity* _activity;

}

@property (nonatomic,readonly) RTMotionActivity * activity;              //@synthesize activity=_activity - In the implementation block
-(id)initWithActivity:(id)arg1 ;
-(RTMotionActivity *)activity;
@end

