/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:43 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertApplication.h>

@interface RTPredictionExpertApplicationMicroLocation : RTPredictionExpertApplication {

	double _maxMicroLocationEventAge;

}

@property (assign,nonatomic) double maxMicroLocationEventAge;              //@synthesize maxMicroLocationEventAge=_maxMicroLocationEventAge - In the implementation block
-(id)initWithQueue:(id)arg1 category:(long long)arg2 dataSource:(id)arg3 defaultsManager:(id)arg4 mediaRemote:(id)arg5 featureAddons:(id)arg6 ;
-(double)maxMicroLocationEventAge;
-(id)supportedEventClasses;
-(void)_processEventsWithAppLaunchEvents:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)dateIntervalForAppLaunchEvent:(id)arg1 ;
-(void)setMaxMicroLocationEventAge:(double)arg1 ;
@end

