/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:44 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSNumber, RTPredictionTableEntryMO;

@interface RTPredictionItemMO : NSManagedObject

@property (nonatomic,retain) NSNumber * confidence; 
@property (nonatomic,retain) RTPredictionTableEntryMO * entry; 
@end

