/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:47 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTReachabilityMonitorNotificationReachabilityChanged : RTNotification {

	long long _reachability;

}

@property (nonatomic,readonly) long long reachability;              //@synthesize reachability=_reachability - In the implementation block
-(long long)reachability;
-(id)initWithReachability:(long long)arg1 ;
@end

