/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:46 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableDictionary;

@interface RTStateModelLegacy : NSObject <NSSecureCoding> {

	long long _version;
	NSMutableDictionary* _stateModelLut;

}

@property (assign,nonatomic) long long version;                                //@synthesize version=_version - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * stateModelLut;              //@synthesize stateModelLut=_stateModelLut - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSMutableDictionary *)stateModelLut;
-(void)setStateModelLut:(NSMutableDictionary *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(void)setVersion:(long long)arg1 ;
-(long long)version;
@end

