/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 11:06:47 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTVisitMonitorDelegate <NSObject>
@optional
-(void)onVisitIncident:(id)arg1 error:(id)arg2;
-(void)onLeechedVisitIncident:(id)arg1 error:(id)arg2;
-(void)onVisitMonitorStateChanged:(id)arg1;
-(void)onLowConfidenceVisitIncident:(id)arg1 error:(id)arg2;

@end

