//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView;

@interface _HBMultiSizedImageView : UIView
{
    UIImage *_image;	// 8 = 0x8
    UIImageView *_imageView;	// 16 = 0x10
    UIImageView *_shadowImageView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000513c8
- (void)setBounds:(struct CGRect)arg1;	// IMP=0x00000001000511e4
- (id)_shadowImage;	// IMP=0x0000000100050fb8
- (id)_shadowPath;	// IMP=0x0000000100050ecc
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2;	// IMP=0x0000000100050c4c
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100050c2c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100050c1c

@end

