//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface HBApplicationProxyLifetimeCacheKey : NSObject <NSCopying>
{
    NSString *_applicationIdentifier;	// 8 = 0x8
    NSString *_bundlePathHash;	// 16 = 0x10
    double _lastModifiedDate;	// 24 = 0x18
}

+ (id)cacheKeyForApp:(id)arg1;	// IMP=0x000000010005eb58
+ (id)cacheKeyForProxy:(id)arg1;	// IMP=0x000000010005e994
@property(readonly, nonatomic) double lastModifiedDate; // @synthesize lastModifiedDate=_lastModifiedDate;
@property(readonly, copy, nonatomic) NSString *bundlePathHash; // @synthesize bundlePathHash=_bundlePathHash;
@property(readonly, copy, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
- (void).cxx_destruct;	// IMP=0x000000010005ef70
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010005ee94
- (unsigned long long)hash;	// IMP=0x000000010005ee7c
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010005ed70
@property(readonly, copy, nonatomic) NSString *filesystemSafeKeyName;
- (id)_init;	// IMP=0x000000010005e960
- (id)init;	// IMP=0x000000010005e948

@end

