//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HBRootCell.h"

#import "HBFolderObserver.h"

@class HBFolder, NSString;

@interface HBFolderCell : HBRootCell <HBFolderObserver>
{
}

+ (id)_baseFolderLayerStackWithInterfaceStyle:(long long)arg1;	// IMP=0x00000001000076d0
- (void)_updateIconImages;	// IMP=0x0000000100007640
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000074c0
- (void)iconImagesDidChange:(id)arg1;	// IMP=0x00000001000074b4
- (void)setDropState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000073e0
- (void)setDropState:(long long)arg1;	// IMP=0x00000001000073d0
@property(readonly, nonatomic) HBFolder *folder;
- (void)setItem:(id)arg1;	// IMP=0x00000001000072d8
- (id)notificationObject:(id)arg1;	// IMP=0x0000000100007144

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

