//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HBImageStackCollectionViewCell.h"

#import "HBIconProgressViewDelegate.h"
#import "HBRootItemObserver.h"

@class CALayer, HBBadgeOverlayView, HBIconProgressView, HBRootItem, NSString, PBSBadgeValue, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;

@interface HBRootCell : HBImageStackCollectionViewCell <HBIconProgressViewDelegate, HBRootItemObserver>
{
    _Bool _pendingProgressViewUpdate;	// 8 = 0x8
    _Bool _allowsProgressAnimation;	// 9 = 0x9
    _Bool _isIdle;	// 10 = 0xa
    struct {
        unsigned int delegateDidLongPress:1;
    } _flags;	// 12 = 0xc
    _Bool _paused;	// 16 = 0x10
    _Bool _showingSnapshot;	// 17 = 0x11
    _Bool _editing;	// 18 = 0x12
    _Bool _inDock;	// 19 = 0x13
    id <HBRootCellDelegate> _delegate;	// 24 = 0x18
    HBRootItem *_item;	// 32 = 0x20
    id <UINamedLayerStack> _icon;	// 40 = 0x28
    double _installPercentage;	// 48 = 0x30
    long long _installProgressState;	// 56 = 0x38
    PBSBadgeValue *_badgeValue;	// 64 = 0x40
    long long _dropState;	// 72 = 0x48
    UIView *_flashView;	// 80 = 0x50
    UIView *_snapshotView;	// 88 = 0x58
    HBBadgeOverlayView *_badgeOverlayView;	// 96 = 0x60
    UILongPressGestureRecognizer *_editGesture;	// 104 = 0x68
    UITapGestureRecognizer *_removeGesture;	// 112 = 0x70
    UITapGestureRecognizer *_selectGesture;	// 120 = 0x78
    HBIconProgressView *_progressView;	// 128 = 0x80
}

+ (id)_badgeNumberFormatter;	// IMP=0x0000000100055438
+ (double)_radiosityStrengthForUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100055124
+ (id)_iconImageConfigurationForUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100054fd4
+ (id)_progressMaskImage;	// IMP=0x0000000100054830
+ (void)_setFocusDuration:(double)arg1;	// IMP=0x00000001000546a0
+ (double)_focusDuration;	// IMP=0x0000000100054694
+ (_Bool)automaticallyNotifiesObserversOfInDock;	// IMP=0x0000000100054210
@property(nonatomic, getter=isInDock) _Bool inDock; // @synthesize inDock=_inDock;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(retain, nonatomic) HBIconProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UITapGestureRecognizer *selectGesture; // @synthesize selectGesture=_selectGesture;
@property(retain, nonatomic) UITapGestureRecognizer *removeGesture; // @synthesize removeGesture=_removeGesture;
@property(retain, nonatomic) UILongPressGestureRecognizer *editGesture; // @synthesize editGesture=_editGesture;
@property(retain, nonatomic) HBBadgeOverlayView *badgeOverlayView; // @synthesize badgeOverlayView=_badgeOverlayView;
@property(nonatomic) _Bool showingSnapshot; // @synthesize showingSnapshot=_showingSnapshot;
@property(retain, nonatomic) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) UIView *flashView; // @synthesize flashView=_flashView;
@property(nonatomic) long long dropState; // @synthesize dropState=_dropState;
@property(retain, nonatomic) PBSBadgeValue *badgeValue; // @synthesize badgeValue=_badgeValue;
@property(nonatomic) long long installProgressState; // @synthesize installProgressState=_installProgressState;
@property(nonatomic) double installPercentage; // @synthesize installPercentage=_installPercentage;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(retain, nonatomic) id <UINamedLayerStack> icon; // @synthesize icon=_icon;
@property(retain, nonatomic) HBRootItem *item; // @synthesize item=_item;
@property(nonatomic) __weak id <HBRootCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010005568c
- (void)_updateRadiosityStrength;	// IMP=0x00000001000551e8
- (void)_updateStackedImageConfiguration;	// IMP=0x000000010005512c
- (void)_longPressGesture:(id)arg1;	// IMP=0x0000000100054f2c
- (void)_updateBadgeValueView;	// IMP=0x0000000100054c6c
- (void)_updateProgressView;	// IMP=0x0000000100054a94
- (void)_updateBadgeValue;	// IMP=0x00000001000547bc
- (void)_updateDisplayName;	// IMP=0x0000000100054748
- (void)_updateInstallState;	// IMP=0x00000001000546ac
- (void)_updateForInDockState;	// IMP=0x00000001000545fc
- (void)_unbindInDock;	// IMP=0x00000001000545e8
- (void)_setInDock:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000544e0
- (double)_maxTitleWidthWithFocus:(_Bool)arg1;	// IMP=0x000000010005442c
- (void)_updateInDockBinding;	// IMP=0x0000000100054360
- (void)tvs_bindInDockBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x000000010005426c
- (id)InDockBinding;	// IMP=0x0000000100054218
- (void)progressViewCanBeRemoved:(id)arg1;	// IMP=0x0000000100054200
- (void)_disableSnapshotViewIfNeeded;	// IMP=0x0000000100054170
- (_Bool)requiresGroupOpacityDuringBubbleAnimation:(_Bool)arg1;	// IMP=0x00000001000540c8
- (void)completedBubbleAnimation:(_Bool)arg1;	// IMP=0x00000001000540bc
- (void)prepareForBubbleAnimation:(_Bool)arg1;	// IMP=0x0000000100053d7c
- (void)setInstallPercentage:(double)arg1 shouldNotify:(_Bool)arg2;	// IMP=0x0000000100053cb0
- (_Bool)_applyKeyPathsAndRelativeValues:(id)arg1 forMotionEffect:(id)arg2;	// IMP=0x0000000100053bbc
- (long long)_focusedSound;	// IMP=0x0000000100053bb4
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100053b0c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100053abc
- (void)setLayeredImageView:(id)arg1;	// IMP=0x000000010005388c
- (void)setImageStackView:(id)arg1;	// IMP=0x0000000100053888
- (id)imageStackView;	// IMP=0x0000000100053880
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x00000001000537d4
- (void)prepareForReuse;	// IMP=0x000000010005371c
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x0000000100053674
- (void)_exitIdleMode;	// IMP=0x0000000100053538
- (void)_enterIdleMode;	// IMP=0x00000001000533f0
@property(readonly, nonatomic, getter=_layerBelowFlash) CALayer *layerBelowFlash;
- (void)cancelConfirmFlash;	// IMP=0x00000001000532e4
- (void)beginConfirmFlash;	// IMP=0x0000000100052d54
- (void)setDropState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100052ca8
- (void)setItem:(id)arg1 withIcon:(id)arg2;	// IMP=0x0000000100052a98
- (void)dealloc;	// IMP=0x0000000100052870
- (id)notificationObject:(id)arg1;	// IMP=0x0000000100052860
- (void)badgeValueDidChangeNotification:(id)arg1;	// IMP=0x00000001000527cc
- (void)displayNameDidChangeNotification:(id)arg1;	// IMP=0x0000000100052738
- (void)installStateDidChangeNotification:(id)arg1;	// IMP=0x00000001000526a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000522d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

