//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UICollectionViewDelegate_Private.h"
#import "UIGestureRecognizerDelegate.h"

@class NSIndexPath, NSString, UICollectionView, UITapGestureRecognizer;

@interface HBTopShelfLabeledContentView : UIView <UIGestureRecognizerDelegate, UICollectionViewDataSource, UICollectionViewDelegate_Private, UICollectionViewDelegateFlowLayout>
{
    UITapGestureRecognizer *_playButtonRecognizer;	// 8 = 0x8
    struct {
        unsigned int delegateDidFocusItemAtIndexPath:1;
        unsigned int delegateDidSelectItemAtIndexPath:1;
        unsigned int delegateDidPlayItemAtIndexPath:1;
        unsigned int dataSourceTitleForSection:1;
        unsigned int dataSourceConfigureLabelForSection:1;
        unsigned int dataSourceNumberOfSections:1;
        unsigned int dataSourceNumberOfItemsInSection:1;
        unsigned int dataSourcePreferredSizeOfItemAtIndexPath:1;
    } _flags;	// 16 = 0x10
    _Bool _shouldUpdateNormalizedHeight;	// 20 = 0x14
    id <HBTopShelfLabeledContentViewDelegate> _delegate;	// 24 = 0x18
    id <HBTopShelfLabeledContentViewDataSource> _dataSource;	// 32 = 0x20
    UICollectionView *_collectionView;	// 40 = 0x28
    NSIndexPath *_preferredIndexPath;	// 48 = 0x30
    double _normalizedHeight;	// 56 = 0x38
}

@property(nonatomic) _Bool shouldUpdateNormalizedHeight; // @synthesize shouldUpdateNormalizedHeight=_shouldUpdateNormalizedHeight;
@property(nonatomic) double normalizedHeight; // @synthesize normalizedHeight=_normalizedHeight;
@property(retain, nonatomic) NSIndexPath *preferredIndexPath; // @synthesize preferredIndexPath=_preferredIndexPath;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <HBTopShelfLabeledContentViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <HBTopShelfLabeledContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000300b4
- (double)_normalizedItemHeight;	// IMP=0x000000010002fa80
- (long long)_numberOfItemsInSection:(long long)arg1;	// IMP=0x000000010002fa00
- (long long)_numberOfSections;	// IMP=0x000000010002f990
- (void)_playButtonAction:(id)arg1;	// IMP=0x000000010002f80c
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x000000010002f804
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x000000010002f7d0
- (void)collectionView:(id)arg1 didFocusItemAtIndexPath:(id)arg2;	// IMP=0x000000010002f6e0
- (_Bool)collectionView:(id)arg1 canFocusItemAtIndexPath:(id)arg2;	// IMP=0x000000010002f6d8
- (void)collectionView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;	// IMP=0x000000010002f648
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010002f5b8
- (double)collectionView:(id)arg1 layout:(id)arg2 widthOfSectionHeaderAtIndexPath:(id)arg3;	// IMP=0x000000010002f4d8
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010002f420
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010002f31c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010002f230
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010002f220
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x000000010002f214
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010002f088
- (id)visibleViews;	// IMP=0x000000010002ef78
- (void)preheatCellsInRect:(struct CGRect)arg1;	// IMP=0x000000010002ef08
- (void)reloadData;	// IMP=0x000000010002eeb0
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;	// IMP=0x000000010002ee44
- (void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;	// IMP=0x000000010002ee2c
- (struct CGSize)normalizedSizeWithPreferredSize:(struct CGSize)arg1;	// IMP=0x000000010002ebdc
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010002e9a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010002e6a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

