//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface UICollectionView (HBAdditions)
- (void)hb_updateItemsInSection:(unsigned long long)arg1 withChanges:(id)arg2;	// IMP=0x000000010008b3cc
- (void)hb_updateItemsInSection:(unsigned long long)arg1 withChange:(id)arg2;	// IMP=0x000000010008b0c8
@end

