//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (TVAdditions)
- (double)primaryHighlightAlphaForHighlightProgress:(double)arg1;	// IMP=0x000000010009a1f8
- (void)didSelect;	// IMP=0x000000010009a1f4
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010009a1e8
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010009a1e4

// Remaining properties
@property(nonatomic) double highlightProgress;
@end

