//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImage, UIImageView;

@interface TVDeckImageView : UIView
{
    UIView *_pendingDisplayView;	// 8 = 0x8
    unsigned long long _pendingViewType;	// 16 = 0x10
    UIView *_displayView;	// 24 = 0x18
    unsigned long long _viewType;	// 32 = 0x20
    UIImageView *_placeholderImageView;	// 40 = 0x28
    double _imageLoadTimeout;	// 48 = 0x30
    NSArray *_artworkCatalogs;	// 56 = 0x38
    UIImage *_placeholderImage;	// 64 = 0x40
    unsigned long long _deckViewParadeType;	// 72 = 0x48
    double _cycleInterval;	// 80 = 0x50
    double _transitionDuration;	// 88 = 0x58
    double _newDataTransitionDuration;	// 96 = 0x60
    struct CGRect _imageFrame;	// 104 = 0x68
}

@property(nonatomic) double newDataTransitionDuration; // @synthesize newDataTransitionDuration=_newDataTransitionDuration;
@property(nonatomic) double transitionDuration; // @synthesize transitionDuration=_transitionDuration;
@property(nonatomic) double cycleInterval; // @synthesize cycleInterval=_cycleInterval;
@property(nonatomic) unsigned long long deckViewParadeType; // @synthesize deckViewParadeType=_deckViewParadeType;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(nonatomic) struct CGRect imageFrame; // @synthesize imageFrame=_imageFrame;
@property(copy, nonatomic) NSArray *artworkCatalogs; // @synthesize artworkCatalogs=_artworkCatalogs;
- (void).cxx_destruct;	// IMP=0x0000000100050300
- (unsigned long long)_viewTypeForNumberOfImages:(long long)arg1;	// IMP=0x00000001000501d4
- (unsigned long long)_paradeThreshold;	// IMP=0x00000001000501cc
- (void)_displayPlaceholderView;	// IMP=0x000000010004fec8
- (void)_fadeToBlack;	// IMP=0x000000010004fdc0
- (void)_dissolveToPendingView;	// IMP=0x000000010004f95c
- (void)resume;	// IMP=0x000000010004f8ec
- (_Bool)isPaused;	// IMP=0x000000010004f86c
- (void)pause;	// IMP=0x000000010004f7fc
- (void)_scrollingParadeViewReadyNotification:(id)arg1;	// IMP=0x000000010004f47c
- (void)_crossfadeViewReadyNotification:(id)arg1;	// IMP=0x000000010004f3a8
- (void)layoutSubviews;	// IMP=0x000000010004f31c
- (void)dealloc;	// IMP=0x000000010004f280
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010004f0f8

@end

