//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVImageScaleDecorator.h"

@class UIImage;

@interface TVMusicBlurDecorator : TVImageScaleDecorator
{
    UIImage *_overlayImage;	// 8 = 0x8
}

+ (id)blurDecoratorForDataIsPrivate;	// IMP=0x000000010005037c
@property(readonly, nonatomic) UIImage *overlayImage; // @synthesize overlayImage=_overlayImage;
- (void).cxx_destruct;	// IMP=0x0000000100050920
- (id)decoratorIdentifier;	// IMP=0x00000001000507f8
- (id)decorate:(id)arg1 scaledWithSize:(struct CGSize)arg2 croppedToFit:(_Bool)arg3;	// IMP=0x0000000100050470
- (id)initWithOverlayImage:(id)arg1;	// IMP=0x00000001000503f0

@end

