//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

@interface TVMusicLibraryRecentlyAddedViewController : TVMusicMPRequestViewController
{
}

- (void)handlePlayPauseCommand;	// IMP=0x00000001000a41a0
- (id)_placeholderImageForObjectType:(long long)arg1;	// IMP=0x00000001000a4044
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000a3d88
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000a3d80
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000a34d4
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000a2ed8

@end

