//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

#import "TVCollectionViewDelegate.h"

@class MPModelTVSeason, NSArray, NSDateFormatter, NSString, TVImageView, UIControl, UIView;

@interface TVMusicLibraryEpisodesViewController : TVMusicMPRequestViewController <TVCollectionViewDelegate>
{
    UIView *_imageViewContainer;	// 8 = 0x8
    TVImageView *_artworkImageView;	// 16 = 0x10
    UIControl *_goToShowButton;	// 24 = 0x18
    UIControl *_moreButton;	// 32 = 0x20
    NSArray *_actionButtons;	// 40 = 0x28
    MPModelTVSeason *_tvSeason;	// 48 = 0x30
    NSDateFormatter *_episodeReleaseDateFormatter;	// 56 = 0x38
    _Bool _visibleOnScreen;	// 64 = 0x40
    _Bool _shouldReloadOnViewDidAppear;	// 65 = 0x41
}

+ (_Bool)_isTVEpisodeWatched:(id)arg1;	// IMP=0x0000000100015358
- (void).cxx_destruct;	// IMP=0x0000000100015798
- (struct CGSize)artworkSize;	// IMP=0x0000000100015784
- (void)_bookmarkWillUpdateNotification:(id)arg1;	// IMP=0x0000000100015720
- (id)_songCellPlaceholderImage;	// IMP=0x00000001000156bc
- (id)_artworkPlaceholderImageForUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100015658
- (void)_selectedMoreButton;	// IMP=0x0000000100015508
- (void)_setPositionForView:(id)arg1 topLeft:(struct CGPoint)arg2;	// IMP=0x0000000100015498
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100014ec8
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100014dd4
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100014dcc
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100014ccc
- (double)cellsTopMargin;	// IMP=0x0000000100014cc0
- (id)cellIdentifier;	// IMP=0x0000000100014c94
- (void)_goToShow;	// IMP=0x0000000100014b7c
- (void)_sizeImageViewToFit;	// IMP=0x0000000100014a60
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000148ec
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010001460c
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100014340
- (void)viewDidLoad;	// IMP=0x0000000100013948
- (id)_seasonName;	// IMP=0x000000010001383c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000137a0
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100013754
- (void)dealloc;	// IMP=0x00000001000136dc
- (id)initWithSeason:(id)arg1 libraryRequest:(id)arg2;	// IMP=0x0000000100013094
- (id)initWithTitle:(id)arg1 libraryRequest:(id)arg2;	// IMP=0x000000010001307c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

