//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TVSignInLandingViewDelegate.h"

@class NSString, TVMusicCloudProgressView, TVMusicLibraryManager, TVMusicLibraryTopMenuViewController, TVSStateMachine, TVSignInLandingView, UIActivityIndicatorView, UIView;

@interface TVMusicCloudViewController : UIViewController <TVSignInLandingViewDelegate>
{
    _Bool _viewVisible;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
    TVMusicLibraryTopMenuViewController *_topMenuViewController;	// 24 = 0x18
    TVMusicCloudProgressView *_cloudProgressView;	// 32 = 0x20
    UIActivityIndicatorView *_activityIndicatorView;	// 40 = 0x28
    TVSignInLandingView *_loginPromptView;	// 48 = 0x30
    UIView *_errorMessageView;	// 56 = 0x38
    UIView *_noMusicView;	// 64 = 0x40
    UIView *_currentDisplayedView;	// 72 = 0x48
    TVMusicLibraryManager *_libraryManager;	// 80 = 0x50
}

@property(nonatomic, getter=isViewVisible) _Bool viewVisible; // @synthesize viewVisible=_viewVisible;
@property(retain, nonatomic) TVMusicLibraryManager *libraryManager; // @synthesize libraryManager=_libraryManager;
@property(nonatomic) __weak UIView *currentDisplayedView; // @synthesize currentDisplayedView=_currentDisplayedView;
@property(retain, nonatomic) UIView *noMusicView; // @synthesize noMusicView=_noMusicView;
@property(retain, nonatomic) UIView *errorMessageView; // @synthesize errorMessageView=_errorMessageView;
@property(retain, nonatomic) TVSignInLandingView *loginPromptView; // @synthesize loginPromptView=_loginPromptView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) TVMusicCloudProgressView *cloudProgressView; // @synthesize cloudProgressView=_cloudProgressView;
@property(retain, nonatomic) TVMusicLibraryTopMenuViewController *topMenuViewController; // @synthesize topMenuViewController=_topMenuViewController;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void).cxx_destruct;	// IMP=0x000000010000650c
- (void)_libraryDidUpdate:(id)arg1;	// IMP=0x0000000100006378
- (void)_musicLibrarySyncProgress:(id)arg1;	// IMP=0x00000001000062a8
- (void)_musicLibraryStateChanged:(id)arg1;	// IMP=0x0000000100006198
- (void)_appDidBecomeActiveNotification:(id)arg1;	// IMP=0x0000000100006178
- (void)authenticateUserOnSelectSignIn;	// IMP=0x0000000100006158
- (void)_updateTopMenu;	// IMP=0x0000000100005ed4
- (void)_updateUIForStyle:(long long)arg1;	// IMP=0x0000000100005d6c
- (void)_registerStateMachineHandlers;	// IMP=0x0000000100005380
- (void)_removeCurrentView;	// IMP=0x000000010000530c
- (void)_showSyncingView;	// IMP=0x00000001000052d8
- (void)_clickedErrorRetryButton:(id)arg1;	// IMP=0x00000001000052b8
- (void)_removeErrorMessageView;	// IMP=0x0000000100005224
- (void)_showErrorView;	// IMP=0x0000000100004c14
- (void)_removeWaitingView;	// IMP=0x0000000100004b80
- (void)_showWaitingView;	// IMP=0x00000001000048d8
- (void)_removeLoginPromptView;	// IMP=0x0000000100004814
- (void)_showLoginPromptView;	// IMP=0x00000001000045cc
- (id)_menuItems;	// IMP=0x00000001000042ec
- (void)_showAuthenticationDialog;	// IMP=0x00000001000040cc
- (void)_removeTopMenu;	// IMP=0x000000010000400c
- (void)_setScreenSaverEnabledForCloudLibrary;	// IMP=0x0000000100003dc0
- (void)_removeNoMusicView;	// IMP=0x0000000100003d2c
- (void)_showNoMusicView;	// IMP=0x0000000100003b38
- (void)_removeCloudProgressView;	// IMP=0x0000000100003aa4
- (void)_showCloudProgressView;	// IMP=0x0000000100003954
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100003818
- (id)preferredFocusEnvironments;	// IMP=0x0000000100003744
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000036f0
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000369c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000035c8
- (void)viewDidLoad;	// IMP=0x0000000100003450
- (void)dealloc;	// IMP=0x00000001000033d8
- (id)init;	// IMP=0x0000000100003310

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

