//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "_UIFloatingContentViewDelegate.h"

@class MPIdentifierSet, MPModelObject, NSArray, NSNumber, NSString, TVImageProxy, TVImageView, TVLabel, TVMusicBarsView, TVMusicSocialBadge, UIColor, UIImage, UIImageView, _UIFloatingContentView;

@interface TVMusicSongCell : UICollectionViewCell <_UIFloatingContentViewDelegate>
{
    TVLabel *_titleLabel;	// 8 = 0x8
    TVLabel *_artistLabel;	// 16 = 0x10
    TVLabel *_albumLabel;	// 24 = 0x18
    TVLabel *_durationLabel;	// 32 = 0x20
    TVLabel *_ordinalLabel;	// 40 = 0x28
    TVLabel *_headingLabel;	// 48 = 0x30
    TVImageView *_thumbnailView;	// 56 = 0x38
    UIImageView *_explicitBadgeView;	// 64 = 0x40
    UIImageView *_popularityIndicatorView;	// 72 = 0x48
    UIImageView *_videoBadgeView;	// 80 = 0x50
    NSArray *_labels;	// 88 = 0x58
    TVMusicBarsView *_musicBarsView;	// 96 = 0x60
    _Bool _isObservingPlayer;	// 104 = 0x68
    UIImageView *_playIconView;	// 112 = 0x70
    UIImage *_popularityOnImage;	// 120 = 0x78
    UIImageView *_watchedCheckmarkImageView;	// 128 = 0x80
    UIColor *_titleColor;	// 136 = 0x88
    _Bool _didConfigureOrdinal;	// 144 = 0x90
    _Bool _isExplicit;	// 145 = 0x91
    _Bool _hasOrdinal;	// 146 = 0x92
    _Bool _fullWidthStyle;	// 147 = 0x93
    _Bool _showPlayIconWhenFocused;	// 148 = 0x94
    _Bool _enabled;	// 149 = 0x95
    _Bool _focusable;	// 150 = 0x96
    _Bool _isWatched;	// 151 = 0x97
    _Bool _ordinalVisible;	// 152 = 0x98
    _Bool _playIconVisible;	// 153 = 0x99
    _Bool _musicBarsVisible;	// 154 = 0x9a
    _Bool _hasThumbnailOverrideFrame;	// 155 = 0x9b
    long long _songType;	// 160 = 0xa0
    UIImage *_placeholderImage;	// 168 = 0xa8
    NSString *_title;	// 176 = 0xb0
    NSString *_artist;	// 184 = 0xb8
    NSString *_album;	// 192 = 0xc0
    NSString *_heading;	// 200 = 0xc8
    double _duration;	// 208 = 0xd0
    NSString *_durationString;	// 216 = 0xd8
    unsigned long long _ordinalValue;	// 224 = 0xe0
    NSNumber *_popularity;	// 232 = 0xe8
    NSNumber *_popularityThreshold;	// 240 = 0xf0
    TVMusicSocialBadge *_socialBadge;	// 248 = 0xf8
    MPIdentifierSet *_songIdentifier;	// 256 = 0x100
    _UIFloatingContentView *_floatingView;	// 264 = 0x108
    MPModelObject *_playbackItem;	// 272 = 0x110
    MPModelObject *_playbackContainer;	// 280 = 0x118
    struct CGPoint _socialBadgeOffset;	// 288 = 0x120
    struct CGRect _thumbnailOverrideFrame;	// 304 = 0x130
}

+ (id)songCellFromElement:(id)arg1 existingView:(id)arg2;	// IMP=0x00000001000100d8
+ (void)registerElements;	// IMP=0x0000000100010024
@property(nonatomic) _Bool hasThumbnailOverrideFrame; // @synthesize hasThumbnailOverrideFrame=_hasThumbnailOverrideFrame;
@property(retain, nonatomic) MPModelObject *playbackContainer; // @synthesize playbackContainer=_playbackContainer;
@property(retain, nonatomic) MPModelObject *playbackItem; // @synthesize playbackItem=_playbackItem;
@property(nonatomic) _Bool musicBarsVisible; // @synthesize musicBarsVisible=_musicBarsVisible;
@property(nonatomic) _Bool playIconVisible; // @synthesize playIconVisible=_playIconVisible;
@property(nonatomic) _Bool ordinalVisible; // @synthesize ordinalVisible=_ordinalVisible;
@property(retain, nonatomic) _UIFloatingContentView *floatingView; // @synthesize floatingView=_floatingView;
@property(retain, nonatomic) MPIdentifierSet *songIdentifier; // @synthesize songIdentifier=_songIdentifier;
@property(nonatomic) struct CGPoint socialBadgeOffset; // @synthesize socialBadgeOffset=_socialBadgeOffset;
@property(nonatomic) struct CGRect thumbnailOverrideFrame; // @synthesize thumbnailOverrideFrame=_thumbnailOverrideFrame;
@property(retain, nonatomic) TVMusicSocialBadge *socialBadge; // @synthesize socialBadge=_socialBadge;
@property(nonatomic) _Bool isWatched; // @synthesize isWatched=_isWatched;
@property(nonatomic) _Bool focusable; // @synthesize focusable=_focusable;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool showPlayIconWhenFocused; // @synthesize showPlayIconWhenFocused=_showPlayIconWhenFocused;
@property(retain, nonatomic) NSNumber *popularityThreshold; // @synthesize popularityThreshold=_popularityThreshold;
@property(retain, nonatomic) NSNumber *popularity; // @synthesize popularity=_popularity;
@property(nonatomic) _Bool fullWidthStyle; // @synthesize fullWidthStyle=_fullWidthStyle;
@property(nonatomic) _Bool hasOrdinal; // @synthesize hasOrdinal=_hasOrdinal;
@property(nonatomic) unsigned long long ordinalValue; // @synthesize ordinalValue=_ordinalValue;
@property(nonatomic) _Bool isExplicit; // @synthesize isExplicit=_isExplicit;
@property(retain, nonatomic) NSString *durationString; // @synthesize durationString=_durationString;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *heading; // @synthesize heading=_heading;
@property(retain, nonatomic) NSString *album; // @synthesize album=_album;
@property(retain, nonatomic) NSString *artist; // @synthesize artist=_artist;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(nonatomic) long long songType; // @synthesize songType=_songType;
- (void).cxx_destruct;	// IMP=0x0000000100056844
- (void)floatingContentView:(id)arg1 isTransitioningFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;	// IMP=0x000000010005654c
- (void)_layoutMusicBarsView;	// IMP=0x0000000100056360
- (void)_updateVideoBadge;	// IMP=0x000000010005613c
- (_Bool)_hasVideoBadge;	// IMP=0x00000001000560f4
- (_Bool)_hasThumbnail;	// IMP=0x0000000100056084
- (unsigned long long)_floatingViewControlState;	// IMP=0x000000010005605c
- (_Bool)_shouldShowPlayIcon;	// IMP=0x0000000100055fdc
- (void)_playbackStatusChanged:(id)arg1;	// IMP=0x0000000100055fd0
- (void)_updatePlayingState;	// IMP=0x0000000100055d84
@property(readonly, nonatomic) struct CGSize thumbnailSize;
- (void)_setColorsForCurrentUserInterfaceStyle;	// IMP=0x00000001000558c4
- (void)_updateColorsForUserInterfaceStyle:(long long)arg1;	// IMP=0x00000001000550cc
- (void)_layoutLabel:(id)arg1;	// IMP=0x0000000100054fec
- (id)_createLabelAtPosition:(double)arg1 width:(double)arg2;	// IMP=0x0000000100054f4c
@property(readonly, nonatomic) TVImageView *thumbnailImageView;
@property(retain, nonatomic) UIImage *thumbnailImage;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100054cfc
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100054be0
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100054ac4
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010005495c
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x00000001000548f4
- (void)setPlayItem:(id)arg1 inContainer:(id)arg2;	// IMP=0x00000001000547a4
@property(readonly, nonatomic) _Bool hasPlaylistOrdinal;
- (double)_ordinalWidth;	// IMP=0x0000000100054218
- (void)_updateOrdinalLabel;	// IMP=0x0000000100053f44
- (id)_popularityImageForPopularity:(id)arg1;	// IMP=0x0000000100053de0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000535d0
- (void)_adjustThumbnailForFocusState;	// IMP=0x000000010005344c
- (void)layoutSubviews;	// IMP=0x0000000100052420
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010005212c
@property(retain, nonatomic) TVImageProxy *thumbnail;
@property(readonly, nonatomic) double cellHeight;
- (void)prepareForReuse;	// IMP=0x0000000100051bcc
- (_Bool)canBecomeFocused;	// IMP=0x0000000100051bc0
- (void)dealloc;	// IMP=0x000000010005169c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100050f28
- (long long)_songCellTypeFromTrackTypeAttribute:(id)arg1;	// IMP=0x000000010001119c
- (void)_setPlaybackIdentifiersWithAttributes:(id)arg1;	// IMP=0x0000000100010b34
- (void)layoutWithElement:(id)arg1;	// IMP=0x00000001000101a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

