//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MPModelPlayEvent, MPModelSong, NSData, NSError, NSOperationQueue, NSString, UIActivityIndicatorView, UIImageView, UILabel, UIScrollView, UIView;

@interface TVMusicLyricsViewController : UIViewController
{
    UIImageView *_artworkImageView;	// 8 = 0x8
    UIImageView *_backgroundImageView;	// 16 = 0x10
    UIView *_artworkShadowView;	// 24 = 0x18
    UILabel *_lyricsLabel;	// 32 = 0x20
    UIScrollView *_lyricsScrollView;	// 40 = 0x28
    UIActivityIndicatorView *_spinnerView;	// 48 = 0x30
    UILabel *_songTitleLabel;	// 56 = 0x38
    UILabel *_songSubtitleLabel;	// 64 = 0x40
    double _startViewTime;	// 72 = 0x48
    MPModelSong *_song;	// 80 = 0x50
    _Bool _viewAppeared;	// 88 = 0x58
    NSError *_storeLyricsError;	// 96 = 0x60
    NSString *_PAFFeatureName;	// 104 = 0x68
    NSData *_PAFRecommendationData;	// 112 = 0x70
    MPModelPlayEvent *_PAFContainerData;	// 120 = 0x78
    NSString *_lyricsText;	// 128 = 0x80
    NSString *_lyricsID;	// 136 = 0x88
}

+ (id)HTMLifyNewlines:(id)arg1;	// IMP=0x000000010000f95c
+ (id)attributedStringFromLyricsString:(id)arg1;	// IMP=0x000000010000f748
@property(copy, nonatomic) NSString *lyricsID; // @synthesize lyricsID=_lyricsID;
@property(copy, nonatomic) NSString *lyricsText; // @synthesize lyricsText=_lyricsText;
@property(retain, nonatomic) MPModelPlayEvent *PAFContainerData; // @synthesize PAFContainerData=_PAFContainerData;
@property(retain, nonatomic) NSData *PAFRecommendationData; // @synthesize PAFRecommendationData=_PAFRecommendationData;
@property(copy, nonatomic) NSString *PAFFeatureName; // @synthesize PAFFeatureName=_PAFFeatureName;
- (void).cxx_destruct;	// IMP=0x000000010000fe98
- (id)_resizeImage:(struct CGImage *)arg1 targetSize:(struct CGSize)arg2;	// IMP=0x000000010000fd10
- (id)_blurredImageWithImage:(id)arg1 targetSize:(struct CGSize)arg2;	// IMP=0x000000010000fb60
@property(readonly, nonatomic) NSOperationQueue *lyricsOperationQueue;
- (void)_handleTogglePlayPause;	// IMP=0x000000010000f6e0
- (void)_reportPAFEventForLyricsView;	// IMP=0x000000010000f524
- (void)_showErrorAlertWithTitle:(id)arg1 message:(id)arg2;	// IMP=0x000000010000f388
- (void)viewWillLayoutSubviews;	// IMP=0x000000010000ec04
- (id)preferredFocusEnvironments;	// IMP=0x000000010000eb94
@property(readonly, nonatomic) NSString *songArtist;
@property(readonly, nonatomic) NSString *songAlbum;
@property(readonly, nonatomic) NSString *songTitle;
- (_Bool)_showLyrics:(id)arg1 withLyricsID:(id)arg2 error:(id)arg3;	// IMP=0x000000010000e74c
- (void)_loadAndDisplayStoreLyrics;	// IMP=0x000000010000e3c0
- (void)_hideActivityIndicator;	// IMP=0x000000010000e374
- (void)_showActivityIndicator;	// IMP=0x000000010000e26c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010000e21c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000e170
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000d9a4
- (void)viewDidLoad;	// IMP=0x000000010000d2c0
- (id)initWithSong:(id)arg1;	// IMP=0x000000010000d238

@end

