//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicTableViewController.h"

@interface TVMusicLibraryComposersViewController : TVMusicTableViewController
{
}

- (id)_previewViewControllerForIndexPath:(id)arg1;	// IMP=0x0000000100068b28
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100068a40
- (void)_setColorsForCell:(id)arg1 indexPath:(id)arg2 isFocused:(_Bool)arg3 withAnimationCoordinator:(id)arg4;	// IMP=0x0000000100068848
- (id)_textColor;	// IMP=0x00000001000687b4
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000687a8
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000685cc
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000685c8
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100068554
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000683b4
- (void)_handlePlayPause:(id)arg1;	// IMP=0x0000000100068188
- (void)viewDidLoad;	// IMP=0x0000000100067e3c
- (id)init;	// IMP=0x0000000100067b00

@end

