//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicMPLibraryRequestFactory : NSObject
{
}

+ (id)propertySetForSongsInContextMenu;	// IMP=0x000000010006db48
+ (id)propertySetForMovie;	// IMP=0x000000010006da60
+ (id)propertySetForTVEpisode;	// IMP=0x000000010006d84c
+ (id)propertySetForSongsWithDetails:(_Bool)arg1;	// IMP=0x000000010006d118
+ (id)propertySetForAlbumDetails;	// IMP=0x000000010006cdf8
+ (id)composersLibraryRequest;	// IMP=0x000000010006cc54
+ (id)genresLibraryRequest;	// IMP=0x000000010006cab0
+ (id)musicVideosLibraryRequest;	// IMP=0x000000010006c9e8
+ (id)artistsLibraryRequest;	// IMP=0x000000010006c824
+ (id)compilationsLibraryRequest;	// IMP=0x000000010006c814
+ (id)albumsLibraryRequestForArtist:(id)arg1;	// IMP=0x000000010006c73c
+ (id)albumsLibraryRequest;	// IMP=0x000000010006c72c
+ (id)_albumsLibraryRequestWithVariants:(unsigned long long)arg1;	// IMP=0x000000010006c628
+ (id)playlistsLibraryRequestWithParentPlaylistFolder:(id)arg1 userEditableOnly:(_Bool)arg2 allowEmptyPlaylists:(_Bool)arg3;	// IMP=0x000000010006c230
+ (id)playlistsLibraryRequestWithParentPlaylistFolder:(id)arg1;	// IMP=0x000000010006c21c
+ (id)TVEpisodeLibraryRequestWithAdamID:(long long)arg1;	// IMP=0x000000010006c01c
+ (id)_songsLibraryRequestForContextMenuWithPlaylist:(id)arg1 songProperties:(id)arg2;	// IMP=0x000000010006bd8c
+ (id)songsLibraryRequestForContextMenuWithPlaylist:(id)arg1;	// IMP=0x000000010006bd04
+ (id)songsLibraryRequestForPlaylist:(id)arg1;	// IMP=0x000000010006bc78
+ (id)songsAndMusicVideosLibraryRequestForContextMenu;	// IMP=0x000000010006bbb4
+ (id)songsLibraryRequestForContextMenu;	// IMP=0x000000010006baf0
+ (id)songsLibraryRequestForAlbum:(id)arg1;	// IMP=0x000000010006b854
+ (id)songsLibraryRequestForAlbumDetails;	// IMP=0x000000010006b768
+ (id)songsLibraryRequest;	// IMP=0x000000010006b6a0
+ (id)moviesLibraryRequest;	// IMP=0x000000010006b5a0
+ (id)TVEpisodesLibraryRequestForShow:(id)arg1 season:(id)arg2;	// IMP=0x000000010006b1bc
+ (id)TVSeasonsLibraryRequestForShow:(id)arg1;	// IMP=0x000000010006ae18
+ (id)TVShowsAndMoviesLibraryRequest;	// IMP=0x000000010006ab18
+ (id)TVShowsLibraryRequest;	// IMP=0x000000010006a858
+ (id)recentlyAddedlibraryRequest;	// IMP=0x0000000100069cc4

@end

