//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVMusicLibraryButtonFactory : NSObject
{
}

+ (id)allSeasonsButton;	// IMP=0x0000000100027178
+ (id)goToShowButton;	// IMP=0x0000000100027078
+ (id)wideGoToArtistButton;	// IMP=0x0000000100026f78
+ (id)wideShuffleButton;	// IMP=0x0000000100026e78
+ (id)widePlayButton;	// IMP=0x0000000100026d78
+ (id)normalMoreButton;	// IMP=0x0000000100026c78
+ (id)normalShuffleButton;	// IMP=0x0000000100026b78

@end

