//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PBSViewServicePresenter.h"
#import "TVIBackgroundViewDataSource.h"
#import "TVIBackgroundViewDelegate.h"

@class NSMapTable, NSMutableSet, NSString, TVIAssetManager, TVIBackgroundView, UIView, UIViewPropertyAnimator;

@interface TVIMainViewController : UIViewController <PBSViewServicePresenter, TVIBackgroundViewDelegate, TVIBackgroundViewDataSource>
{
    _Bool _playbackPausedWhileScreenSaverIsUp;	// 8 = 0x8
    _Bool _presentationEnded;	// 9 = 0x9
    TVIAssetManager *_assetManager;	// 16 = 0x10
    CDUnknownBlockType _storeDemoModeResetBlock;	// 24 = 0x18
    id _nowPlayingStateObserver;	// 32 = 0x20
    TVIBackgroundView *_backgroundView;	// 40 = 0x28
    NSMutableSet *_assetsToRemove;	// 48 = 0x30
    NSMapTable *_mediaItemToAssetMap;	// 56 = 0x38
    UIViewPropertyAnimator *_fadeInAnimator;	// 64 = 0x40
    UIViewPropertyAnimator *_fadeOutAnimator;	// 72 = 0x48
    UIView *_internalShroudView;	// 80 = 0x50
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0000000100005f24
+ (id)_exportedInterface;	// IMP=0x0000000100005e08
@property(readonly, nonatomic) UIView *internalShroudView; // @synthesize internalShroudView=_internalShroudView;
@property(retain, nonatomic) UIViewPropertyAnimator *fadeOutAnimator; // @synthesize fadeOutAnimator=_fadeOutAnimator;
@property(retain, nonatomic) UIViewPropertyAnimator *fadeInAnimator; // @synthesize fadeInAnimator=_fadeInAnimator;
@property(nonatomic) _Bool presentationEnded; // @synthesize presentationEnded=_presentationEnded;
@property(retain, nonatomic) NSMapTable *mediaItemToAssetMap; // @synthesize mediaItemToAssetMap=_mediaItemToAssetMap;
@property(retain, nonatomic) NSMutableSet *assetsToRemove; // @synthesize assetsToRemove=_assetsToRemove;
@property(retain, nonatomic) TVIBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) id nowPlayingStateObserver; // @synthesize nowPlayingStateObserver=_nowPlayingStateObserver;
@property(nonatomic) _Bool playbackPausedWhileScreenSaverIsUp; // @synthesize playbackPausedWhileScreenSaverIsUp=_playbackPausedWhileScreenSaverIsUp;
@property(copy, nonatomic) CDUnknownBlockType storeDemoModeResetBlock; // @synthesize storeDemoModeResetBlock=_storeDemoModeResetBlock;
@property(retain, nonatomic) TVIAssetManager *assetManager; // @synthesize assetManager=_assetManager;
- (void).cxx_destruct;	// IMP=0x0000000100008030
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100007ae8
- (double)backgroundView:(id)arg1 startTimeForMediaItem:(id)arg2;	// IMP=0x0000000100007a90
- (void)backgroundView:(id)arg1 lastPlayedMediaItem:(id)arg2 elapsedTime:(double)arg3 resetList:(_Bool)arg4;	// IMP=0x0000000100007924
- (void)backgroundView:(id)arg1 didEncounterPlaybackErrorForMediaItem:(id)arg2;	// IMP=0x00000001000078d0
- (void)backgroundView:(id)arg1 didTransitionFromMediaItem:(id)arg2 toMediaItem:(id)arg3;	// IMP=0x00000001000077f8
- (void)backgroundView:(id)arg1 willTransitionFromMediaItem:(id)arg2 toMediaItem:(id)arg3;	// IMP=0x00000001000077f4
- (void)_enumerateActiveMediaItemsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007684
- (id)_assetForMediaItem:(id)arg1;	// IMP=0x0000000100007600
- (void)_setAsset:(id)arg1 forMediaItem:(id)arg2;	// IMP=0x0000000100007550
- (void)_mediaPlaybackStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000072ec
- (void)_mediaRemotePlaybackApplicationStateDidChange;	// IMP=0x00000001000070c4
- (id)_mediaItemWithPlayableAsset:(id)arg1;	// IMP=0x0000000100006f0c
- (id)_defaultMediaItemForResourceName:(id)arg1;	// IMP=0x0000000100006dbc
- (id)_defaultMediaItem;	// IMP=0x0000000100006bf0
- (void)_removeAsset:(id)arg1;	// IMP=0x0000000100006b58
- (_Bool)_unlockAsset:(id)arg1;	// IMP=0x0000000100006a90
- (_Bool)_lockAsset:(id)arg1;	// IMP=0x0000000100006a14
- (void)_dequeueMediaItem:(id)arg1;	// IMP=0x0000000100006954
- (void)_queueDefaultAsset;	// IMP=0x00000001000068e4
- (_Bool)_queueAsset:(id)arg1;	// IMP=0x00000001000067b8
- (void)_queueNextPlayableAssetFollowingAsset:(id)arg1 inPlaybackDirection:(long long)arg2;	// IMP=0x00000001000065e0
- (void)_queueNextPlayableAssetBeforeAsset:(id)arg1;	// IMP=0x00000001000065d0
- (void)_queueNextPlayableAssetAfterAsset:(id)arg1;	// IMP=0x00000001000065c0
- (id)_initialAsset;	// IMP=0x00000001000060a0
- (void)_enumerateObjectsInArray:(id)arg1 startObject:(id)arg2 reverse:(_Bool)arg3 usingBlock:(CDUnknownBlockType)arg4;	// IMP=0x0000000100005f40
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005b98
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x0000000100005624
- (_Bool)isSyntheticB39GestureWithRecognizer:(id)arg1;	// IMP=0x00000001000055ac
- (void)_swipeRightAction:(id)arg1;	// IMP=0x00000001000052f4
- (void)_swipeLeftAction:(id)arg1;	// IMP=0x0000000100005118
- (void)_internalPlayPauseAction:(id)arg1;	// IMP=0x0000000100004aac
- (void)_tapAction:(id)arg1;	// IMP=0x0000000100004930
- (void)_selectAction:(id)arg1;	// IMP=0x0000000100004790
- (void)_rightAction:(id)arg1;	// IMP=0x00000001000045e8
- (void)_leftAction:(id)arg1;	// IMP=0x0000000100004440
- (void)_playPauseTapButtonAction:(id)arg1;	// IMP=0x0000000100004248
- (void)loadView;	// IMP=0x00000001000034ec
- (void)dealloc;	// IMP=0x0000000100003404
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010000312c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

