//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVSettingsiTunesMoviesFacade : NSObject
{
    long long _playbackQuality;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00000001000a24b8
@property(nonatomic) long long playbackQuality; // @synthesize playbackQuality=_playbackQuality;
- (void)_updatePlaybackQuality;	// IMP=0x00000001000a2770
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000a26fc
- (void)dealloc;	// IMP=0x00000001000a25dc
- (id)init;	// IMP=0x00000001000a2538

@end

