//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class TVSettingsPreviouslyUsedEmailFacade, UIBarButtonItem;

@interface TVSettingsPreviouslyUsedEmailViewController : TSKViewController
{
    TVSettingsPreviouslyUsedEmailFacade *_emailFacade;	// 8 = 0x8
    UIBarButtonItem *_editButtonItem;	// 16 = 0x10
    UIBarButtonItem *_doneButtonItem;	// 24 = 0x18
}

@property(retain, nonatomic) UIBarButtonItem *doneButtonItem; // @synthesize doneButtonItem=_doneButtonItem;
@property(retain, nonatomic) UIBarButtonItem *editButtonItem; // @synthesize editButtonItem=_editButtonItem;
@property(retain, nonatomic) TVSettingsPreviouslyUsedEmailFacade *emailFacade; // @synthesize emailFacade=_emailFacade;
- (void).cxx_destruct;	// IMP=0x0000000100050200
- (void)_clearAll;	// IMP=0x000000010004fdcc
- (void)_showDeleteConfirmationForItem:(id)arg1;	// IMP=0x000000010004f838
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x000000010004f7d0
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x000000010004f7a8
- (void)clearAll;	// IMP=0x000000010004f79c
- (void)willResumeFromBackground;	// IMP=0x000000010004f790
- (id)title;	// IMP=0x000000010004f720
- (id)loadSettingGroups;	// IMP=0x000000010004f350
- (void)_updateNavigationItem;	// IMP=0x000000010004f1f4
- (void)toggleEditMode:(id)arg1;	// IMP=0x000000010004f070
- (void)dealloc;	// IMP=0x000000010004efe8
- (void)didReceiveMemoryWarning;	// IMP=0x000000010004efb4
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010004eea0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010004ee4c
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010004ed80

@end

