//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@class NSArray, TVPAudioRoute, TVPAudioRoutingController;

@interface TVSettingsAudioRouteViewController : TSKViewController
{
    TVPAudioRoutingController *_routingController;	// 8 = 0x8
    TVPAudioRoute *_recentlySelectedRoute;	// 16 = 0x10
    NSArray *_routes;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000a052c
- (id)_identifierForRoute:(id)arg1;	// IMP=0x00000001000a0408
- (void)_selectRoute:(id)arg1;	// IMP=0x00000001000a03a0
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;	// IMP=0x00000001000a008c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010009fe70
- (id)loadSettingGroups;	// IMP=0x000000010009fa68
- (void)viewDidLoad;	// IMP=0x000000010009f9a4
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010009f910

@end

