//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class TVSettingsImageView;

@interface TVSettingsRegulatoryViewController : UIViewController
{
    TVSettingsImageView *_imageView;	// 8 = 0x8
}

@property(retain, nonatomic) TVSettingsImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;	// IMP=0x000000010004b3d4
- (id)_regulatoryImageForUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010004b264
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010004b158
- (void)viewDidLayoutSubviews;	// IMP=0x000000010004b008
- (void)viewDidLoad;	// IMP=0x000000010004aea0

@end

