//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "PBSExternalControlSystemDelegate.h"

@class NSString, PBSExternalControlSystem, TVSettings3rdPartyRemotesFacade, TVSettingsBluetoothFacade, TVSettingsSelectIRConfigurationViewController;

@interface TVSettingsRemotesViewController : TSKViewController <PBSExternalControlSystemDelegate>
{
    _Bool _updatingPairedAppleRemoteState;	// 8 = 0x8
    _Bool _pairedWithAppleRemote;	// 9 = 0x9
    TVSettingsSelectIRConfigurationViewController *_selectIRConfigurationViewController;	// 16 = 0x10
    PBSExternalControlSystem *_externalControlSystem;	// 24 = 0x18
    TVSettingsBluetoothFacade *_bluetoothFacade;	// 32 = 0x20
    TVSettings3rdPartyRemotesFacade *_remoteFacade;	// 40 = 0x28
}

+ (id)stringForCurrentVolumePolicyWithExternalControlSystem:(id)arg1;	// IMP=0x00000001000a317c
@property(retain, nonatomic) TVSettings3rdPartyRemotesFacade *remoteFacade; // @synthesize remoteFacade=_remoteFacade;
@property(retain, nonatomic) TVSettingsBluetoothFacade *bluetoothFacade; // @synthesize bluetoothFacade=_bluetoothFacade;
@property(retain, nonatomic) PBSExternalControlSystem *externalControlSystem; // @synthesize externalControlSystem=_externalControlSystem;
@property(nonatomic, getter=isPairedWithAppleRemote) _Bool pairedWithAppleRemote; // @synthesize pairedWithAppleRemote=_pairedWithAppleRemote;
@property(nonatomic, getter=isUpdatingPairedAppleRemoteState) _Bool updatingPairedAppleRemoteState; // @synthesize updatingPairedAppleRemoteState=_updatingPairedAppleRemoteState;
@property(nonatomic) __weak TVSettingsSelectIRConfigurationViewController *selectIRConfigurationViewController; // @synthesize selectIRConfigurationViewController=_selectIRConfigurationViewController;
- (void).cxx_destruct;	// IMP=0x00000001000a9524
- (void)_remoteFacadeConfigurationChanged;	// IMP=0x00000001000a9438
- (void)_externalControlSystemConfigurationChanged;	// IMP=0x00000001000a942c
- (void)_updateAppleRemotePairedStateWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a92bc
- (void)_fetchAppleRemotePairedState;	// IMP=0x00000001000a9238
- (void)_showLearnedRemoteFinishedAlertWithName:(id)arg1;	// IMP=0x00000001000a8f54
- (void)_setUpPlaybackButtonsForRemoteWithUUID:(id)arg1;	// IMP=0x00000001000a8bdc
- (void)_showLearnedRemoteOptionsAlertForDevice:(id)arg1 withName:(id)arg2;	// IMP=0x00000001000a8790
- (void)_learnNewRemote;	// IMP=0x00000001000a84d0
- (void)_showSystemControlUnavailableDialog;	// IMP=0x00000001000a82d4
- (_Bool)_canProgramBluetoothRemote;	// IMP=0x00000001000a82c0
- (_Bool)_showLearnedRemotes;	// IMP=0x00000001000a8214
- (id)_systemControlSettingsGroups;	// IMP=0x00000001000a75d8
- (id)_remoteSettingsGroups;	// IMP=0x00000001000a671c
- (id)_appleRemoteSettingGroups;	// IMP=0x00000001000a5abc
- (void)externalControlSystemDidUpdatePolicy:(id)arg1;	// IMP=0x00000001000a5a10
- (void)externalControlSystem:(id)arg1 didReceiveDeviceEvent:(long long)arg2;	// IMP=0x00000001000a5964
- (void)externalControlSystem:(id)arg1 didChangeReadyStatus:(_Bool)arg2;	// IMP=0x00000001000a58b8
- (void)_activateKonamiCodeForUnpair:(id)arg1;	// IMP=0x00000001000a5864
- (void)_showSelectedLearnedRemoteOptionsAlertForDevice:(id)arg1 withName:(id)arg2;	// IMP=0x00000001000a4474
- (void)_didSelectLearnedRemoteItem:(id)arg1;	// IMP=0x00000001000a4260
- (void)_didSelectLearnNewRemoteItem:(id)arg1;	// IMP=0x00000001000a3ec0
- (void)_didSelectPairAppleRemoteItem:(id)arg1;	// IMP=0x00000001000a3db8
- (void)_didSelectVolumeControlItem:(id)arg1;	// IMP=0x00000001000a3ce8
- (void)_togglePowerItem:(id)arg1;	// IMP=0x00000001000a3c48
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000a3a48
- (id)loadSettingGroups;	// IMP=0x00000001000a395c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000a390c
- (void)viewDidLoad;	// IMP=0x00000001000a3848
- (void)dealloc;	// IMP=0x00000001000a37d0
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000a3558

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

