//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsSetupViewController : TSKViewController
{
}

- (void)_handleResetAllSettingsResultWithError:(id)arg1;	// IMP=0x000000010006d7cc
- (void)_showFailureWithText:(id)arg1;	// IMP=0x000000010006d674
- (void)_showConfirmRestore;	// IMP=0x000000010006d34c
- (void)_showConfirmReset;	// IMP=0x000000010006cee0
- (id)_resetViewController;	// IMP=0x000000010006cb20
- (id)loadSettingGroups;	// IMP=0x000000010006c21c

@end

