//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsNotificationsViewController : TSKViewController
{
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010001ffcc
- (id)loadSettingGroups;	// IMP=0x000000010001fe1c
- (void)dealloc;	// IMP=0x000000010001fd94
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010001fd00

@end

