//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (TVSettings)
- (id)_viewControllersUpToViewController:(id)arg1;	// IMP=0x000000010004bc30
- (void)tvset_popToViewControllerBelowViewController:(id)arg1;	// IMP=0x000000010004bbd4
- (void)tvset_replaceViewControllersAboveViewController:(id)arg1 withViewController:(id)arg2;	// IMP=0x000000010004bb28
@end

