//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBTransaction.h"

@class FBApplicationUpdateScenesTransaction, PBAppTransitionContext;

@interface PBAppTransitionTransaction : FBTransaction
{
    PBAppTransitionContext *_context;	// 8 = 0x8
    FBApplicationUpdateScenesTransaction *_updateScenesTransaction;	// 16 = 0x10
}

@property(retain, nonatomic) FBApplicationUpdateScenesTransaction *updateScenesTransaction; // @synthesize updateScenesTransaction=_updateScenesTransaction;
@property(readonly, nonatomic) PBAppTransitionContext *context; // @synthesize context=_context;
- (void).cxx_destruct;	// IMP=0x00000001000ec9a4
- (void)_handleUpdateScenesTransactionDidComplete;	// IMP=0x00000001000ec834
- (void)_childTransactionDidComplete:(id)arg1;	// IMP=0x00000001000ec794
- (void)_willFailWithReason:(id)arg1;	// IMP=0x00000001000ec760
- (void)_willComplete;	// IMP=0x00000001000ec6b0
- (_Bool)_shouldFailForChildTransaction:(id)arg1;	// IMP=0x00000001000ec6a8
- (void)beginForegroundTransition;	// IMP=0x00000001000ec628
- (id)initWithTransaction:(id)arg1 context:(id)arg2;	// IMP=0x00000001000ec55c
- (id)init;	// IMP=0x00000001000ec520

@end

