//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSMutableArray, NSMutableDictionary;

@interface PBAppSwitcherFocusLayout : UICollectionViewLayout
{
    NSMutableArray *_insertedIndexPaths;	// 8 = 0x8
    NSMutableArray *_deletedIndexPaths;	// 16 = 0x10
    NSMutableDictionary *_finalIndexPathByOriginalIndexPath;	// 24 = 0x18
    long long _numberOfItemsBeforeUpdate;	// 32 = 0x20
    long long _numberOfItems;	// 40 = 0x28
    double _screenHeight;	// 48 = 0x30
    long long _swipeIndex;	// 56 = 0x38
    double _swipeUpOffset;	// 64 = 0x40
}

+ (double)contentOffsetAdjustmentForLastItem;	// IMP=0x00000001000bc12c
+ (Class)invalidationContextClass;	// IMP=0x00000001000bbf5c
+ (Class)layoutAttributesClass;	// IMP=0x00000001000bbf38
@property(readonly, nonatomic) double swipeUpOffset; // @synthesize swipeUpOffset=_swipeUpOffset;
@property(readonly, nonatomic) long long swipeIndex; // @synthesize swipeIndex=_swipeIndex;
@property(readonly, nonatomic) double screenHeight; // @synthesize screenHeight=_screenHeight;
@property(readonly, nonatomic) long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(readonly, nonatomic) long long numberOfItemsBeforeUpdate; // @synthesize numberOfItemsBeforeUpdate=_numberOfItemsBeforeUpdate;
@property(readonly, copy, nonatomic) NSMutableDictionary *finalIndexPathByOriginalIndexPath; // @synthesize finalIndexPathByOriginalIndexPath=_finalIndexPathByOriginalIndexPath;
@property(readonly, copy, nonatomic) NSMutableArray *deletedIndexPaths; // @synthesize deletedIndexPaths=_deletedIndexPaths;
@property(readonly, copy, nonatomic) NSMutableArray *insertedIndexPaths; // @synthesize insertedIndexPaths=_insertedIndexPaths;
- (void).cxx_destruct;	// IMP=0x00000001000bd6c4
- (double)_scrollProgress;	// IMP=0x00000001000bd5a4
- (id)_attributesForIndexPath:(id)arg1 scrollProgress:(double)arg2 swipeOffset:(double)arg3 swipeIndex:(long long)arg4 allowMask:(_Bool)arg5;	// IMP=0x00000001000bcd74
- (void)finalizeCollectionViewUpdates;	// IMP=0x00000001000bccf0
- (void)prepareForCollectionViewUpdates:(id)arg1;	// IMP=0x00000001000bc860
- (void)invalidateLayoutWithContext:(id)arg1;	// IMP=0x00000001000bc6f0
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;	// IMP=0x00000001000bc564
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;	// IMP=0x00000001000bc484
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000bc408
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x00000001000bc154
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;	// IMP=0x00000001000bc054
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;	// IMP=0x00000001000bc02c
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x00000001000bc024
- (struct CGSize)collectionViewContentSize;	// IMP=0x00000001000bbf80
- (id)init;	// IMP=0x00000001000bbe2c

@end

