//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PBBundleLoader : NSObject
{
    NSMutableDictionary *_loadedPluginsByBundleID;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010002f2a8
- (void).cxx_destruct;	// IMP=0x000000010002fa68
- (id)pluginControllerForBundleIdentifier:(id)arg1;	// IMP=0x000000010002fa40
- (void)_loadBundlesFromDirectory:(id)arg1;	// IMP=0x000000010002f424
- (id)init;	// IMP=0x000000010002f3a4
- (void)loadPlugins;	// IMP=0x000000010002f32c

@end

