//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBApplicationProcessObserver.h"
#import "PBScreenSaverManagerObserver.h"

@class NSString, TVSStateMachine;

@interface PBConferenceRoomDisplayManager : NSObject <PBScreenSaverManagerObserver, FBApplicationProcessObserver>
{
    _Bool _crdActive;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00000001000fdcf4
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(nonatomic, getter=isCRDActive) _Bool crdActive; // @synthesize crdActive=_crdActive;
- (void).cxx_destruct;	// IMP=0x0000000100100554
- (void)_updateIfCRDDisabledWhileActive;	// IMP=0x00000001001004a0
- (void)_updateIfCRDForcedOnWhileIdle;	// IMP=0x0000000100100378
- (void)_handleLoadingTimeout;	// IMP=0x000000010010032c
- (id)_showCRDWaitingScreen;	// IMP=0x0000000100100298
- (void)_exitCRDApp;	// IMP=0x0000000100100078
- (id)_launchCRDApp;	// IMP=0x00000001000ffe14
- (void)_initializeStateMachine;	// IMP=0x00000001000fe5f0
- (void)_handleSettingsChanged;	// IMP=0x00000001000fe590
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000fe4c8
- (void)screenSaverManagerDidDismissScreenSaver:(id)arg1;	// IMP=0x00000001000fe498
- (void)screenSaverManagerWillDismissScreenSaver:(id)arg1;	// IMP=0x00000001000fe468
- (void)screenSaverManagerDidPresentScreenSaver:(id)arg1;	// IMP=0x00000001000fe438
- (void)screenSaverManagerWillPresentScreenSaver:(id)arg1;	// IMP=0x00000001000fe408
- (_Bool)dismissCRDWaitingScreen;	// IMP=0x00000001000fe34c
- (void)handleTermination;	// IMP=0x00000001000fe31c
- (void)canStopCRDWithResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001000fe140
- (void)endStopCRD;	// IMP=0x00000001000fe110
- (void)beginStopCRD;	// IMP=0x00000001000fe0e0
- (_Bool)startCRDWithReason:(unsigned long long)arg1;	// IMP=0x00000001000fdf9c
- (void)dealloc;	// IMP=0x00000001000fded4
- (id)_init;	// IMP=0x00000001000fddf0
- (id)init;	// IMP=0x00000001000fddb0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

