//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBLanguageChangeObserver : NSObject
{
    _Bool _observing;	// 8 = 0x8
    id <PBLanguageChangeObserverDelegate> _delegate;	// 16 = 0x10
}

@property(nonatomic, getter=isObserving) _Bool observing; // @synthesize observing=_observing;
@property(nonatomic) __weak id <PBLanguageChangeObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100058994
- (void)localeDidChange;	// IMP=0x0000000100058880
- (void)unsubscribeFromLocaleChangeNotification;	// IMP=0x000000010005884c
- (void)subscribeToLocaleChangeNotification;	// IMP=0x0000000100058774
- (void)languageDidChangeWithSource:(long long)arg1;	// IMP=0x0000000100058710
- (void)unsubscribeFromLanguageChangeNotification;	// IMP=0x00000001000586c4
- (void)subscribeToLanguageChangeNotification;	// IMP=0x0000000100058530
- (void)stopObservingLanguageChanges;	// IMP=0x00000001000584d0
- (void)startObservingLanguageChanges;	// IMP=0x0000000100058470
- (void)dealloc;	// IMP=0x0000000100058424

@end

