//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBSceneDeactivationAssertionManager : NSObject
{
}

+ (void)checkInTransitionAssertion;	// IMP=0x00000001000afd00
+ (void)checkOutTransitionAssertion;	// IMP=0x00000001000afcdc
+ (void)checkInSiriFullScreenAssertion;	// IMP=0x00000001000afcb8
+ (void)checkOutSiriFullScreenAssertion;	// IMP=0x00000001000afc94
+ (void)checkInSiriAssertion;	// IMP=0x00000001000afc70
+ (void)checkOutSiriAssertion;	// IMP=0x00000001000afc4c
+ (void)checkInScreenSaverAssertion;	// IMP=0x00000001000afc28
+ (void)checkOutScreenSaverAssertion;	// IMP=0x00000001000afc04
+ (void)checkInHotBlackAssertion;	// IMP=0x00000001000afbe0
+ (void)checkOutHotBlackAssertion;	// IMP=0x00000001000afbbc
+ (void)checkInDialogAssertion;	// IMP=0x00000001000afb98
+ (void)checkOutDialogAssertion;	// IMP=0x00000001000afb74
+ (void)checkInAppSwitcherAssertion;	// IMP=0x00000001000afb50
+ (void)checkOutAppSwitcherAssertion;	// IMP=0x00000001000afb2c
+ (void)checkInAirPlayAssertion;	// IMP=0x00000001000afb08
+ (void)checkOutAirPlayAssertion;	// IMP=0x00000001000afae4

@end

