//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, NSMutableArray, NSObject<OS_dispatch_source>, PBRemoteViewController, TVSPreferences, TVSStateMachine;

@interface PBScreenSaverManager : NSObject
{
    _Bool _holdOffForMusicEnabled;	// 8 = 0x8
    _Bool _needsDismissal;	// 9 = 0x9
    double _screenSaverActivationDelayInMinutes;	// 16 = 0x10
    unsigned long long _displayState;	// 24 = 0x18
    TVSPreferences *_screenSaverPrefs;	// 32 = 0x20
    TVSStateMachine *_stateMachine;	// 40 = 0x28
    NSMutableArray *_pendingActivationRequests;	// 48 = 0x30
    PBRemoteViewController *_screenSaverViewController;	// 56 = 0x38
    NSHashTable *_observers;	// 64 = 0x40
    NSObject<OS_dispatch_source> *_watchdogTimer;	// 72 = 0x48
}

+ (id)sharedInstance;	// IMP=0x0000000100017a44
@property(retain, nonatomic) NSObject<OS_dispatch_source> *watchdogTimer; // @synthesize watchdogTimer=_watchdogTimer;
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) PBRemoteViewController *screenSaverViewController; // @synthesize screenSaverViewController=_screenSaverViewController;
@property(nonatomic) _Bool needsDismissal; // @synthesize needsDismissal=_needsDismissal;
@property(readonly, nonatomic) NSMutableArray *pendingActivationRequests; // @synthesize pendingActivationRequests=_pendingActivationRequests;
@property(readonly, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(readonly, nonatomic) TVSPreferences *screenSaverPrefs; // @synthesize screenSaverPrefs=_screenSaverPrefs;
@property(nonatomic) _Bool holdOffForMusicEnabled; // @synthesize holdOffForMusicEnabled=_holdOffForMusicEnabled;
@property(readonly, nonatomic) unsigned long long displayState; // @synthesize displayState=_displayState;
@property(nonatomic) double screenSaverActivationDelayInMinutes; // @synthesize screenSaverActivationDelayInMinutes=_screenSaverActivationDelayInMinutes;
- (void).cxx_destruct;	// IMP=0x000000010001a99c
- (void)_notifyPhotosSourcesDaemon;	// IMP=0x000000010001a898
- (void)_updateActivationDelay;	// IMP=0x000000010001a81c
- (id)_screenSaverControllerClassNameForAppBundleID:(id)arg1;	// IMP=0x000000010001a724
- (id)_screenSaverAppBundleID;	// IMP=0x000000010001a6b8
- (void)_postSystemDidChangeIdleState:(_Bool)arg1;	// IMP=0x000000010001a41c
- (void)_saveScreenSaverSnapshotForWindow:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a18c
- (void)_notifyObserversScreenSaverDidDismiss;	// IMP=0x000000010001a05c
- (void)_notifyObserversScreenSaverWillDismiss;	// IMP=0x0000000100019f2c
- (void)_handleScreenSaverDismissalWithState:(_Bool)arg1;	// IMP=0x0000000100019ea4
- (void)_forceDismissScreenSaver;	// IMP=0x0000000100019e10
- (void)_dismissScreenSaver;	// IMP=0x0000000100019c58
- (void)_activateScreenSaverViewControllerWithInfo:(id)arg1;	// IMP=0x0000000100019634
- (CDUnknownBlockType)_machineStateChangeHandler;	// IMP=0x0000000100019040
- (void)_initializeStateMachine;	// IMP=0x00000001000181c4
- (void)removeObserver:(id)arg1;	// IMP=0x000000010001819c
- (void)addObserver:(id)arg1;	// IMP=0x0000000100018174
@property(readonly, nonatomic) _Bool screenSaverIsActive;
- (_Bool)dismissScreenSaver;	// IMP=0x0000000100017f58
- (void)activateScreenSaverFromUserAction:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100017e30
- (void)fetchInitialPhotoAssets;	// IMP=0x0000000100017e14
- (id)init;	// IMP=0x0000000100017ac8

@end

