//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBOSSoftwareUpdateProcessDelegate.h"

@class NSString, NSTimer, PCSimpleTimer, TVSBackgroundTask;

@interface PBSoftwareUpdateService : NSObject <PBOSSoftwareUpdateProcessDelegate>
{
    _Bool _monitoringEnabled;	// 8 = 0x8
    TVSBackgroundTask *_osSoftwareUpdateInitialCheckTask;	// 16 = 0x10
    TVSBackgroundTask *_osSoftwareUpdatePeriodicCheckTask;	// 24 = 0x18
    PCSimpleTimer *_darkWakeTimer;	// 32 = 0x20
    PCSimpleTimer *_updateDelayExpirationTimer;	// 40 = 0x28
    NSTimer *_vendorBagRefetchTimeoutTimer;	// 48 = 0x30
    CDUnknownBlockType _osSoftwareUpdateCheckResponse;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x00000001000bd71c
@property(copy, nonatomic) CDUnknownBlockType osSoftwareUpdateCheckResponse; // @synthesize osSoftwareUpdateCheckResponse=_osSoftwareUpdateCheckResponse;
@property(nonatomic) __weak NSTimer *vendorBagRefetchTimeoutTimer; // @synthesize vendorBagRefetchTimeoutTimer=_vendorBagRefetchTimeoutTimer;
@property(retain, nonatomic) PCSimpleTimer *updateDelayExpirationTimer; // @synthesize updateDelayExpirationTimer=_updateDelayExpirationTimer;
@property(retain, nonatomic) PCSimpleTimer *darkWakeTimer; // @synthesize darkWakeTimer=_darkWakeTimer;
@property(retain, nonatomic) TVSBackgroundTask *osSoftwareUpdatePeriodicCheckTask; // @synthesize osSoftwareUpdatePeriodicCheckTask=_osSoftwareUpdatePeriodicCheckTask;
@property(retain, nonatomic) TVSBackgroundTask *osSoftwareUpdateInitialCheckTask; // @synthesize osSoftwareUpdateInitialCheckTask=_osSoftwareUpdateInitialCheckTask;
@property(nonatomic) _Bool monitoringEnabled; // @synthesize monitoringEnabled=_monitoringEnabled;
- (void).cxx_destruct;	// IMP=0x00000001000c5028
- (void)osUpdateProcessDidFinishApplyWithData:(id)arg1;	// IMP=0x00000001000c4a34
- (void)osUpdateProcessDidEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x00000001000c47fc
- (void)osUpdateProcessDidUpdateApplyProgressWithData:(id)arg1;	// IMP=0x00000001000c451c
- (void)osUpdateProcessDidStartApplyWithData:(id)arg1;	// IMP=0x00000001000c42a0
- (void)osUpdateProcessDidStartRedownloadWithData:(id)arg1;	// IMP=0x00000001000c4118
- (void)osUpdateProcessDidFinishDownloadWithData:(id)arg1;	// IMP=0x00000001000c3d18
- (void)osUpdateProcessDidUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x00000001000c3ba4
- (void)osUpdateProcessDidStartDownloadWithData:(id)arg1;	// IMP=0x00000001000c3a1c
- (void)osUpdateProcessDidFinishCheckWithData:(id)arg1;	// IMP=0x00000001000c3398
- (void)osUpdateProcessDidStartCheckWithData:(id)arg1;	// IMP=0x00000001000c3224
- (void)_showOSUpdateUpToDateDialog:(_Bool)arg1;	// IMP=0x00000001000c3010
- (void)_showOSUpdateError:(id)arg1 inDomain:(id)arg2 description:(id)arg3;	// IMP=0x00000001000c27ec
- (void)_showApplyConfirmationDialogWithData:(id)arg1;	// IMP=0x00000001000c1edc
- (void)_showOSUpdateDownloadAndApplyConfirmationForUpdate:(id)arg1 largeUpdate:(_Bool)arg2 assetIsDownloaded:(_Bool)arg3;	// IMP=0x00000001000c198c
- (id)_versionForUpdate:(id)arg1;	// IMP=0x00000001000c1830
- (void)_handleManagedConfigurationSettingsChangedNotification:(id)arg1;	// IMP=0x00000001000c1814
- (void)_handleDeviceWillWakeNotification:(id)arg1;	// IMP=0x00000001000c1768
- (void)_handleDeviceWillSleepNotification:(id)arg1;	// IMP=0x00000001000c14fc
- (void)_handleOSUpdatePrefsDidChange;	// IMP=0x00000001000c14c0
- (void)_handlePineBoardPrefsDidChange;	// IMP=0x00000001000c1404
- (void)_precheckConditionsAndPerformAction:(unsigned long long)arg1;	// IMP=0x00000001000c1130
- (_Bool)_isAtHomeSeedUser;	// IMP=0x00000001000c1010
- (void)_startOSUpdateCheckForAction:(unsigned long long)arg1;	// IMP=0x00000001000c0f44
- (_Bool)_serverAllowsAutoApplyUpdates;	// IMP=0x00000001000c085c
- (void)_postVendorBagReloadContinueAutoApply;	// IMP=0x00000001000c048c
- (void)_reloadVendorBag;	// IMP=0x00000001000c035c
- (void)_osUpdateDelayedUpdateExpirationTimerFired:(id)arg1;	// IMP=0x00000001000c0298
- (void)_scheduleOSUpdateCheckForExpiredDelay;	// IMP=0x00000001000c0000
- (void)_osUpdateDarkWakeTimerFired:(id)arg1;	// IMP=0x00000001000bfe40
- (void)_scheduleOSUpdateDarkWakeAt:(id)arg1;	// IMP=0x00000001000bfd54
- (void)_cancelOSUpdateDarkWakeTimer;	// IMP=0x00000001000bfcdc
- (void)_scheduleOSUpdateTimerForNextDarkWake;	// IMP=0x00000001000bfa50
- (void)_scheduleOSUpdateOnSleepCheck;	// IMP=0x00000001000bf7e4
- (void)_scheduleOSUpdateCheck;	// IMP=0x00000001000bf300
- (_Bool)_okToCheckForOSSoftwareUpdate;	// IMP=0x00000001000bf2d8
- (void)purgeAssetsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bf264
- (void)purgeableAssetSpaceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bf1f0
- (void)rebootDueToSlowUpdate;	// IMP=0x00000001000bf1a4
- (void)notePlaybackStarted;	// IMP=0x00000001000bf154
- (void)cancelOSSoftwareUpdate;	// IMP=0x00000001000bf104
- (void)installUpdate:(id)arg1 withOptions:(id)arg2 withResult:(CDUnknownBlockType)arg3;	// IMP=0x00000001000bedf4
- (void)reallyPerformOSSoftwareRestore;	// IMP=0x00000001000bedb4
- (void)purgeDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bea80
- (void)cancelDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be978
- (void)startDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be728
- (void)reallyPerformMDMOSSoftwareUpdateCheck;	// IMP=0x00000001000be6e8
- (void)reallyPerformOSSoftwareUpdateCheck;	// IMP=0x00000001000be6a8
- (void)checkForOSUpdatesWithConditions:(id)arg1 response:(CDUnknownBlockType)arg2;	// IMP=0x00000001000be5b8
- (void)isUpdate:(id)arg1 readyForInstallation:(CDUnknownBlockType)arg2;	// IMP=0x00000001000be14c
- (void)isOSSoftwareUpdateRunning:(CDUnknownBlockType)arg1;	// IMP=0x00000001000be0c0
- (void)setAssetDownloadIsDiscretionary:(_Bool)arg1;	// IMP=0x00000001000be06c
- (void)currentDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdca8
- (void)isOSSoftwareUpdateDownloading:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdc1c
- (void)isOSSoftwareUpdateChecking:(CDUnknownBlockType)arg1;	// IMP=0x00000001000bdb90
- (void)startSoftwareUpdateMonitoring;	// IMP=0x00000001000bda64
- (id)init;	// IMP=0x00000001000bda08

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

