//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"
#import "PBScreenSaverManagerObserver.h"

@class CLLocationManager, GEOAlmanac, NSString;

@interface PBSystemAppearanceManager : NSObject <CLLocationManagerDelegate, PBScreenSaverManagerObserver>
{
    GEOAlmanac *_almanac;	// 8 = 0x8
    CLLocationManager *_locationManager;	// 16 = 0x10
    struct CLLocationCoordinate2D _locationForDaylight;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010007aa44
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) struct CLLocationCoordinate2D locationForDaylight; // @synthesize locationForDaylight=_locationForDaylight;
@property(retain, nonatomic) GEOAlmanac *almanac; // @synthesize almanac=_almanac;
- (void).cxx_destruct;	// IMP=0x000000010007cd88
- (id)_defaultTransitionContext;	// IMP=0x000000010007cc58
- (void)_updateUserInterfaceStyleForScenesWithUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010007c908
- (long long)_systemAppearanceForUserInterfaceStyle:(long long)arg1;	// IMP=0x000000010007c8f0
- (long long)_userInterfaceStyleForSystemAppearance:(long long)arg1;	// IMP=0x000000010007c8a4
- (void)_updateSystemAppPermissionsToMatchTimeZone;	// IMP=0x000000010007c694
- (void)_migrateSystemAppearanceSettings;	// IMP=0x000000010007c524
- (void)_updateLocationForDaylight:(id)arg1;	// IMP=0x000000010007c3e0
- (void)_handleWillWakeNotification:(id)arg1;	// IMP=0x000000010007c308
- (void)_videoPlayerNowPlayingStateDidChange:(id)arg1;	// IMP=0x000000010007c144
- (void)screenSaverManagerDidDismissScreenSaver:(id)arg1;	// IMP=0x000000010007c140
- (void)screenSaverManagerWillDismissScreenSaver:(id)arg1;	// IMP=0x000000010007c0ac
- (void)screenSaverManagerDidPresentScreenSaver:(id)arg1;	// IMP=0x000000010007c0a8
- (void)screenSaverManagerWillPresentScreenSaver:(id)arg1;	// IMP=0x000000010007c0a4
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x000000010007bfa4
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;	// IMP=0x000000010007bec8
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;	// IMP=0x000000010007babc
- (long long)effectiveUserInterfaceStyleForBundleIdentifier:(id)arg1;	// IMP=0x000000010007b6bc
- (long long)effectiveUserInterfaceStyle;	// IMP=0x000000010007b680
- (long long)reportingValueForCurrentSystemAppearance;	// IMP=0x000000010007b65c
- (void)toggleSystemAppearance;	// IMP=0x000000010007b600
@property(readonly, nonatomic, getter=isLocationAvailable) _Bool locationAvailable;
@property(readonly, nonatomic) _Bool isDaylight;
- (void)updateAutomaticSystemAppearanceIfNeeded;	// IMP=0x000000010007b2a4
- (void)setSystemAppearance:(long long)arg1;	// IMP=0x000000010007b0a0
- (long long)systemAppearance;	// IMP=0x000000010007b04c
- (void)setup;	// IMP=0x000000010007ae34
- (void)dealloc;	// IMP=0x000000010007ada0
- (id)init;	// IMP=0x000000010007ab00

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

