//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "PBTapGestureRecognizerDelegate.h"

@class FBDisplayLayoutElement, NSString, PBTapGestureRecognizer, UILongPressGestureRecognizer, UITapGestureRecognizer, _UIRepeatingPressGestureRecognizer;

@interface PBWindow : UIWindow <PBTapGestureRecognizerDelegate>
{
    UILongPressGestureRecognizer *_microphoneLongPressRecognizer;	// 8 = 0x8
    UITapGestureRecognizer *_microphoneTapRecognizer;	// 16 = 0x10
    PBTapGestureRecognizer *_microphoneTapDownRecognizer;	// 24 = 0x18
    UILongPressGestureRecognizer *_tvLongPressRecognizer;	// 32 = 0x20
    PBTapGestureRecognizer *_tvTapRecognizer;	// 40 = 0x28
    PBTapGestureRecognizer *_tvDoubleTapRecognizer;	// 48 = 0x30
    UILongPressGestureRecognizer *_rapidVolumeUpRecognizer;	// 56 = 0x38
    UILongPressGestureRecognizer *_rapidVolumeDownRecognizer;	// 64 = 0x40
    UILongPressGestureRecognizer *_longPressMenuRecognizer;	// 72 = 0x48
    UITapGestureRecognizer *_tapMenuRecognizer;	// 80 = 0x50
    UITapGestureRecognizer *_tapACHomeRecognizer;	// 88 = 0x58
    UITapGestureRecognizer *_tripleTapMenuRecognizer;	// 96 = 0x60
    UITapGestureRecognizer *_quadrupleTapMenuRecognizer;	// 104 = 0x68
    UITapGestureRecognizer *_tapExposeAllRecognizer;	// 112 = 0x70
    UILongPressGestureRecognizer *_playPauseLongPressRecognizer;	// 120 = 0x78
    UILongPressGestureRecognizer *_rewindLongPressRecognizer;	// 128 = 0x80
    UILongPressGestureRecognizer *_fastForwardLongPressRecognizer;	// 136 = 0x88
    UITapGestureRecognizer *_playPauseTapRecognizer;	// 144 = 0x90
    PBTapGestureRecognizer *_playTapRecognizer;	// 152 = 0x98
    PBTapGestureRecognizer *_pauseTapRecognizer;	// 160 = 0xa0
    PBTapGestureRecognizer *_stopTapRecognizer;	// 168 = 0xa8
    UITapGestureRecognizer *_rewindTapRecognizer;	// 176 = 0xb0
    UITapGestureRecognizer *_fastForwardTapRecognizer;	// 184 = 0xb8
    PBTapGestureRecognizer *_nextTrackTapRecognizer;	// 192 = 0xc0
    PBTapGestureRecognizer *_previousTrackTapRecognizer;	// 200 = 0xc8
    _UIRepeatingPressGestureRecognizer *_skipForwardsRepeatingPressRecognizer;	// 208 = 0xd0
    _UIRepeatingPressGestureRecognizer *_skipBackwardsRepeatingPressRecognizer;	// 216 = 0xd8
    UITapGestureRecognizer *_directionalRecognizer;	// 224 = 0xe0
    _Bool _shouldOcclude;	// 232 = 0xe8
    _Bool _occluding;	// 233 = 0xe9
    NSString *_name;	// 240 = 0xf0
    FBDisplayLayoutElement *_displayLayoutElement;	// 248 = 0xf8
}

+ (void)_decrementOcclusionCounter;	// IMP=0x00000001000656f8
+ (void)_incrementOcclusionCounter;	// IMP=0x00000001000652c4
@property(retain, nonatomic) FBDisplayLayoutElement *displayLayoutElement; // @synthesize displayLayoutElement=_displayLayoutElement;
@property(nonatomic, getter=isOccluding) _Bool occluding; // @synthesize occluding=_occluding;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool shouldOcclude; // @synthesize shouldOcclude=_shouldOcclude;
- (void).cxx_destruct;	// IMP=0x0000000100068068
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeOnPressDown:(id)arg2;	// IMP=0x0000000100067ed4
- (_Bool)gestureRecognizer:(id)arg1 shouldReceivePress:(id)arg2;	// IMP=0x0000000100067c58
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x0000000100067bb8
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;	// IMP=0x0000000100067a34
- (id)_newTripleTapGestureRecognizerWithPressTypes:(id)arg1;	// IMP=0x0000000100067978
- (void)setDirectionalGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x0000000100067770
- (void)setPlaybackGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x0000000100066a80
- (void)setTripleTapMenuGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x0000000100066924
- (void)setMenuGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x00000001000663a4
- (void)setMicrophoneGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x0000000100065f98
- (void)setExposeAllGestureRecognizerEnabled:(_Bool)arg1;	// IMP=0x0000000100065e14
- (void)setTVGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x0000000100065980
- (void)setVolumeGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x00000001000657e4
- (void)_updateLayoutElements;	// IMP=0x0000000100065120
- (void)_updateOccludingState;	// IMP=0x00000001000650a4
- (void)setHidden:(_Bool)arg1;	// IMP=0x0000000100064e18
- (void)setWindowLevel:(double)arg1;	// IMP=0x0000000100064ce4
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x0000000100064b08
- (id)initWithFrame:(struct CGRect)arg1 name:(id)arg2;	// IMP=0x0000000100064998
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100064968
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100064948

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

