//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVCKStoreAppDelegate.h"

#import "UIApplicationDelegate.h"
#import "_TVInterfaceCreatingPrivate.h"

@class NSString, UINavigationController, UITapGestureRecognizer, UIWindow;

__attribute__((visibility("hidden")))
@interface TVWatchListAppDelegate : TVCKStoreAppDelegate <_TVInterfaceCreatingPrivate, UIApplicationDelegate>
{
    UITapGestureRecognizer *_tvButtonRecognizer;	// 8 = 0x8
    UINavigationController *_navigationController;	// 16 = 0x10
}

+ (void)exposeObjectsInJSContext:(id)arg1;	// IMP=0x0000000100003c48
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;	// IMP=0x00000001000056a0
- (void)_navigateToUpNextOrSuspend:(_Bool)arg1;	// IMP=0x0000000100004968
- (void)_backgroundUpdateRequestedNotification:(id)arg1;	// IMP=0x00000001000047d0
- (void)_cloudClientStatusChanged:(id)arg1;	// IMP=0x00000001000046f4
- (void)_tvButtonAction:(id)arg1;	// IMP=0x00000001000046e4
- (_Bool)supportsIdleModeVisualEffects;	// IMP=0x00000001000046dc
- (id)bootURL;	// IMP=0x0000000100004630
- (id)_styleSheetURLForTemplate:(id)arg1;	// IMP=0x0000000100004338
- (id)_imageProxyForElement:(id)arg1;	// IMP=0x00000001000041b0
- (Class)collectionViewCellClassForElement:(id)arg1;	// IMP=0x00000001000040a8
- (id)viewForElement:(id)arg1 existingView:(id)arg2;	// IMP=0x0000000100003e98
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0000000100003bb4
- (void)_tabDidSelect:(id)arg1;	// IMP=0x0000000100003838
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x0000000100003670
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x00000001000035f0
- (void)dealloc;	// IMP=0x0000000100003578
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00000001000030e4
- (_Bool)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;	// IMP=0x000000010000302c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

