//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SATVHeaderView;

@interface _SATVRegionOtherCountriesContainerView : UIView
{
    SATVHeaderView *_otherCountriesHeader;	// 8 = 0x8
}

@property(readonly, nonatomic) SATVHeaderView *otherCountriesHeader; // @synthesize otherCountriesHeader=_otherCountriesHeader;
- (void).cxx_destruct;	// IMP=0x0000000100031380
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100031300
- (void)layoutSubviews;	// IMP=0x0000000100031218
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100030d5c

@end

