//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CALayer, NSDictionary, NSString;

@interface MicaAnimator : NSObject
{
    NSString *_path;	// 8 = 0x8
    CALayer *_rootLayer;	// 16 = 0x10
    NSDictionary *_publishedObjects;	// 24 = 0x18
    double _secondsToLoad;	// 32 = 0x20
    double _requestedLoad;	// 40 = 0x28
    double _documentDuration;	// 48 = 0x30
}

+ (id)rootDictForPath:(id)arg1;	// IMP=0x000000010007a4f8
+ (id)bestURLForUserInterfaceFileName:(id)arg1;	// IMP=0x000000010007a230
@property(nonatomic) double documentDuration; // @synthesize documentDuration=_documentDuration;
@property(nonatomic) double requestedLoad; // @synthesize requestedLoad=_requestedLoad;
@property(nonatomic) double secondsToLoad; // @synthesize secondsToLoad=_secondsToLoad;
@property(retain, nonatomic) NSDictionary *publishedObjects; // @synthesize publishedObjects=_publishedObjects;
@property(retain, nonatomic) CALayer *rootLayer; // @synthesize rootLayer=_rootLayer;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;	// IMP=0x000000010007a9d4
- (void)setHidden:(_Bool)arg1;	// IMP=0x000000010007a8f0
- (id)publishedObjectWithKey:(id)arg1 required:(_Bool)arg2;	// IMP=0x000000010007a8d8
- (id)publishedLayerWithKey:(id)arg1;	// IMP=0x000000010007a864
- (void)removeFromSuperlayer;	// IMP=0x000000010007a48c
- (void)addToLayer:(id)arg1 onTop:(_Bool)arg2;	// IMP=0x000000010007a3f0
@property(readonly, nonatomic) __weak NSString *name;
- (id)initWithPath:(id)arg1 rootLayer:(id)arg2 publishedObjects:(id)arg3;	// IMP=0x0000000100079e38
- (id)initWithPath:(id)arg1;	// IMP=0x0000000100079ad8
- (id)initWithFileName:(id)arg1 forUserInterface:(_Bool)arg2;	// IMP=0x000000010007984c

@end

