//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVAbstractFlow.h"

#import "SATVActivatorDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSTimer, SATVActivator, SATVNavigationController, SATVVideoSubscriberAccountViewController, TVSStateMachine;

@interface SATVOutOfBoxFlow : SATVAbstractFlow <SATVActivatorDelegate>
{
    _Bool _touchlessSetup;	// 8 = 0x8
    SATVNavigationController *_navigationController;	// 16 = 0x10
    TVSStateMachine *_stateMachine;	// 24 = 0x18
    NSMutableArray *_stateBreadcrumbs;	// 32 = 0x20
    NSMutableArray *_skippedControllers;	// 40 = 0x28
    NSMutableDictionary *_stateBreadcrumbsToControllers;	// 48 = 0x30
    CDUnknownBlockType _completionBlock;	// 56 = 0x38
    SATVActivator *_activator;	// 64 = 0x40
    NSTimer *_touchlessTimer;	// 72 = 0x48
    NSTimer *_TFDEPPollTimer;	// 80 = 0x50
    SATVVideoSubscriberAccountViewController *_videoSubscriberAccountViewController;	// 88 = 0x58
}

+ (void)initialize;	// IMP=0x00000001000533e4
@property(retain, nonatomic) SATVVideoSubscriberAccountViewController *videoSubscriberAccountViewController; // @synthesize videoSubscriberAccountViewController=_videoSubscriberAccountViewController;
@property(retain, nonatomic) NSTimer *TFDEPPollTimer; // @synthesize TFDEPPollTimer=_TFDEPPollTimer;
@property(retain, nonatomic) NSTimer *touchlessTimer; // @synthesize touchlessTimer=_touchlessTimer;
@property(nonatomic, getter=isTouchlessSetup) _Bool touchlessSetup; // @synthesize touchlessSetup=_touchlessSetup;
@property(retain, nonatomic) SATVActivator *activator; // @synthesize activator=_activator;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSMutableDictionary *stateBreadcrumbsToControllers; // @synthesize stateBreadcrumbsToControllers=_stateBreadcrumbsToControllers;
@property(retain, nonatomic) NSMutableArray *skippedControllers; // @synthesize skippedControllers=_skippedControllers;
@property(retain, nonatomic) NSMutableArray *stateBreadcrumbs; // @synthesize stateBreadcrumbs=_stateBreadcrumbs;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) SATVNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;	// IMP=0x000000010005d878
- (void)_autoAdvanceNow;	// IMP=0x000000010005d6e0
- (void)_removeDEPSkippedStates;	// IMP=0x000000010005d4ec
- (_Bool)_isResumingTouchlessSetup;	// IMP=0x000000010005d434
- (void)_stopTouchlessSetup;	// IMP=0x000000010005d3e8
- (void)_beginTouchlessSetupWithInvocation:(id)arg1 afterDelay:(double)arg2;	// IMP=0x000000010005d1e8
- (void)activator:(id)arg1 didSucceedWithType:(unsigned long long)arg2;	// IMP=0x000000010005cfb8
- (void)activator:(id)arg1 didFailWithError:(id)arg2 reason:(unsigned long long)arg3;	// IMP=0x000000010005cf40
- (void)_attemptSilentActivation;	// IMP=0x000000010005ce1c
- (id)_displayAssistantController;	// IMP=0x000000010005ccc8
- (id)_termsAndConditionsController;	// IMP=0x000000010005ca9c
- (id)_appAnalyticsController;	// IMP=0x000000010005c888
- (id)_diagnosticsController;	// IMP=0x000000010005c674
- (id)_flyoverController;	// IMP=0x000000010005c460
- (id)_timeZoneController;	// IMP=0x000000010005c24c
- (id)_locationServicesController;	// IMP=0x000000010005bf78
- (id)_airplay2RoomPickerViewController;	// IMP=0x000000010005bd4c
- (id)_homeScreenSyncController;	// IMP=0x000000010005bb38
- (id)_videoSubscriberAccountAppController;	// IMP=0x000000010005b90c
- (id)_videoSubscriberAccountController;	// IMP=0x000000010005b644
- (id)_siriStoreFrontController;	// IMP=0x000000010005b430
- (id)_homeScreenSyncQueryController;	// IMP=0x000000010005b21c
- (id)_loginController;	// IMP=0x000000010005aff0
- (id)_loadingCloudConfigController;	// IMP=0x000000010005ad00
- (id)_cloudConfigController;	// IMP=0x000000010005aaec
- (id)_activationController;	// IMP=0x000000010005a4fc
- (id)_networkValidationController;	// IMP=0x000000010005a390
- (id)_tapToSetupController;	// IMP=0x000000010005a164
- (id)_chooseSetupMethodController;	// IMP=0x0000000100059eac
- (id)_siriAndDictationController;	// IMP=0x0000000100059c98
- (id)_privacyController;	// IMP=0x0000000100059a84
- (id)_displayRegionModeController;	// IMP=0x0000000100059930
- (id)_selectRegionController;	// IMP=0x000000010005971c
- (id)_selectLanguageController;	// IMP=0x00000001000595c8
- (id)_pairRemoteController;	// IMP=0x000000010005933c
- (void)_popToControllerForCurrentState;	// IMP=0x0000000100059134
- (id)_existingControllerForCurrentState;	// IMP=0x00000001000590a8
- (void)_pushControllerForCurrentState:(id)arg1 skipIfConfigured:(_Bool)arg2;	// IMP=0x0000000100058ca0
- (id)_previousState;	// IMP=0x0000000100058c20
- (unsigned long long)_currentStateIndex;	// IMP=0x0000000100058b9c
- (id)_currentState;	// IMP=0x0000000100058b48
- (void)_registerHandlersForStateMachine:(id)arg1;	// IMP=0x0000000100053c90
- (void)finish;	// IMP=0x0000000100053c70
- (void)startWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100053c24
- (void)TFDEPPollTimerFired:(id)arg1;	// IMP=0x0000000100053ad4
- (_Bool)isTeslaEnrolled;	// IMP=0x0000000100053a24
- (void)stopTFDEPPolling;	// IMP=0x0000000100053974
- (void)startTFDEPPolling;	// IMP=0x000000010005389c
- (id)initWithNavigationController:(id)arg1 overrideEntryFlowState:(id)arg2;	// IMP=0x000000010005344c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

