//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SATVHeaderView;

@interface SATVLanguageHeaderView : UIView
{
    SATVHeaderView *_visibleHeaderView;	// 8 = 0x8
    SATVHeaderView *_hiddenHeaderView;	// 16 = 0x10
}

@property(retain, nonatomic) SATVHeaderView *hiddenHeaderView; // @synthesize hiddenHeaderView=_hiddenHeaderView;
@property(retain, nonatomic) SATVHeaderView *visibleHeaderView; // @synthesize visibleHeaderView=_visibleHeaderView;
- (void).cxx_destruct;	// IMP=0x000000010004e210
- (void)setTitle:(id)arg1 subtitle:(id)arg2 languageCode:(id)arg3 animated:(_Bool)arg4;	// IMP=0x000000010004d6e0
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010004d674
- (void)layoutSubviews;	// IMP=0x000000010004d57c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010004d420

@end

