//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDataDelegate.h"
#import "NSURLSessionDelegate.h"
#import "RemoteUIControllerDelegate.h"

@class NSMutableArray, NSString, NSTimer, RUIPage, RemoteUIController, SATVActivationEngine, TVSStateMachine, UINavigationController;

@interface SATVActivator : NSObject <NSURLSessionDelegate, NSURLSessionDataDelegate, RemoteUIControllerDelegate>
{
    SATVActivationEngine *_engine;	// 8 = 0x8
    RemoteUIController *_remoteUIController;	// 16 = 0x10
    NSMutableArray *_objectModels;	// 24 = 0x18
    RUIPage *_loadingPage;	// 32 = 0x20
    NSTimer *_ticketAcceptedTimer;	// 40 = 0x28
    id <SATVActivatorDelegate> _delegate;	// 48 = 0x30
    UINavigationController *_navigationController;	// 56 = 0x38
    TVSStateMachine *_stateMachine;	// 64 = 0x40
}

+ (_Bool)_hasDeKOTAFlagInActivationRecord;	// IMP=0x0000000100040c3c
+ (unsigned long long)_successTypeForActivationState:(id)arg1;	// IMP=0x000000010003b5a8
+ (_Bool)isBricked;	// IMP=0x000000010003b560
+ (_Bool)isDeviceFactoryActivated;	// IMP=0x000000010003b504
+ (_Bool)isDeviceActivated;	// IMP=0x000000010003b4a8
+ (id)_activationState;	// IMP=0x000000010003b3c0
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) __weak id <SATVActivatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100040f5c
- (void)remoteUIController:(id)arg1 didFinishLoadWithError:(id)arg2;	// IMP=0x00000001000409ec
- (void)remoteUIController:(id)arg1 didRemoveObjectModel:(id)arg2;	// IMP=0x0000000100040864
- (void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(_Bool)arg3;	// IMP=0x0000000100040724
- (void)remoteUIController:(id)arg1 didReceiveObjectModel:(id)arg2 actionSignal:(unsigned long long *)arg3;	// IMP=0x00000001000403d4
- (_Bool)remoteUIController:(id)arg1 shouldLoadRequest:(id)arg2 redirectResponse:(id)arg3;	// IMP=0x000000010003ffc4
- (void)_dismissRemoteUI;	// IMP=0x000000010003fe6c
- (void)_loadCloudConfig;	// IMP=0x000000010003fbd4
- (void)_checkActivationFailIfBricked:(_Bool)arg1;	// IMP=0x000000010003f9cc
- (void)_activationStateChanged;	// IMP=0x000000010003f844
- (void)_ticketAcceptedDidTimeout;	// IMP=0x000000010003f6fc
- (void)_clearTicketAcceptedTimer;	// IMP=0x000000010003f610
- (void)_activationDidFailWithReason:(unsigned long long)arg1 error:(id)arg2;	// IMP=0x000000010003f348
- (void)_activationSucceeded;	// IMP=0x000000010003efc4
- (void)_cleanup;	// IMP=0x000000010003eee4
- (void)_handleActivationFailureWithError:(id)arg1 reason:(unsigned long long)arg2;	// IMP=0x000000010003eb44
- (void)_handleActivationResponse:(id)arg1;	// IMP=0x000000010003e664
- (void)_activateDeviceWithResponse:(id)arg1;	// IMP=0x000000010003e0f4
- (void)_startRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010003dbf4
- (void)_tryActivateWithOptions:(id)arg1 requestMutator:(CDUnknownBlockType)arg2;	// IMP=0x000000010003d634
- (void)_startActivation;	// IMP=0x000000010003d1d4
- (void)_setTimeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010003cd6c
- (void)_configureStateMachine;	// IMP=0x000000010003b910
- (void)start;	// IMP=0x000000010003b828
- (void)dealloc;	// IMP=0x000000010003b7b0
- (id)init;	// IMP=0x000000010003b648

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

