//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep.h"
#import "SATVConsentViewControllerDataSource.h"
#import "SATVConsentViewControllerDelegate.h"

@class NSString;

@interface SATVCloudConfigViewController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
}

+ (_Bool)isSupported;	// IMP=0x000000010000b700
+ (id)stableKey;	// IMP=0x000000010000b6d4
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x000000010000d854
- (void)_obliterate;	// IMP=0x000000010000d76c
- (void)_leaveRemoteManagementAndErase;	// IMP=0x000000010000d24c
- (void)_showEraseDeviceAlert;	// IMP=0x000000010000cfa8
- (void)showLeaveRemoteManagementAlert;	// IMP=0x000000010000cd04
- (void)_presentEraseAlertWithTitle:(id)arg1 message:(id)arg2 eraseHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010000ca88
- (void)_applyConfiguration:(_Bool)arg1;	// IMP=0x000000010000c9c4
- (id)_aboutText;	// IMP=0x000000010000c3c8
- (_Bool)consentViewControllerCanSelectDissent:(id)arg1;	// IMP=0x000000010000c374
- (void)consentViewControllerDidSelectAuxiliary:(id)arg1;	// IMP=0x000000010000c368
- (void)consentViewControllerDidSelectFooter:(id)arg1;	// IMP=0x000000010000c23c
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x000000010000c1a4
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x000000010000c10c
- (id)auxiliaryButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010000c030
- (id)footnoteTextForConsentViewController:(id)arg1;	// IMP=0x000000010000bedc
- (id)footerButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010000be54
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010000bd28
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010000bbd8
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x000000010000b9f0
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x000000010000b968
- (void)autoAdvance;	// IMP=0x000000010000b958
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010000b924
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000b890
- (void)viewDidLoad;	// IMP=0x000000010000b79c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isConfigured;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

