//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CAAnimationDelegate.h"

@class CAAnimation, CALayer, NSArray, NSString;

@interface SATVIntroAnimator : NSObject <CAAnimationDelegate>
{
    _Bool _clickRunning;	// 8 = 0x8
    _Bool _shadowRunning;	// 9 = 0x9
    _Bool _enabled;	// 10 = 0xa
    _Bool _paused;	// 11 = 0xb
    double _cycleDuration;	// 16 = 0x10
    CAAnimation *_shadowAnimation;	// 24 = 0x18
    CAAnimation *_clickAnimation;	// 32 = 0x20
    CALayer *_clickLayer;	// 40 = 0x28
    CALayer *_shadowLayer;	// 48 = 0x30
    NSArray *_cyclingViews;	// 56 = 0x38
}

@property(nonatomic) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool shadowRunning; // @synthesize shadowRunning=_shadowRunning;
@property(nonatomic) _Bool clickRunning; // @synthesize clickRunning=_clickRunning;
@property(retain, nonatomic) NSArray *cyclingViews; // @synthesize cyclingViews=_cyclingViews;
@property(retain, nonatomic) CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
@property(retain, nonatomic) CALayer *clickLayer; // @synthesize clickLayer=_clickLayer;
@property(retain, nonatomic) CAAnimation *clickAnimation; // @synthesize clickAnimation=_clickAnimation;
@property(retain, nonatomic) CAAnimation *shadowAnimation; // @synthesize shadowAnimation=_shadowAnimation;
@property(nonatomic) double cycleDuration; // @synthesize cycleDuration=_cycleDuration;
- (void).cxx_destruct;	// IMP=0x0000000100052418
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;	// IMP=0x000000010005217c
- (void)_removeAnimations;	// IMP=0x00000001000520c8
- (void)_addAnimations;	// IMP=0x0000000100051db0
- (id)layerForKey:(id)arg1;	// IMP=0x0000000100051d04
- (id)animationForKey:(id)arg1;	// IMP=0x0000000100051c58
- (void)stopAnimation;	// IMP=0x0000000100051c48
- (void)startAnimation;	// IMP=0x0000000100051c10
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100051bb8
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0000000100051b60
- (void)dealloc;	// IMP=0x0000000100051a84
- (id)initWithAnimations:(id)arg1 layers:(id)arg2 cyclingViews:(id)arg3;	// IMP=0x0000000100051764

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

