//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep.h"
#import "SATVConsentViewControllerDataSource.h"
#import "SATVConsentViewControllerDelegate.h"

@class NSMutableDictionary, NSString, SATVTermsDetailsController, UIFocusGuide, UIView;

@interface SATVTermsController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
    NSMutableDictionary *_termsDictionary;	// 16 = 0x10
    SATVTermsDetailsController *_termsDetailsPreviewController;	// 24 = 0x18
    UIFocusGuide *_choiceFocusGuide;	// 32 = 0x20
    UIView *_choiceView;	// 40 = 0x28
}

+ (id)stableKey;	// IMP=0x000000010006d320
@property(retain, nonatomic) UIView *choiceView; // @synthesize choiceView=_choiceView;
@property(retain, nonatomic) UIFocusGuide *choiceFocusGuide; // @synthesize choiceFocusGuide=_choiceFocusGuide;
@property(retain, nonatomic) SATVTermsDetailsController *termsDetailsPreviewController; // @synthesize termsDetailsPreviewController=_termsDetailsPreviewController;
@property(retain, nonatomic) NSMutableDictionary *termsDictionary; // @synthesize termsDictionary=_termsDictionary;
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x000000010006fac8
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x000000010006f944
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x000000010006f86c
- (id)footnoteTextForConsentViewController:(id)arg1;	// IMP=0x000000010006f7e4
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010006f75c
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x000000010006f6d4
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x000000010006f64c
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x000000010006f5c4
- (void)_freezeTerms:(id)arg1 withName:(id)arg2;	// IMP=0x000000010006efac
- (void)_getFallbackTermsAndFreeze;	// IMP=0x000000010006ebb8
- (void)_decodeTermsData:(id)arg1;	// IMP=0x000000010006e93c
- (id)_termsRequest;	// IMP=0x000000010006e5f0
- (void)_downloadTerms;	// IMP=0x000000010006e18c
- (void)downloadCompleted;	// IMP=0x000000010006dbfc
- (void)viewDidLayoutSubviews;	// IMP=0x000000010006d8fc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010006d86c
- (void)viewDidLoad;	// IMP=0x000000010006d44c
- (void)autoAdvance;	// IMP=0x000000010006d3cc
- (id)init;	// IMP=0x000000010006d34c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isConfigured;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

