//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SATVCyclingView.h"
#import "SATVPulsingAnimationDelegate.h"

@class NSArray, NSObject<OS_dispatch_source>, NSString, SATVFooterView, SATVPulsingFooterView;

@interface SATVCyclingFooterView : UIView <SATVPulsingAnimationDelegate, SATVCyclingView>
{
    NSObject<OS_dispatch_source> *_autoAdvanceTimer;	// 8 = 0x8
    double _autoAdvanceInterval;	// 16 = 0x10
    _Bool _manualMode;	// 24 = 0x18
    NSArray *_contentStrings;	// 32 = 0x20
    NSArray *_languageCodes;	// 40 = 0x28
    SATVPulsingFooterView *_firstPulsingFooterView;	// 48 = 0x30
    SATVPulsingFooterView *_secondPulsingFooterView;	// 56 = 0x38
    SATVFooterView *_manualFooterView;	// 64 = 0x40
    unsigned long long _currentStringIndex;	// 72 = 0x48
}

@property(nonatomic) _Bool manualMode; // @synthesize manualMode=_manualMode;
@property(nonatomic) unsigned long long currentStringIndex; // @synthesize currentStringIndex=_currentStringIndex;
@property(retain, nonatomic) SATVFooterView *manualFooterView; // @synthesize manualFooterView=_manualFooterView;
@property(retain, nonatomic) SATVPulsingFooterView *secondPulsingFooterView; // @synthesize secondPulsingFooterView=_secondPulsingFooterView;
@property(retain, nonatomic) SATVPulsingFooterView *firstPulsingFooterView; // @synthesize firstPulsingFooterView=_firstPulsingFooterView;
@property(retain, nonatomic) NSArray *languageCodes; // @synthesize languageCodes=_languageCodes;
@property(retain, nonatomic) NSArray *contentStrings; // @synthesize contentStrings=_contentStrings;
- (void).cxx_destruct;	// IMP=0x0000000100053354
- (void)didFinishAnimationPulsingAnimation:(id)arg1;	// IMP=0x00000001000530a4
- (void)setManualAttributedString:(id)arg1;	// IMP=0x0000000100052f74
- (unsigned long long)_nextUniqueStringIndex;	// IMP=0x0000000100052e10
- (_Bool)_supportsCycling;	// IMP=0x0000000100052dc0
- (void)_stopAutoAdvanceTimer;	// IMP=0x0000000100052d7c
- (void)_startAutoAdvanceTimer;	// IMP=0x0000000100052be8
- (void)_cycleAtBeginTime:(double)arg1;	// IMP=0x0000000100052a50
- (void)cycleAtBeginTime:(double)arg1;	// IMP=0x0000000100052a0c
- (void)cycleWithInterval:(double)arg1;	// IMP=0x00000001000529f4
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010005298c
- (void)layoutSubviews;	// IMP=0x00000001000528e4
- (void)dealloc;	// IMP=0x0000000100052890
- (id)initWithStrings:(id)arg1 languageCodes:(id)arg2;	// IMP=0x0000000100052494

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

