//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep.h"
#import "SATVConsentViewControllerDataSource.h"
#import "SATVConsentViewControllerDelegate.h"

@class NSString, OBPrivacyLinkController;

@interface SATVAppAnalyticsController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
    OBPrivacyLinkController *_privacyLink;	// 16 = 0x10
}

+ (_Bool)isSupported;	// IMP=0x000000010000892c
+ (id)stableKey;	// IMP=0x0000000100008900
@property(retain, nonatomic) OBPrivacyLinkController *privacyLink; // @synthesize privacyLink=_privacyLink;
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x00000001000091a4
- (void)_enableAppAnalytics:(_Bool)arg1;	// IMP=0x0000000100009058
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x0000000100008fc0
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x0000000100008f28
- (id)footerButtonViewForConsentViewController:(id)arg1;	// IMP=0x0000000100008f10
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x0000000100008e88
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x0000000100008e00
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100008d78
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100008cf0
- (void)reset;	// IMP=0x0000000100008c58
@property(readonly, nonatomic) _Bool isConfigured;
- (void)autoAdvance;	// IMP=0x0000000100008bec
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100008b58
- (void)viewDidLoad;	// IMP=0x0000000100008a64
- (id)init;	// IMP=0x00000001000089e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

