//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIFocusContainerGuide;

@interface SATVFocusRedirectView : UIView
{
    _Bool _containsInertia;	// 8 = 0x8
    UIFocusContainerGuide *_containerGuide;	// 16 = 0x10
}

@property(readonly, nonatomic) UIFocusContainerGuide *containerGuide; // @synthesize containerGuide=_containerGuide;
@property(nonatomic) _Bool containsInertia; // @synthesize containsInertia=_containsInertia;
- (void).cxx_destruct;	// IMP=0x0000000100009348
- (_Bool)_containsInertiaSelectionChanges;	// IMP=0x0000000100009308
- (void)layoutSubviews;	// IMP=0x000000010000929c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000091e4

@end

