//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVStepViewController.h"

#import "SATVConsentStep.h"
#import "SATVConsentViewControllerDataSource.h"
#import "SATVConsentViewControllerDelegate.h"

@class NSString, OBPrivacyLinkController;

@interface SATVSiriController : SATVStepViewController <SATVConsentViewControllerDelegate, SATVConsentViewControllerDataSource, SATVConsentStep>
{
    CDUnknownBlockType consentHandler;	// 8 = 0x8
    OBPrivacyLinkController *_privacyLink;	// 16 = 0x10
}

+ (_Bool)isSupported;	// IMP=0x0000000100046164
+ (id)stableKey;	// IMP=0x0000000100045ea4
@property(retain, nonatomic) OBPrivacyLinkController *privacyLink; // @synthesize privacyLink=_privacyLink;
@property(copy, nonatomic) CDUnknownBlockType consentHandler; // @synthesize consentHandler;
- (void).cxx_destruct;	// IMP=0x0000000100046d28
- (void)_storeFrontDidChange:(id)arg1;	// IMP=0x0000000100046c18
- (void)_enableAssistantOnStoreFrontChange;	// IMP=0x0000000100046b24
- (void)_setDictationEnabled:(_Bool)arg1;	// IMP=0x0000000100046ad4
- (void)_setAssistantEnabled:(_Bool)arg1;	// IMP=0x0000000100046a00
- (void)_enableSiriAndDictation:(_Bool)arg1;	// IMP=0x0000000100046780
- (void)consentViewControllerDidSelectDissent:(id)arg1;	// IMP=0x00000001000466e8
- (void)consentViewControllerDidSelectConsent:(id)arg1;	// IMP=0x0000000100046650
- (id)footerButtonViewForConsentViewController:(id)arg1;	// IMP=0x0000000100046638
- (id)footnoteTextForConsentViewController:(id)arg1;	// IMP=0x00000001000465b0
- (id)dissentButtonTextForConsentViewController:(id)arg1;	// IMP=0x0000000100046528
- (id)consentButtonTextForConsentViewController:(id)arg1;	// IMP=0x00000001000464a0
- (id)subtitleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100046418
- (id)titleTextForConsentViewController:(id)arg1;	// IMP=0x0000000100046390
- (void)reset;	// IMP=0x0000000100046274
@property(readonly, nonatomic) _Bool isConfigured;
- (void)autoAdvance;	// IMP=0x0000000100046154
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000460c0
- (void)viewDidLoad;	// IMP=0x0000000100045fcc
- (void)dealloc;	// IMP=0x0000000100045f54
- (id)init;	// IMP=0x0000000100045ed0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) CDUnknownBlockType menuHandler;
@property(readonly) Class superclass;

@end

