/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 10:56:58 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Object : _UKNOWN_SUPERCLASS_ {

	Class isa;

}
+(id)class;
+(void)release;
+(id)initialize;
+(id)autorelease;
+(id)retain;
-(void)release;
-(id)autorelease;
-(id)retain;
@end

