//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SVSStarkConfirmationSnippetControllerDelegate.h"
#import "SVSStarkDisambiguationSnippetControllerDelegate.h"
#import "SVSStarkGatekeeperHeaderViewDelegate.h"
#import "SVSStarkItemControllerDelegate.h"
#import "SVSStarkViewDataSource.h"
#import "SVSStarkViewDelegate.h"
#import "SiriUIPresentation.h"

@class AFUIRequestOptions, AceObject, NSString, NSTimer, SVSStarkView, UIViewController<SVSStarkItemController>;

@interface SVSCarDisplayViewController : UIViewController <SVSStarkConfirmationSnippetControllerDelegate, SVSStarkDisambiguationSnippetControllerDelegate, SVSStarkItemControllerDelegate, SVSStarkViewDelegate, SVSStarkGatekeeperHeaderViewDelegate, SVSStarkViewDataSource, SiriUIPresentation>
{
    AceObject *_gatekeeperHeaderDataSource;	// 8 = 0x8
    _Bool _displayInitialPrompt;	// 16 = 0x10
    _Bool _screenSupportsTouchInteraction;	// 17 = 0x11
    id <SiriUIPresentationDataSource> _dataSource;	// 24 = 0x18
    id <SiriUIPresentationDelegate> _delegate;	// 32 = 0x20
    UIViewController<SVSStarkItemController> *_currentSnippetController;	// 40 = 0x28
    AFUIRequestOptions *_requestOptions;	// 48 = 0x30
    double _selectButtonTimeInterval;	// 56 = 0x38
    NSTimer *_selectButtonHoldToTalkTimer;	// 64 = 0x40
}

@property(retain, nonatomic, getter=_selectButtonHoldToTalkTimer, setter=_setSelectButtonHoldToTalkTimer:) NSTimer *selectButtonHoldToTalkTimer; // @synthesize selectButtonHoldToTalkTimer=_selectButtonHoldToTalkTimer;
@property(nonatomic, getter=_selectButtonTimeInterval, setter=_setSelectButtonTimeInterval:) double selectButtonTimeInterval; // @synthesize selectButtonTimeInterval=_selectButtonTimeInterval;
@property(nonatomic, getter=_screenSupportsTouchInteraction) _Bool screenSupportsTouchInteraction; // @synthesize screenSupportsTouchInteraction=_screenSupportsTouchInteraction;
@property(retain, nonatomic, getter=_requestOptions, setter=_setRequestOptions:) AFUIRequestOptions *requestOptions; // @synthesize requestOptions=_requestOptions;
@property(retain, nonatomic, getter=_currentSnippetController, setter=_setCurrentSnippetController:) UIViewController<SVSStarkItemController> *currentSnippetController; // @synthesize currentSnippetController=_currentSnippetController;
@property(nonatomic) __weak id <SiriUIPresentationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SiriUIPresentationDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x0000000100039dd0
- (void)siriSessionDidUpdateSessionInfo:(id)arg1;	// IMP=0x0000000100039cb4
- (void)siriSessionDidInitializeSessionInfo:(id)arg1;	// IMP=0x0000000100039c74
- (long long)userAccountCountForStarkView:(id)arg1;	// IMP=0x0000000100039bd8
- (id)activeAccountForStarkView:(id)arg1;	// IMP=0x0000000100039b54
- (id)assistantVersionForStarkView:(id)arg1;	// IMP=0x0000000100039ad0
- (void)mapsGatekeeperKeyboardButtonActivatedFromView:(id)arg1 interactionModel:(unsigned long long)arg2;	// IMP=0x000000010003998c
- (void)gatekeeperHeaderDismissalButtonPressed:(id)arg1;	// IMP=0x0000000100039980
- (id)backgroundColorForCellsInDisambiguationSnippetController:(id)arg1;	// IMP=0x00000001000398f4
- (void)disambiguationSnippetController:(id)arg1 performAceCommands:(id)arg2;	// IMP=0x0000000100039760
- (_Bool)isShowingGatekeeperHeader;	// IMP=0x0000000100039704
- (void)confirmationSnippetControllerRequestsDismissal:(id)arg1;	// IMP=0x00000001000396e0
- (void)confirmationSnippetController:(id)arg1 performAceCommands:(id)arg2;	// IMP=0x000000010003955c
- (void)_sendWillSendStartRequestIfNecessary:(id)arg1;	// IMP=0x00000001000393ec
- (_Bool)_containStartRequest:(id)arg1;	// IMP=0x000000010003922c
- (void)starkViewDidRemoveSnippetView:(id)arg1;	// IMP=0x0000000100039078
- (void)handleSelectButtonTap:(id)arg1;	// IMP=0x0000000100038ea8
- (void)siriDidFinishTest:(id)arg1;	// IMP=0x0000000100038df4
- (void)siriWillStartTest:(id)arg1;	// IMP=0x0000000100038d40
- (void)_selectButtonHoldToTalkIntervalFired:(id)arg1;	// IMP=0x0000000100038bfc
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003894c
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100038714
- (_Bool)_buttons:(id)arg1 hasType:(long long)arg2;	// IMP=0x00000001000385c8
- (_Bool)shouldResumeInterruptedAudioPlayback;	// IMP=0x00000001000385c0
- (void)displayUtteranceWithTitle:(id)arg1 subtitle:(id)arg2;	// IMP=0x0000000100038500
- (void)didReceiveDismissalAction:(CDUnknownBlockType)arg1;	// IMP=0x00000001000384ec
- (void)startNewConversation;	// IMP=0x00000001000384e0
- (_Bool)shouldBlockURLOpenOnTTS:(id)arg1;	// IMP=0x00000001000384bc
- (void)siriDidStopSpeakingWithIdentifier:(id)arg1 speechQueueIsEmpty:(_Bool)arg2;	// IMP=0x000000010003840c
- (_Bool)shouldDismissForIdling;	// IMP=0x00000001000383e0
- (double)idleTimerInterval;	// IMP=0x00000001000383d8
- (void)reloadItemsAtIndexPaths:(id)arg1;	// IMP=0x0000000100038354
- (void)insertItemsAtIndexPaths:(id)arg1;	// IMP=0x00000001000382d0
- (void)_updateItemsAtIndexPath:(id)arg1;	// IMP=0x0000000100037624
- (void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2;	// IMP=0x0000000100037608
- (id)preferredFocusEnvironments;	// IMP=0x000000010003756c
- (id)viewController;	// IMP=0x0000000100037568
- (long long)options;	// IMP=0x0000000100037560
- (void)userWantsStarkItemControllerFullScreen:(id)arg1;	// IMP=0x00000001000374e8
- (void)starkItemControllerRequestsDismissal:(id)arg1;	// IMP=0x00000001000373e4
- (void)starkItemController:(id)arg1 synthesizeSpeechWithText:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100037358
- (void)_setGatekeeperHeaderForAceObject:(id)arg1;	// IMP=0x0000000100037098
- (void)_setGatekeeperHeaderForRequestOptions:(id)arg1;	// IMP=0x0000000100036fac
- (void)_clearSnippetDisplay;	// IMP=0x0000000100036db4
- (void)_dismissStark;	// IMP=0x0000000100036cb0
- (_Bool)_screenSupportsKnobInteraction;	// IMP=0x0000000100036c24
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100036a80
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010003680c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100036794
- (void)loadView;	// IMP=0x0000000100036708
- (void)siriRequestWillStartWithRequestOptions:(id)arg1;	// IMP=0x00000001000366a0
- (void)_configureForRequestOptions:(id)arg1;	// IMP=0x00000001000364e0
- (void)configureForRequestOptions:(id)arg1;	// IMP=0x00000001000364d4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 delegate:(id)arg3 dataSource:(id)arg4;	// IMP=0x00000001000363dc
- (id)initWithDelegate:(id)arg1 dataSource:(id)arg2;	// IMP=0x0000000100036378
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100036314
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000362f8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SVSStarkView *view; // @dynamic view;

@end

