//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SiriUISnippetCollectionViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, SAGuidanceGuideDomainSnippet;

@interface SVSGuideDomainViewController : SiriUISnippetCollectionViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
}

- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x0000000100055714
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010005570c
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;	// IMP=0x0000000100055704
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000554f8
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100055484
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100055478
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000552ac
- (void)setSnippet:(id)arg1;	// IMP=0x0000000100055228
- (id)_phraseForIndexPath:(id)arg1;	// IMP=0x0000000100055148
- (_Bool)_showsCategoriesForSection:(unsigned long long)arg1;	// IMP=0x00000001000550f8
- (id)_titleForSection:(unsigned long long)arg1;	// IMP=0x0000000100055050
- (_Bool)usePlatterStyle;	// IMP=0x0000000100055048
- (_Bool)wantsToManageBackgroundColor;	// IMP=0x0000000100055040
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x0000000100054d94
- (id)_utterancesForSection:(unsigned long long)arg1;	// IMP=0x0000000100054cec
- (long long)_numberOfSections;	// IMP=0x0000000100054c78
- (struct UIEdgeInsets)_headerViewEdgeInsets;	// IMP=0x0000000100054c5c
- (long long)_cellTypeForIndexPath:(id)arg1;	// IMP=0x0000000100054b50
- (double)desiredHeightForHeaderView;	// IMP=0x0000000100054a44
- (void)configureReusableHeaderView:(id)arg1;	// IMP=0x0000000100054994
- (Class)headerViewClass;	// IMP=0x0000000100054980
- (void)loadView;	// IMP=0x00000001000547c0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010005472c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SAGuidanceGuideDomainSnippet *snippet; // @dynamic snippet;
@property(readonly) Class superclass;

@end

