//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class SiriUIKeyline;

@interface SVSKeylineNavigationBar : UINavigationBar
{
    SiriUIKeyline *_keyline;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010007f988
- (void)layoutSubviews;	// IMP=0x000000010007f888
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010007f7b0

@end

