//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SVSStarkGatekeeperHeaderView : UIView
{
    id <SVSStarkGatekeeperHeaderViewDelegate> _delegate;	// 8 = 0x8
    NSString *_appBundleIdentifier;	// 16 = 0x10
}

+ (id)_starkTitleLabel;	// IMP=0x000000010003ab78
+ (double)_headerViewSpacerDistance;	// IMP=0x000000010003a808
+ (id)gatekeeperForAceObject:(id)arg1;	// IMP=0x000000010003a650
+ (id)gatekeeperForRequestOptions:(id)arg1;	// IMP=0x000000010003a590
@property(retain, nonatomic, getter=_appBundleIdentifier, setter=_setAppBundleIdentifier:) NSString *appBundleIdentifier; // @synthesize appBundleIdentifier=_appBundleIdentifier;
@property(nonatomic) __weak id <SVSStarkGatekeeperHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010003af70
- (unsigned long long)_gatekeeperTypeForBundleIdentifier:(id)arg1;	// IMP=0x000000010003ae88
- (void)_logGatekeeperDismissedManually;	// IMP=0x000000010003ad04
- (void)logGatekeeperAppeared;	// IMP=0x000000010003ab80
- (void)_updateForAppBundleIdentifier;	// IMP=0x000000010003ab74
- (void)_dismissalButtonTapped:(id)arg1;	// IMP=0x000000010003aac8
- (void)dealloc;	// IMP=0x000000010003a9a4
- (id)initWithAceObject:(id)arg1;	// IMP=0x000000010003a998
- (id)initWithRequestOptions:(id)arg1;	// IMP=0x000000010003a90c
- (id)_init;	// IMP=0x000000010003a878

@end

