//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFQueue.h"

@interface SVSTranscriptAnimationQueue : AFQueue
{
}

- (id)nextNonPinningAnimationForTranscriptItem:(id)arg1;	// IMP=0x0000000100005130
- (id)dequeueAllAnimations;	// IMP=0x0000000100005124
- (id)dequeNextAnimation;	// IMP=0x0000000100005118
- (id)nextAnimation;	// IMP=0x000000010000510c
- (void)enqueueAnimations:(id)arg1;	// IMP=0x0000000100005100
- (void)enqueueAnimation:(id)arg1;	// IMP=0x00000001000050f4

@end

