/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 10:56:58 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source_data_replace <OS_dispatch_source>
@end

