/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 31, 2019 at 10:56:59 AM Mountain Standard Time
* Operating System: Version 12.1.1 (Build 16K45)
* Image Source: /usr/lib/system/libxpc.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>

@interface OS_xpc_event_publisher : OS_object
-(void)_xref_dispose;
-(void)_dispose;
-(id)init;
-(id)description;
@end

