//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPImageRepresentation.h"

@class UIImage;

@interface _TVUIImageRepresentation : TVPImageRepresentation
{
    UIImage *_image;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x000000010000f5ec
- (id)_originalImageCacheKey;	// IMP=0x000000010000f5a4
- (struct CGImage *)_originalImage;	// IMP=0x000000010000f57c
- (id)initWithImage:(id)arg1;	// IMP=0x000000010000f4fc

@end

