//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, TVPImageStack, TVUINamedLayerStack, UIColor, _UIStackedImageConfiguration, _UIStackedImageContainerLayer;

@interface TVPImageStackView : UIView
{
    _UIStackedImageContainerLayer *_imageStackLayer;	// 8 = 0x8
    _UIStackedImageConfiguration *_imageStackConfig;	// 16 = 0x10
    TVPImageStack *_imageStack;	// 24 = 0x18
    struct CGSize _imageStackSize;	// 32 = 0x20
    TVUINamedLayerStack *_uiLayerStack;	// 48 = 0x30
    double _layerSelectionDuration;	// 56 = 0x38
    double _layerUnselectionDuration;	// 64 = 0x40
    double _shadowSelectionDuration;	// 72 = 0x48
    double _shadowUnselectionDuration;	// 80 = 0x50
    double _repositionUnselectionDuration;	// 88 = 0x58
    _Bool _imageLoaded;	// 96 = 0x60
    UIView *_overlayView;	// 104 = 0x68
    UIView *_unmaskedOverlayView;	// 112 = 0x70
}

+ (struct CGSize)_scaledSizeForSize:(struct CGSize)arg1 focusSizeIncrease:(double)arg2 selectionStyle:(long long)arg3;	// IMP=0x000000010008af00
+ (struct CGSize)_scaledSizeForSize:(struct CGSize)arg1 selectionStyle:(long long)arg2;	// IMP=0x000000010008ae6c
+ (id)imageStackViewWithSize:(struct CGSize)arg1;	// IMP=0x00000001000889f0
+ (id)imageStackViewWithImageStack:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x0000000100088968
@property(nonatomic, getter=isImageLoaded) _Bool imageLoaded; // @synthesize imageLoaded=_imageLoaded;
@property(retain, nonatomic) UIView *unmaskedOverlayView; // @synthesize unmaskedOverlayView=_unmaskedOverlayView;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;	// IMP=0x000000010008af6c
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x000000010008af14
- (void)_updateStackedImageConfiguration;	// IMP=0x000000010008ac68
- (double)_unpressedDuration;	// IMP=0x000000010008ac50
- (void)_setUnpressedDuration:(double)arg1;	// IMP=0x000000010008ac38
- (void)_setSelectionStyle:(long long)arg1;	// IMP=0x000000010008ac20
- (void)_setPressedScaleAdjustment:(double)arg1;	// IMP=0x000000010008ac08
- (void)_setPressedDuration:(double)arg1;	// IMP=0x000000010008abf0
- (void)_setImageStackContentsGravity:(id)arg1;	// IMP=0x000000010008abd8
- (void)_setIdleModeFocusSizeOffset:(double)arg1;	// IMP=0x000000010008abc0
- (void)_setFocusDirection:(struct CGPoint)arg1 duration:(double)arg2;	// IMP=0x000000010008aba8
- (long long)_selectionStyle;	// IMP=0x000000010008ab90
- (id)_layeredImageContainerLayer;	// IMP=0x000000010008ab80
- (id)_shadowLayer;	// IMP=0x000000010008ab68
- (double)_pressedScaleAdjustment;	// IMP=0x000000010008ab50
- (double)_pressedDuration;	// IMP=0x000000010008ab38
- (void)_resetShadowSettings;	// IMP=0x000000010008a9b8
- (void)_setShadowVerticalOffset:(double)arg1;	// IMP=0x000000010008a954
- (void)_setShadowRadius:(double)arg1;	// IMP=0x000000010008a8f0
- (void)_setShadowOpacity:(double)arg1;	// IMP=0x000000010008a88c
- (id)_newImageConfiguration;	// IMP=0x000000010008a848
- (id)_flatLayer;	// IMP=0x000000010008a830
- (id)_layerBelowTitles;	// IMP=0x000000010008a818
- (id)_imageStackContentsGravity;	// IMP=0x000000010008a800
- (id)_imageConfiguration;	// IMP=0x000000010008a7e8
- (double)_idleModeFocusSizeOffset;	// IMP=0x000000010008a7d0
@property(nonatomic) double focusSizeIncrease;
@property(readonly, nonatomic) unsigned long long primaryControlState;
- (void)setControlState:(unsigned long long)arg1 animated:(_Bool)arg2 focusAnimationCoordinator:(id)arg3;	// IMP=0x000000010008a748
- (void)setControlState:(unsigned long long)arg1 animated:(_Bool)arg2;	// IMP=0x000000010008a730
@property(nonatomic) unsigned long long controlState;
- (void)setFocusDirection:(struct CGPoint)arg1 animated:(_Bool)arg2;	// IMP=0x000000010008a590
@property(nonatomic) struct CGPoint focusDirection;
- (void)setPressed:(_Bool)arg1 duration:(double)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010008a378
- (void)setPressed:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010008a360
- (void)setPressed:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010008a348
@property(nonatomic, getter=isPressed) _Bool pressed;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2 focusAnimationCoordinator:(id)arg3;	// IMP=0x000000010008a284
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010008a1f0
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010008a190
@property(nonatomic, getter=isSelected) _Bool selected;
@property(nonatomic) double layerUnselectionDuration;
@property(nonatomic) double layerSelectionDuration;
@property(nonatomic, getter=isHueShiftEnabled) _Bool hueShiftEnabled;
@property(nonatomic, getter=isBrightnessBoostEnabled) _Bool brightnessBoostEnabled;
@property(nonatomic) double radiosityAmount;
@property(nonatomic) double specularHighlightVerticalPositionSensitivity;
@property(nonatomic) double specularHighlightVerticalPosition;
@property(nonatomic) double specularHighlightHorizontalPositionSensitivity;
@property(retain, nonatomic) UIColor *specularHighlightColor;
@property(nonatomic) double rotationAmount;
@property(nonatomic) double cornerRadius;
@property(nonatomic) double perspectiveZDepth;
@property(copy, nonatomic) NSArray *parallaxImageDepths;
@property(nonatomic) double maxParallaxImageDepth;
- (void)_loadImage;	// IMP=0x00000001000891c0
@property(retain, nonatomic) TVPImageStack *imageStack;
- (void)setImageStack:(id)arg1 withSize:(struct CGSize)arg2;	// IMP=0x0000000100088f90
- (void)willMoveToWindow:(id)arg1;	// IMP=0x0000000100088efc
- (void)layoutSubviews;	// IMP=0x0000000100088e90
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100088e28
- (void)dealloc;	// IMP=0x0000000100088d94
- (id)initWithSize:(struct CGSize)arg1;	// IMP=0x0000000100088ca8
- (id)initWithImageStack:(id)arg1 size:(struct CGSize)arg2;	// IMP=0x0000000100088a88
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100088a3c

@end

