//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPAccessObject.h"

#import "MSDeleterPlugin.h"
#import "MSSubscriberPlugin.h"
#import "TVCKPushNotificationListener.h"

@class NSArray, NSString, TVAssetLibrary, TVPMyPSImageLoadTask;

@interface TVPMyPSAccessObject : TVPAccessObject <MSSubscriberPlugin, MSDeleterPlugin, TVCKPushNotificationListener>
{
    struct sqlite3 *_db;	// 8 = 0x8
    NSArray *_assets;	// 16 = 0x10
    id <TVPMyPSAccessObjectDelegate> _delegate;	// 24 = 0x18
    TVAssetLibrary *_imageManager;	// 32 = 0x20
    id <MSSubscriber> _subscriber;	// 40 = 0x28
    TVPMyPSImageLoadTask *_imageLoadTask;	// 48 = 0x30
}

+ (id)deleterPluginForPersonID:(id)arg1;	// IMP=0x0000000100076cc0
+ (id)personIDsForPollingTriggeredByPushNotification;	// IMP=0x000000010007662c
+ (id)subscriberPluginForPersonID:(id)arg1;	// IMP=0x0000000100076574
+ (id)dbCachePathForPersonID:(id)arg1;	// IMP=0x00000001000763b8
+ (id)accessObjectWithAppleAccount:(id)arg1;	// IMP=0x0000000100075eac
@property(retain, nonatomic) TVPMyPSImageLoadTask *imageLoadTask; // @synthesize imageLoadTask=_imageLoadTask;
@property(nonatomic) __weak id <MSSubscriber> subscriber; // @synthesize subscriber=_subscriber;
@property(retain, nonatomic) TVAssetLibrary *imageManager; // @synthesize imageManager=_imageManager;
@property(nonatomic) __weak id <TVPMyPSAccessObjectDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;	// IMP=0x0000000100079470
- (void)_removeAssets:(id)arg1;	// IMP=0x00000001000790bc
- (void)_addNewAssetsFromServerAssets:(id)arg1;	// IMP=0x0000000100078c94
- (id)_assetForAssetID:(id)arg1;	// IMP=0x0000000100078ae0
- (void)_didFinishDeletingAssetCollection:(id)arg1 error:(id)arg2;	// IMP=0x00000001000788b8
- (void)_didReceiveDeleteForAssetCollections:(id)arg1;	// IMP=0x0000000100078680
- (void)_didCompleteCheckForNewAssetCollections;	// IMP=0x0000000100078584
- (void)_didFinishRetrievingAsset:(id)arg1 imageData:(id)arg2 error:(id)arg3;	// IMP=0x0000000100077e60
- (void)_didRequestAssetRetrievalForAssetCollections:(id)arg1;	// IMP=0x000000010007740c
- (void)_loadImageForImageTokens:(id)arg1;	// IMP=0x0000000100077320
- (id)_imageTokenForAssetID:(id)arg1;	// IMP=0x0000000100077314
- (id)_imageForAssetID:(id)arg1 canLoad:(_Bool *)arg2;	// IMP=0x0000000100077244
- (void)_tearDown;	// IMP=0x0000000100077110
- (void)_runSetup;	// IMP=0x0000000100076fdc
- (void)pushNotificationServerTokenDidChange:(id)arg1;	// IMP=0x0000000100076fd8
- (void)pushNotificationServer:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000100076ec0
- (void)deleter:(id)arg1 didFinishDeletingAssetCollection:(id)arg2 error:(id)arg3;	// IMP=0x0000000100076d78
- (void)subscriberDidCompleteCheckForNewAssetCollections:(id)arg1;	// IMP=0x0000000100076c48
- (void)subscriber:(id)arg1 didReceiveDeleteForAssetCollections:(id)arg2 streamID:(id)arg3;	// IMP=0x0000000100076b50
- (void)subscriber:(id)arg1 didFailToRetriveSubscriptionUpdateWithError:(id)arg2;	// IMP=0x0000000100076b4c
- (void)subscriber:(id)arg1 didFinishRetrievingAsset:(id)arg2 error:(id)arg3;	// IMP=0x0000000100076950
- (void)subscriber:(id)arg1 didFinishRequestingAssetRetrievalForStreamID:(id)arg2;	// IMP=0x000000010007694c
- (void)subscriber:(id)arg1 didRequestAssetRetrievalForAssetCollections:(id)arg2 streamID:(id)arg3;	// IMP=0x0000000100076854
- (void)subscriberWillAssignPluginAsDelegateOfSubscriber:(id)arg1;	// IMP=0x000000010007675c
- (void)removeAssetForAssetID:(id)arg1;	// IMP=0x000000010007604c
- (void)tearDown;	// IMP=0x0000000100075fdc
- (void)_insertDBAsset:(id)arg1;	// IMP=0x000000010007a218
- (id)_dateFormatter;	// IMP=0x000000010007a134
- (void)_removeDBAsset:(id)arg1;	// IMP=0x000000010007a058
- (void)_removeDBAssets:(id)arg1;	// IMP=0x0000000100079ecc
- (void)_insertDBAssets:(id)arg1;	// IMP=0x0000000100079d50
- (void)_updateDBAsset:(id)arg1 newState:(int)arg2;	// IMP=0x0000000100079c48
- (void)_removeDB;	// IMP=0x0000000100079b00
- (id)_loadAssetsFromDB;	// IMP=0x00000001000795f4
- (void)_createOrOpenDB;	// IMP=0x00000001000794e4
- (void)_writeImageFromImageData:(id)arg1 assetID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010007a6fc
- (void)_purgeImages;	// IMP=0x000000010007a6b0
- (void)_purgeImageForAssetID:(id)arg1;	// IMP=0x000000010007a644
- (id)_imageForAssetID:(id)arg1;	// IMP=0x000000010007a5b4
- (id)_imagePathForAssetID:(id)arg1;	// IMP=0x000000010007a524

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

