//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PXPhotoLibraryUIChangeObserver.h"
#import "TVPCollectionViewCachingManagerDataSource.h"
#import "TVPCollectionViewDelegate.h"
#import "TVPCollectionViewDelegateFlowLayout.h"
#import "TVPPhotoLibraryTabbedViewController.h"
#import "UICollectionViewDataSource.h"

@class NSArray, NSMutableDictionary, NSString, PHCollectionList, TVPCollectionView, TVPCollectionViewCachingManager, TVPFetchManager, UIView;

@interface TVPPhotoLibraryAlbumsListController : UIViewController <UICollectionViewDataSource, TVPCollectionViewDelegate, PXPhotoLibraryUIChangeObserver, TVPCollectionViewCachingManagerDataSource, TVPCollectionViewDelegateFlowLayout, TVPPhotoLibraryTabbedViewController>
{
    _Bool _needsReload;	// 8 = 0x8
    TVPCollectionView *_albumsListView;	// 16 = 0x10
    UIView *_loadingView;	// 24 = 0x18
    TVPFetchManager *_fetchManager;	// 32 = 0x20
    TVPCollectionViewCachingManager *_cachingManager;	// 40 = 0x28
    NSArray *_albumAssetCollections;	// 48 = 0x30
    PHCollectionList *_defaultCollectionList;	// 56 = 0x38
    NSMutableDictionary *__subCollectionKeyAssetsFetchResults;	// 64 = 0x40
    NSMutableDictionary *__folderCountFetchResults;	// 72 = 0x48
}

@property(nonatomic) _Bool needsReload; // @synthesize needsReload=_needsReload;
@property(readonly, nonatomic) NSMutableDictionary *_folderCountFetchResults; // @synthesize _folderCountFetchResults=__folderCountFetchResults;
@property(readonly, nonatomic) NSMutableDictionary *_subCollectionKeyAssetsFetchResults; // @synthesize _subCollectionKeyAssetsFetchResults=__subCollectionKeyAssetsFetchResults;
@property(retain, nonatomic) PHCollectionList *defaultCollectionList; // @synthesize defaultCollectionList=_defaultCollectionList;
@property(copy, nonatomic) NSArray *albumAssetCollections; // @synthesize albumAssetCollections=_albumAssetCollections;
@property(retain, nonatomic) TVPCollectionViewCachingManager *cachingManager; // @synthesize cachingManager=_cachingManager;
@property(retain, nonatomic) TVPFetchManager *fetchManager; // @synthesize fetchManager=_fetchManager;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) TVPCollectionView *albumsListView; // @synthesize albumsListView=_albumsListView;
- (void).cxx_destruct;	// IMP=0x0000000100075cdc
- (id)ppt_albumListCollectionView;	// IMP=0x0000000100075bc0
@property(readonly, nonatomic) long long tabMode;
- (id)_albumAtIndexPath:(id)arg1;	// IMP=0x0000000100075b00
- (id)_assetAtIndexPath:(id)arg1;	// IMP=0x0000000100075958
- (void)_dismissLoadingView;	// IMP=0x00000001000758c4
- (void)_displayLoadingView;	// IMP=0x00000001000757c8
- (long long)_assetCountForCollection:(id)arg1;	// IMP=0x0000000100075734
- (void)_fetchAlbumCollectionsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000750c0
- (id)_overlayImageForAlbum:(id)arg1;	// IMP=0x0000000100074fe4
- (id)collectionViewCachingManager:(id)arg1 assetsForIndexPaths:(id)arg2;	// IMP=0x0000000100074e20
- (struct CGSize)collectionView:(id)arg1 referenceSizeForTitleInLayout:(id)arg2;	// IMP=0x0000000100074e10
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100074df8
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100074a78
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000748dc
- (void)_loadFolderCell:(id)arg1 withFolder:(id)arg2;	// IMP=0x00000001000740bc
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100073a7c
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100073a64
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x0000000100073a20
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x00000001000739dc
- (void)photoLibraryDidChangeOnMainQueue:(id)arg1;	// IMP=0x0000000100072b24
- (unsigned long long)_indexOfFavouriteMemoryAlbumInArray:(id)arg1;	// IMP=0x00000001000729a8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000728e8
- (id)preferredFocusEnvironments;	// IMP=0x0000000100072858
- (void)dealloc;	// IMP=0x00000001000727e0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100072730
- (void)viewDidLoad;	// IMP=0x0000000100071fe8
- (id)init;	// IMP=0x0000000100071fd8
- (id)initWithCollectionList:(id)arg1;	// IMP=0x0000000100071e68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

