//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPPhotoLibraryCollectionViewController.h"

#import "PHPhotoLibraryChangeObserver.h"
#import "TVPCollectionViewCachingManagerDataSource.h"
#import "TVPCollectionViewDelegateFlowLayout.h"
#import "TVPPhotoLibraryOneUpViewControllerDelegate.h"
#import "TVPPhotoLibraryTabbedViewController.h"
#import "UICollectionViewDataSource_Private.h"

@class NSIndexPath, NSString, PHAssetCollection, TVPCollectionViewCachingManager, TVPFetchManager;

@interface TVPPhotoLibraryMomentsListController : TVPPhotoLibraryCollectionViewController <PHPhotoLibraryChangeObserver, TVPPhotoLibraryOneUpViewControllerDelegate, TVPCollectionViewCachingManagerDataSource, TVPCollectionViewDelegateFlowLayout, TVPPhotoLibraryTabbedViewController, UICollectionViewDataSource_Private>
{
    _Bool _shouldSkipInvalidation;	// 8 = 0x8
    _Bool _needsReload;	// 9 = 0x9
    id <TVPPhotoLibraryMomentsListControllerDelegate> _delegate;	// 16 = 0x10
    NSIndexPath *_preferredFocusIndexPath;	// 24 = 0x18
    TVPFetchManager *_fetchManager;	// 32 = 0x20
    TVPCollectionViewCachingManager *_cachingManager;	// 40 = 0x28
}

+ (id)yearDateFormatter;	// IMP=0x00000001000111c8
@property(nonatomic) _Bool needsReload; // @synthesize needsReload=_needsReload;
@property(nonatomic) _Bool shouldSkipInvalidation; // @synthesize shouldSkipInvalidation=_shouldSkipInvalidation;
@property(retain, nonatomic) TVPCollectionViewCachingManager *cachingManager; // @synthesize cachingManager=_cachingManager;
@property(retain, nonatomic) TVPFetchManager *fetchManager; // @synthesize fetchManager=_fetchManager;
@property(retain, nonatomic) NSIndexPath *preferredFocusIndexPath; // @synthesize preferredFocusIndexPath=_preferredFocusIndexPath;
@property(nonatomic) __weak id <TVPPhotoLibraryMomentsListControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000140ec
@property(readonly, nonatomic) long long tabMode;
- (id)_momentForSection:(unsigned long long)arg1;	// IMP=0x0000000100013f78
- (id)_assetsForSection:(unsigned long long)arg1;	// IMP=0x0000000100013f08
- (id)_assetsForMoment:(id)arg1;	// IMP=0x0000000100013cc8
- (id)_assetAtIndexPath:(id)arg1;	// IMP=0x0000000100013bf8
- (void)tappedHeader:(id)arg1;	// IMP=0x0000000100013ad4
- (void)_configureHeaderView:(id)arg1 inSection:(long long)arg2;	// IMP=0x0000000100013854
- (void)_fetchMomentsCollectionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010001359c
- (id)collectionViewCachingManager:(id)arg1 assetsForIndexPaths:(id)arg2;	// IMP=0x00000001000133d8
- (Class)_collectionViewCellClass;	// IMP=0x00000001000133c4
- (Class)_sectionHeaderViewClass;	// IMP=0x00000001000133b0
- (Class)_collectionViewTitleViewClass;	// IMP=0x000000010001339c
- (void)photoLibraryDidChange:(id)arg1;	// IMP=0x00000001000129c8
- (void)photoLibraryOneUpControllerWillPop:(id)arg1;	// IMP=0x0000000100012764
- (struct CGSize)collectionView:(id)arg1 referenceSizeForTitleInLayout:(id)arg2;	// IMP=0x0000000100012754
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x00000001000126d4
- (struct CGSize)_referenceSizeForHeaderInSection:(long long)arg1;	// IMP=0x0000000100012618
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x0000000100012608
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x000000010001255c
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x00000001000120b8
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100011de4
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100011c2c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001000118c4
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100011874
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100011868
- (id)_collectionView:(id)arg1 indexPathForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x0000000100011748
- (id)_sectionIndexTitlesForCollectionView:(id)arg1;	// IMP=0x00000001000113b8
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x0000000100011374
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x0000000100011330
- (long long)_sectionIndexMultiplier;	// IMP=0x0000000100011178
- (long long)_numberOfSections;	// IMP=0x0000000100011120
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100011048
- (void)setSelectedIndexPath:(id)arg1;	// IMP=0x0000000100010f84
@property(retain, nonatomic) PHAssetCollection *focusedMoment;
- (void)dealloc;	// IMP=0x0000000100010da8
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100010d20
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100010b78
- (void)viewDidLoad;	// IMP=0x00000001000106d4
- (id)init;	// IMP=0x0000000100010608

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

