//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

@interface UIResponder (TVAdditions)
- (_Bool)_containsInertiaSelectionChanges;	// IMP=0x0000000100026e24
@property(nonatomic) double selectionTrackerAnimationDuration;
- (_Bool)_shouldChangeToResponder:(id)arg1;	// IMP=0x0000000100026d60
- (void)_responderPotentialChangedBetweenFirstResponder:(id)arg1 andResponder:(id)arg2;	// IMP=0x0000000100026d5c
@property(nonatomic) double firstResponderPotential;
@property(nonatomic) double highlightProgress;
@end

