//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioSessionDelegate.h"
#import "IMAVVideoViewDelegate.h"

@class AVPlayer, AVPlayerItem, AVPlayerLayer, IMAVExternalVideoView, IMAVPlayerLayerView, IMAVVideoView, IMPlayerChapterInfo, IMPlayerItem, IMPlayerManifest, MPNowPlayingInfoCenter, MPRemoteCommandCenter, NSMutableArray, NSObject<OS_dispatch_source>, NSString, NSTimer, NSURL, UIWindow;

@interface IMAVPlayer : NSObject <IMAVVideoViewDelegate, AVAudioSessionDelegate>
{
    NSURL *_lastPlayingURL;	// 8 = 0x8
    id _periodicTimeObserver;	// 16 = 0x10
    id _nowPlayingInfoPeriodicTimeObserver;	// 24 = 0x18
    unsigned long long _backgroundTask;	// 32 = 0x20
    NSTimer *_hdcpTimer;	// 40 = 0x28
    NSTimer *_seekTimer;	// 48 = 0x30
    NSMutableArray *_timeObservers;	// 56 = 0x38
    NSMutableArray *_observingTimes;	// 64 = 0x40
    _Bool _timeObserverNeedsUpdate;	// 72 = 0x48
    _Bool _seekForward;	// 73 = 0x49
    struct {
        unsigned int delegateStateChanged:1;
        unsigned int delegateErrorDidOccur:1;
        unsigned int delegateMediaTypeAvailable:1;
        unsigned int delegateDurationAvailable:1;
        unsigned int delegateCallbackForTime:1;
        unsigned int delegatePeriodicUpdate:1;
        unsigned int delegateHasDidChangePlayerItem:1;
        unsigned int delegateHasDidStopPlayerItem:1;
        unsigned int delegateHasDidEndedPlayerItem:1;
        unsigned int delegateLoadedDurationChanged:1;
        unsigned int delegateChapterStarted:1;
        unsigned int delegateCurrentManifestItemChanged:1;
    } _delegateFlags;	// 76 = 0x4c
    NSObject<OS_dispatch_source> *_fadeOutTimer;	// 80 = 0x50
    _Bool _providesVideoView;	// 88 = 0x58
    _Bool _externalDisplay;	// 89 = 0x59
    _Bool _scrubbing;	// 90 = 0x5a
    _Bool _isUpdatingCurrentTime;	// 91 = 0x5b
    _Bool _wasInterrupted;	// 92 = 0x5c
    _Bool _wasInterruptedEarly;	// 93 = 0x5d
    _Bool _isPrerolling;	// 94 = 0x5e
    int _loops;	// 96 = 0x60
    float _scanRate;	// 100 = 0x64
    double _currentTime;	// 104 = 0x68
    id <IMAVPlayerDelegate> _delegate;	// 112 = 0x70
    MPNowPlayingInfoCenter *_infoCenter;	// 120 = 0x78
    MPRemoteCommandCenter *_commandCenter;	// 128 = 0x80
    unsigned long long _state;	// 136 = 0x88
    AVPlayer *_player;	// 144 = 0x90
    AVPlayerItem *_playerItem;	// 152 = 0x98
    IMPlayerManifest *_manifest;	// 160 = 0xa0
    IMPlayerItem *_currentItem;	// 168 = 0xa8
    unsigned long long _autoStop;	// 176 = 0xb0
    double _autoStopTimerTime;	// 184 = 0xb8
    double _autoStopMediaTime;	// 192 = 0xc0
    unsigned long long _videoScale;	// 200 = 0xc8
    unsigned long long _currentChapterIndex;	// 208 = 0xd0
    unsigned long long _chapterMetadataMode;	// 216 = 0xd8
    unsigned long long _playbackSpeed;	// 224 = 0xe0
    NSTimer *_autoStopTimer;	// 232 = 0xe8
    double _autoStopTimerPausedTime;	// 240 = 0xf0
    IMAVVideoView *_videoView;	// 248 = 0xf8
    AVPlayerLayer *_videoLayer;	// 256 = 0x100
    IMAVPlayerLayerView *_videoLayerView;	// 264 = 0x108
    IMAVExternalVideoView *_externalVideoView;	// 272 = 0x110
    UIWindow *_externalVideoWindow;	// 280 = 0x118
}

+ (void)mainThread:(CDUnknownBlockType)arg1;	// IMP=0x0000000100222734
+ (void)performAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100222684
+ (void)perform:(CDUnknownBlockType)arg1;	// IMP=0x000000010022260c
+ (_Bool)isMinSpeed:(unsigned long long)arg1;	// IMP=0x0000000100218d20
+ (_Bool)isMaxSpeed:(unsigned long long)arg1;	// IMP=0x0000000100218d14
+ (unsigned long long)decrementPlaybackSpeed:(unsigned long long)arg1;	// IMP=0x0000000100218cf4
+ (unsigned long long)incrementPlaybackSpeed:(unsigned long long)arg1;	// IMP=0x0000000100218cd4
+ (unsigned long long)playbackSpeedForRate:(float)arg1;	// IMP=0x0000000100218c78
+ (float)rateForPlaybackSpeed:(unsigned long long)arg1;	// IMP=0x0000000100218c54
+ (void)initializePlayerQueue;	// IMP=0x0000000100216078
+ (id)sharedPlayer;	// IMP=0x0000000100215fac
+ (void)setBackgroundAVPlayerQueueEnabled:(_Bool)arg1;	// IMP=0x0000000100215f20
@property(nonatomic) float scanRate; // @synthesize scanRate=_scanRate;
@property(retain, nonatomic) UIWindow *externalVideoWindow; // @synthesize externalVideoWindow=_externalVideoWindow;
@property(retain, nonatomic) IMAVExternalVideoView *externalVideoView; // @synthesize externalVideoView=_externalVideoView;
@property(retain, nonatomic) IMAVPlayerLayerView *videoLayerView; // @synthesize videoLayerView=_videoLayerView;
@property(retain, nonatomic) AVPlayerLayer *videoLayer; // @synthesize videoLayer=_videoLayer;
@property(retain, nonatomic) IMAVVideoView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) double autoStopTimerPausedTime; // @synthesize autoStopTimerPausedTime=_autoStopTimerPausedTime;
@property(retain, nonatomic) NSTimer *autoStopTimer; // @synthesize autoStopTimer=_autoStopTimer;
@property(nonatomic) _Bool isPrerolling; // @synthesize isPrerolling=_isPrerolling;
@property(nonatomic) _Bool wasInterruptedEarly; // @synthesize wasInterruptedEarly=_wasInterruptedEarly;
@property(nonatomic) _Bool wasInterrupted; // @synthesize wasInterrupted=_wasInterrupted;
@property(nonatomic) _Bool isUpdatingCurrentTime; // @synthesize isUpdatingCurrentTime=_isUpdatingCurrentTime;
@property(retain, nonatomic) id nowPlayingInfoPeriodicTimeObserver; // @synthesize nowPlayingInfoPeriodicTimeObserver=_nowPlayingInfoPeriodicTimeObserver;
@property(retain, nonatomic) id periodicTimeObserver; // @synthesize periodicTimeObserver=_periodicTimeObserver;
@property(nonatomic) unsigned long long playbackSpeed; // @synthesize playbackSpeed=_playbackSpeed;
@property(nonatomic) _Bool scrubbing; // @synthesize scrubbing=_scrubbing;
@property(nonatomic) int loops; // @synthesize loops=_loops;
@property(nonatomic) unsigned long long chapterMetadataMode; // @synthesize chapterMetadataMode=_chapterMetadataMode;
@property(nonatomic) unsigned long long currentChapterIndex; // @synthesize currentChapterIndex=_currentChapterIndex;
@property(readonly, nonatomic) _Bool externalDisplay; // @synthesize externalDisplay=_externalDisplay;
@property(nonatomic) unsigned long long videoScale; // @synthesize videoScale=_videoScale;
@property(nonatomic) _Bool providesVideoView; // @synthesize providesVideoView=_providesVideoView;
@property(nonatomic) double autoStopMediaTime; // @synthesize autoStopMediaTime=_autoStopMediaTime;
@property(nonatomic) double autoStopTimerTime; // @synthesize autoStopTimerTime=_autoStopTimerTime;
@property(nonatomic) unsigned long long autoStop; // @synthesize autoStop=_autoStop;
@property(retain, nonatomic) IMPlayerItem *currentItem; // @synthesize currentItem=_currentItem;
@property(retain, nonatomic) IMPlayerManifest *manifest; // @synthesize manifest=_manifest;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) MPRemoteCommandCenter *commandCenter; // @synthesize commandCenter=_commandCenter;
@property(retain, nonatomic) MPNowPlayingInfoCenter *infoCenter; // @synthesize infoCenter=_infoCenter;
@property(nonatomic) __weak id <IMAVPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
- (void).cxx_destruct;	// IMP=0x0000000100222ca8
- (void)_assertMainThread;	// IMP=0x000000010022287c
- (void)_assertPlayerThread;	// IMP=0x0000000100222794
- (void)mainThread:(CDUnknownBlockType)arg1;	// IMP=0x00000001002226dc
- (void)perform:(CDUnknownBlockType)arg1;	// IMP=0x00000001002225b4
- (void)clearAutoStop;	// IMP=0x00000001002224f4
- (void)enforceAutoStopForMode:(unsigned long long)arg1;	// IMP=0x0000000100222380
- (void)_autoStopTimerFired;	// IMP=0x00000001002222f0
- (void)_clearAutoStopTimmer;	// IMP=0x0000000100222210
- (void)_pauseAutoStopTimer;	// IMP=0x000000010022215c
- (void)_setupAutoStopTimer;	// IMP=0x0000000100221e38
@property(readonly, nonatomic) double autoStopTimeRemaining;
- (void)previousChapter;	// IMP=0x0000000100221ab4
- (void)nextChapter;	// IMP=0x0000000100221a14
- (void)onChaptersLoaded:(id)arg1;	// IMP=0x00000001002218e4
- (void)_setChapterIndex:(unsigned long long)arg1;	// IMP=0x0000000100221878
- (void)setupChapterAtTime:(double)arg1;	// IMP=0x0000000100221424
@property(readonly, nonatomic) IMPlayerChapterInfo *currentChapter;
- (void)setupChapterTimeObservers;	// IMP=0x000000010022104c
@property(readonly, nonatomic) unsigned long long chapterCount;
- (_Bool)hasChapters;	// IMP=0x0000000100220fb4
- (void)updateNowPlayingPlaybackState:(unsigned long long)arg1;	// IMP=0x0000000100220f5c
- (void)updateNowPlayingDurationSnapshot;	// IMP=0x0000000100220a2c
- (void)updateNowPlayingMetadataIncludingArtwork:(_Bool)arg1;	// IMP=0x0000000100220534
- (void)forceTriggerTimeObserverAt:(double)arg1;	// IMP=0x0000000100220074
- (void)triggerTimeObserverAt:(id)arg1;	// IMP=0x000000010021ff04
- (void)setupTimeObserver:(id)arg1;	// IMP=0x000000010021fc08
- (void)updateTimeObservers;	// IMP=0x000000010021fa88
- (void)sendPeriodicTimeEvent:(double)arg1 duration:(double)arg2 finished:(_Bool)arg3;	// IMP=0x000000010021f834
- (void)removePeriodicTimeObservers;	// IMP=0x000000010021f710
- (void)addPeriodicTimeObservers;	// IMP=0x000000010021f35c
- (void)clearTimeObservers;	// IMP=0x000000010021f20c
- (void)removeAllTimeObservers;	// IMP=0x000000010021f1c4
- (void)removeCMTimeObserver:(CDStruct_1b6d18a9)arg1;	// IMP=0x000000010021f148
- (void)addCMTimeObserver:(CDStruct_1b6d18a9)arg1;	// IMP=0x000000010021f06c
- (void)removeTimeObserver:(double)arg1;	// IMP=0x000000010021f024
- (void)addTimeObserver:(double)arg1;	// IMP=0x000000010021efd4
- (void)prerollBuffer;	// IMP=0x000000010021ef9c
@property(readonly, nonatomic) _Bool isScanning;
- (void)scanWithRate:(float)arg1;	// IMP=0x000000010021eeec
@property(readonly, nonatomic) double loadedDuration;
@property(readonly, nonatomic) double duration;
- (_Bool)isDurationReady;	// IMP=0x000000010021ec04
- (void)onSeekTimer:(id)arg1;	// IMP=0x000000010021eb88
@property(readonly, nonatomic) _Bool isSeeking;
- (void)endSeek;	// IMP=0x000000010021eb2c
- (void)cancelSeek;	// IMP=0x000000010021eaf0
- (void)startSeek:(_Bool)arg1;	// IMP=0x000000010021ea2c
- (void)_updatePlayerTimeCompleted:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010021e74c
- (void)_updatePlayerToCurrentTime:(CDUnknownBlockType)arg1;	// IMP=0x000000010021e360
- (void)setCurrentTime:(double)arg1 fromMediaRemote:(_Bool)arg2;	// IMP=0x000000010021e0d4
- (void)_setCurrentTime:(double)arg1;	// IMP=0x000000010021e0b4
- (void)_postNotificationName:(id)arg1 userInfo:(id)arg2;	// IMP=0x000000010021df30
- (void)_failedToPlayToEndNotification:(id)arg1;	// IMP=0x000000010021ddb8
- (void)sendItemEndedNotification;	// IMP=0x000000010021dca4
- (void)playerItemDidReachEnd:(id)arg1;	// IMP=0x000000010021db94
- (void)_tracksDidLoad;	// IMP=0x000000010021d8b8
- (void)_durationAvailable;	// IMP=0x000000010021d7b0
- (void)_updateLoadingSpinner;	// IMP=0x000000010021d668
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010021c13c
- (void)resetPlayer:(id)arg1;	// IMP=0x000000010021bf74
- (void)stopObservingPlayerItem:(id)arg1;	// IMP=0x000000010021bea0
- (void)_createPlayer;	// IMP=0x000000010021bac0
- (void)onRouteChange:(id)arg1;	// IMP=0x000000010021b8b4
- (void)handleAudioSessionInterruption:(id)arg1;	// IMP=0x000000010021b4d0
- (void)handlePlayerInterruption:(id)arg1;	// IMP=0x000000010021b3c8
- (void)videoViewReadyForDisplay:(id)arg1;	// IMP=0x000000010021b3b0
- (void)videoView:(id)arg1 willMoveToWindow:(id)arg2;	// IMP=0x000000010021b310
- (void)onScreenDisconnection:(id)arg1;	// IMP=0x000000010021b284
- (void)onClosedCaptioningChanged:(id)arg1;	// IMP=0x000000010021b20c
- (void)onScreenConnection:(id)arg1;	// IMP=0x000000010021b180
- (void)_updateClosedCaptionState;	// IMP=0x000000010021b138
- (void)updateVideoViewScale;	// IMP=0x000000010021af80
- (void)createExternalDisplayOnScreen:(id)arg1;	// IMP=0x000000010021ad34
- (void)destroyExternalDisplay;	// IMP=0x000000010021ac58
- (void)updateVideoView;	// IMP=0x000000010021a55c
- (void)updateVideoViewIfNeeded;	// IMP=0x000000010021a4ac
@property(readonly, nonatomic) _Bool airplayVideoActive;
- (id)stillFrameAt:(double)arg1 maxSize:(struct CGSize)arg2 scale:(double)arg3;	// IMP=0x000000010021a078
- (void)endBackgroundTask;	// IMP=0x0000000100219f28
- (void)beginBackgroundTask;	// IMP=0x0000000100219bbc
@property(readonly, nonatomic) _Bool isPlaybackActive;
@property(readonly, nonatomic) _Bool isPlaybackRequested;
- (_Bool)isAtEnd;	// IMP=0x0000000100219a54
- (_Bool)isStalled;	// IMP=0x0000000100219a30
@property(readonly, nonatomic) unsigned long long loadState;
- (void)cancelFadeOut;	// IMP=0x00000001002197a4
- (void)fadeOutWithDuration:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010021930c
- (void)fadeOutWithDuration:(double)arg1;	// IMP=0x00000001002192fc
- (void)fadeOut;	// IMP=0x00000001002192ec
- (void)sleep;	// IMP=0x0000000100219204
- (_Bool)togglePlayPause;	// IMP=0x00000001002190e0
- (void)_pauseAndContinuePrerollBuffering;	// IMP=0x0000000100219050
- (_Bool)pause;	// IMP=0x0000000100218fa8
- (_Bool)play;	// IMP=0x0000000100218d2c
@property(readonly, nonatomic) float actualRate;
@property(nonatomic) float requestedRate;
@property(nonatomic) _Bool shouldEnforceHDCP;
- (void)hdcpTimer:(id)arg1;	// IMP=0x00000001002185bc
- (void)setCurrentTimeRemote:(double)arg1;	// IMP=0x00000001002185ac
- (void)previousRemote:(_Bool)arg1;	// IMP=0x0000000100218228
- (void)previousRemote;	// IMP=0x0000000100218218
- (void)nextRemote;	// IMP=0x0000000100217fa4
- (void)_resumeLoading;	// IMP=0x0000000100217da4
- (_Bool)_canPauseLoading;	// IMP=0x0000000100217d00
- (void)_pauseLoading;	// IMP=0x0000000100217bd4
- (void)_updateLoadingState;	// IMP=0x0000000100217b0c
- (void)_updateForCurrentRateAndTimeControlStatus;	// IMP=0x0000000100217734
- (void)updateRateForCurrentState;	// IMP=0x000000010021720c
- (void)_updatePlayerForCurrentItem;	// IMP=0x0000000100216d18
- (void)manifestCurrentItemDidChange;	// IMP=0x0000000100216610
- (void)previousMediaItem;	// IMP=0x0000000100216318
- (void)nextMediaItem;	// IMP=0x00000001002161f0
- (void)becomeActiveMediaPlayer;	// IMP=0x0000000100216188
- (void)registerAVSessionCategoryAndMode;	// IMP=0x0000000100216100
- (void)dealloc;	// IMP=0x0000000100215d64
- (id)init;	// IMP=0x0000000100215764

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

