//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface IMDatabaseHandle : NSObject
{
    struct sqlite3 *_databaseHandle;	// 8 = 0x8
    NSMutableDictionary *_statementCache;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_accessQueue;	// 24 = 0x18
}

+ (id)questionMarkListForCollection:(id)arg1;	// IMP=0x00000001001d3b54
- (_Bool)_bindArguments:(id)arg1 inStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x00000001001d42e4
- (id)_stringRowsForQuery:(id)arg1;	// IMP=0x00000001001d3f10
- (void)_reportErrorInFunction:(const char *)arg1;	// IMP=0x00000001001d3e18
- (struct sqlite3 *)_databaseHandle;	// IMP=0x00000001001d3e08
- (id)_cursorForQuery:(id)arg1 withArguments:(id)arg2;	// IMP=0x00000001001d3ca8
- (_Bool)passesIntegrityCheck;	// IMP=0x00000001001d3c28
- (id)stringColumnDataForQuery:(id)arg1 withArguments:(id)arg2;	// IMP=0x00000001001d35ac
- (id)arrayForQuery:(id)arg1 arguments:(id)arg2 rawRows:(_Bool)arg3;	// IMP=0x00000001001d326c
- (id)arrayForQuery:(id)arg1 arguments:(id)arg2;	// IMP=0x00000001001d325c
- (_Bool)runStatement:(id)arg1 arguments:(id)arg2;	// IMP=0x00000001001d2fa4
- (_Bool)runSql:(id)arg1 withArguments:(id)arg2;	// IMP=0x00000001001d2f44
- (id)version;	// IMP=0x00000001001d2ef4
- (id)columnInfoForTable:(id)arg1;	// IMP=0x00000001001d2ea0
- (id)tableNames;	// IMP=0x00000001001d2e8c
- (void)dealloc;	// IMP=0x00000001001d2d14
- (id)initWithPath:(id)arg1;	// IMP=0x00000001001d2c48

@end

