//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@class IMKeyValueStoreTransaction;

@interface IMKeyValueStoreError : NSError
{
    IMKeyValueStoreTransaction *_transaction;	// 40 = 0x28
}

+ (id)serverClampErrorWithTransaction:(id)arg1 retrySeconds:(double)arg2 underlyingError:(id)arg3;	// IMP=0x000000010007bc74
+ (id)userClampErrorWithTransaction:(id)arg1 retrySeconds:(double)arg2 underlyingError:(id)arg3;	// IMP=0x000000010007bb80
+ (id)delegateCancelledErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007bb68
+ (id)transactionCancelledErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007bb50
+ (id)transactionTimeoutErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007bb38
+ (id)transactionCancelledErrorWithTransaction:(id)arg1 code:(long long)arg2 underlyingError:(id)arg3;	// IMP=0x000000010007b5c8
+ (id)transactionMissingURLErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b534
+ (id)transactionMissingDomainErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b4a0
+ (id)storeAccountSessionExpiredWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b40c
+ (id)noStoreAccountErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b378
+ (id)userEnteredWrongCredentialsErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b2e4
+ (id)userCancelledSignInErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b250
+ (id)storeValidationErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b1e0
+ (id)storeGenericErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007b170
+ (id)storeAccountMismatchErrorWithPreviousStoreAccountText:(id)arg1 currentStoreAccontText:(id)arg2 transaction:(id)arg3 underlyingError:(id)arg4;	// IMP=0x000000010007b080
+ (id)storeLoggedOutErrorWithPreviousStoreAccountText:(id)arg1 transaction:(id)arg2 underlyingError:(id)arg3;	// IMP=0x000000010007afac
+ (id)killSwitchErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007af18
+ (id)networkingBlockedErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007ae84
+ (id)keyValueStoreDisabledErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007adf0
+ (id)unknownErrorWithTransaction:(id)arg1 underlyingError:(id)arg2;	// IMP=0x000000010007ad4c
+ (id)keyValueStoreErrorWithCode:(long long)arg1 localizedDescription:(id)arg2 transaction:(id)arg3 underlyingError:(id)arg4;	// IMP=0x000000010007abf4
@property(retain, nonatomic) IMKeyValueStoreTransaction *transaction; // @synthesize transaction=_transaction;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010007ab88
- (double)retrySeconds;	// IMP=0x000000010007ab50
- (id)currentStoreAccountKey;	// IMP=0x000000010007ab24
- (id)previousStoreAccountKey;	// IMP=0x000000010007aaf8
- (_Bool)isTransactionMissingInformationError;	// IMP=0x000000010007aad0
- (_Bool)isTransactionCancelledError;	// IMP=0x000000010007aaa8
- (_Bool)isClampError;	// IMP=0x000000010007aa80
- (_Bool)isRecoverableError;	// IMP=0x000000010007aa20
- (_Bool)isAccountsChangedError;	// IMP=0x000000010007a9ec
- (_Bool)isAuthenticationError;	// IMP=0x000000010007a9c4
- (id)description;	// IMP=0x000000010007a94c
- (void)dealloc;	// IMP=0x000000010007a8f0

@end

