//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IMPreferences : NSObject
{
}

+ (id)storeBookkeeperPreferences;	// IMP=0x0000000100093384
- (_Bool)boolForKey:(id)arg1;	// IMP=0x00000001000936a4
- (void)setBool:(_Bool)arg1 forKey:(id)arg2;	// IMP=0x0000000100093658
- (id)objectForKey:(id)arg1 withDefaultValue:(id)arg2;	// IMP=0x0000000100093610
- (void)setObject:(id)arg1 forKey:(id)arg2;	// IMP=0x00000001000935dc
- (void)registerDefaultsIfKeyNotSet:(id)arg1 registrationBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100093554
- (void)_preferencesDidChange;	// IMP=0x000000010009350c
- (void)dealloc;	// IMP=0x00000001000934b4
- (id)init;	// IMP=0x00000001000933fc

@end

