//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IMProcessAssertion, NSString;

@interface IMTaskAssertion : NSObject
{
    CDUnknownBlockType _expireHandler;	// 8 = 0x8
    NSString *_debugInfo;	// 16 = 0x10
    IMProcessAssertion *_processAssertion;	// 24 = 0x18
}

+ (id)newBackgroundTaskWithExpirationHandler:(CDUnknownBlockType)arg1 debugInfo:(id)arg2;	// IMP=0x0000000100094530
- (void).cxx_destruct;	// IMP=0x00000001000947e8
- (id)description;	// IMP=0x0000000100094720
- (void)invalidate;	// IMP=0x00000001000946bc
- (void)performExpirationHandler;	// IMP=0x0000000100094600
- (void)dealloc;	// IMP=0x00000001000945b4
- (id)initWithExpirationHandler:(CDUnknownBlockType)arg1 debugInfo:(id)arg2;	// IMP=0x0000000100094398

@end

