//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MPAssistantUtilitiesWrapper : NSObject
{
}

+ (id)copyOutputDevicesMatchingUIDs:(id)arg1 features:(unsigned int)arg2;	// IMP=0x000000010017f78c
+ (void)sendCommandToDestination:(unsigned int)arg1 options:(id)arg2 destination:(id)arg3 callback:(CDUnknownBlockType)arg4;	// IMP=0x000000010017f728
+ (void)sendPlaybackQueueToDestination:(struct _MRSystemAppPlaybackQueue *)arg1 destination:(id)arg2 context:(id)arg3 callback:(CDUnknownBlockType)arg4;	// IMP=0x000000010017f6c4
+ (id)createLocalOriginSystemPodcastsApplicationRemoteControlDestination;	// IMP=0x000000010017f654
+ (id)createRemoteControlDestination:(id)arg1;	// IMP=0x000000010017f640

@end

