//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@interface MTAlertController : UIAlertController
{
    _Bool _replacesExistingAlert;	// 8 = 0x8
}

@property(nonatomic) _Bool replacesExistingAlert; // @synthesize replacesExistingAlert=_replacesExistingAlert;
- (id)alertIdentifier;	// IMP=0x00000001001c4120
- (void)presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001001c3e78
- (id)init;	// IMP=0x00000001001c3e08

@end

