//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSString;

@interface MTArtworkView : UIImageView
{
    _Bool _observingArtworkChangeNotifications;	// 8 = 0x8
    _Bool _enabled;	// 9 = 0x9
    NSString *_artworkKey;	// 16 = 0x10
}

@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;	// IMP=0x00000001000b97d0
- (void)_reloadArtwork;	// IMP=0x00000001000b9488
- (void)_stopObservingArtworkChangeNotifications;	// IMP=0x00000001000b9418
- (void)_startObservingArtworkChangeNotifications;	// IMP=0x00000001000b939c
- (void)_artworkDidChange:(id)arg1;	// IMP=0x00000001000b9310
- (void)_artworkKeyDidChange;	// IMP=0x00000001000b929c
- (void)_artworkSizeDidChange;	// IMP=0x00000001000b9290
- (void)setBounds:(struct CGRect)arg1;	// IMP=0x00000001000b91d8
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x00000001000b9120
@property(readonly, nonatomic, getter=isPlaceholder) _Bool placeholder;
@property(retain, nonatomic) NSString *artworkKey; // @synthesize artworkKey=_artworkKey;
- (void)dealloc;	// IMP=0x00000001000b8f80
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000b8dcc

@end

