//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"

@class NSArray, NSString;

@interface MTAssistantRemoteControlDestination : NSObject <NSMutableCopying>
{
    NSString *_appBundleID;	// 8 = 0x8
    NSString *_playerID;	// 16 = 0x10
    void *_origin;	// 24 = 0x18
    NSArray *_outputDeviceUIDs;	// 32 = 0x20
    void *_outputGroup;	// 40 = 0x28
}

+ (id)watchRadioApplicationDestination;	// IMP=0x00000001000e13c0
+ (id)systemPodcastsApplicationDestination;	// IMP=0x00000001000e1374
+ (id)systemMediaApplicationDestination;	// IMP=0x00000001000e1328
@property(readonly, nonatomic) void *outputGroup; // @synthesize outputGroup=_outputGroup;
@property(readonly, nonatomic) NSArray *outputDeviceUIDs; // @synthesize outputDeviceUIDs=_outputDeviceUIDs;
@property(readonly, nonatomic) void *origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) NSString *playerID; // @synthesize playerID=_playerID;
@property(readonly, nonatomic) NSString *appBundleID; // @synthesize appBundleID=_appBundleID;
- (void).cxx_destruct;	// IMP=0x00000001000e1874
- (id)_copyWithZone:(struct _NSZone *)arg1 usingConcreteClass:(Class)arg2;	// IMP=0x00000001000e1750
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000e1708
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000e16c8
- (void *)createPlayerPath;	// IMP=0x00000001000e1644
- (id)description;	// IMP=0x00000001000e1578
- (void)dealloc;	// IMP=0x00000001000e1524
- (id)init;	// IMP=0x00000001000e150c
- (id)initWithAppBundleID:(id)arg1;	// IMP=0x00000001000e14f8
- (id)initWithAppBundleID:(id)arg1 playerID:(id)arg2 origin:(void *)arg3;	// IMP=0x00000001000e13fc

@end

