//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface MTBadgeView : UIView
{
    _Bool _dark;	// 8 = 0x8
    UILabel *_badgeLabel;	// 16 = 0x10
}

@property(retain, nonatomic) UILabel *badgeLabel; // @synthesize badgeLabel=_badgeLabel;
@property(nonatomic, getter=isDark) _Bool dark; // @synthesize dark=_dark;
- (void).cxx_destruct;	// IMP=0x00000001000ecb5c
- (void)setBackgroundColor:(id)arg1;	// IMP=0x00000001000ecaa8
- (void)setBadgeValue:(id)arg1;	// IMP=0x00000001000eca04
- (void)layoutSubviews;	// IMP=0x00000001000ec710
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000ec698
- (id)init;	// IMP=0x00000001000ec604

@end

