//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSFetchedResultsController, NSMutableDictionary, NSString;

@interface MTBaseQueryObserver : NSObject <NSFetchedResultsControllerDelegate>
{
    NSFetchedResultsController *_frc;	// 8 = 0x8
    _Bool _isObserving;	// 16 = 0x10
    NSString *_identifier;	// 24 = 0x18
    NSMutableDictionary *_handlers;	// 32 = 0x20
}

+ (Class)fetchedResultsControllerClass;	// IMP=0x000000010012cc8c
@property(retain, nonatomic) NSMutableDictionary *handlers; // @synthesize handlers=_handlers;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;	// IMP=0x000000010012d9d8
- (void)removeAllResultsChangedHandlers;	// IMP=0x000000010012d918
- (void)stop;	// IMP=0x000000010012d6ac
- (void)removeResultsChangedHandler:(id)arg1;	// IMP=0x000000010012d624
- (id)addResultsChangedHandler:(id)arg1;	// IMP=0x000000010012d544
- (id)uuids;	// IMP=0x000000010012d350
- (void)results:(CDUnknownBlockType)arg1;	// IMP=0x000000010012d1ac
- (void)startObserving;	// IMP=0x000000010012cf30
- (id)sortDescriptors;	// IMP=0x000000010012ced0
- (id)predicate;	// IMP=0x000000010012ce70
- (void)setPredicate:(id)arg1;	// IMP=0x000000010012ccc8
- (id)managedObjectContext;	// IMP=0x000000010012ccb0
- (id)_frc;	// IMP=0x000000010012cca0
- (id)initWithFetchRequest:(id)arg1 managedObjectContext:(id)arg2;	// IMP=0x000000010012cb50
- (id)initWithFetchRequest:(id)arg1;	// IMP=0x000000010012caa8
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 batchSize:(unsigned long long)arg4 propertiesToFetch:(id)arg5;	// IMP=0x000000010012c944
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3 returnObjectsAsFaults:(_Bool)arg4;	// IMP=0x000000010012c83c
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3;	// IMP=0x000000010012c7c0
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 managedObjectContext:(id)arg3;	// IMP=0x000000010012c6cc
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 background:(_Bool)arg3;	// IMP=0x000000010012c5dc
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2;	// IMP=0x000000010012c574

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

