//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTButtonBarItem : NSObject
{
    _Bool _flexible;	// 8 = 0x8
    double _width;	// 16 = 0x10
}

+ (id)fixedSpaceOfWidth:(double)arg1;	// IMP=0x000000010015ad14
+ (id)flexibleSpace;	// IMP=0x000000010015accc
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) _Bool flexible; // @synthesize flexible=_flexible;
- (id)description;	// IMP=0x000000010015ad68

@end

