//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTCoalescableWorkManifest, NSObject<OS_dispatch_queue>, NSString;

@interface MTCoalescableWorkController : NSObject
{
    _Bool _verboseDebugLoggingEnabled;	// 8 = 0x8
    unsigned int _qosClass;	// 12 = 0xc
    NSString *_identifier;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_workQueue;	// 24 = 0x18
    MTCoalescableWorkManifest *_activeWorkManifest;	// 32 = 0x20
    MTCoalescableWorkManifest *_pendingWorkManifest;	// 40 = 0x28
}

+ (id)_uniqueGenericIdentifier;	// IMP=0x00000001000799ec
+ (id)controllerWithQosClass:(unsigned int)arg1 identifier:(id)arg2;	// IMP=0x0000000100079560
@property(retain, nonatomic) MTCoalescableWorkManifest *pendingWorkManifest; // @synthesize pendingWorkManifest=_pendingWorkManifest;
@property(retain, nonatomic) MTCoalescableWorkManifest *activeWorkManifest; // @synthesize activeWorkManifest=_activeWorkManifest;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) unsigned int qosClass; // @synthesize qosClass=_qosClass;
@property(nonatomic) _Bool verboseDebugLoggingEnabled; // @synthesize verboseDebugLoggingEnabled=_verboseDebugLoggingEnabled;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;	// IMP=0x000000010007a4f0
- (void)_onWorkQueuePerformActiveWorkBlock;	// IMP=0x0000000100079f64
- (void)_syncScheduleStartActiveWork:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100079d84
- (void)_syncScheduleUpdatePendingWork:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100079aa8
- (void)schedule:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010007990c
- (void)schedule:(CDUnknownBlockType)arg1;	// IMP=0x00000001000798f4
- (id)description;	// IMP=0x00000001000797bc
- (id)initWithWorkQueue:(id)arg1 identifier:(id)arg2;	// IMP=0x0000000100079664

@end

