//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTFetchedCollectionWithSectionsViewController.h"

#import "MTCollectionViewCellDelegate.h"
#import "MTModalDismissing.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class MTCollectionView, MTCollectionViewFlowLayout, MTContentUnavailableView, MTToolbar, NSIndexPath, NSMutableDictionary, NSString, UIBarButtonItem, UIButton, UICollectionViewCell, UINavigationItem, UIRefreshControl;

@interface MTCollectionListViewController : MTFetchedCollectionWithSectionsViewController <UICollectionViewDelegateFlowLayout, MTCollectionViewCellDelegate, MTModalDismissing>
{
    NSMutableDictionary *_resultsChangedBlocks;	// 8 = 0x8
    MTContentUnavailableView *_emptyOverlay;	// 16 = 0x10
    UIButton *_editButton;	// 24 = 0x18
    UIButton *_downloadButton;	// 32 = 0x20
    UINavigationItem *_navItem;	// 40 = 0x28
    _Bool _hidesFooterWhenEmpty;	// 48 = 0x30
    _Bool _showMarkButtonInsteadOfRemoveButton;	// 49 = 0x31
    _Bool _inSwipeToDeleteMode;	// 50 = 0x32
    UIBarButtonItem *_doneButtonItem;	// 56 = 0x38
    UIBarButtonItem *_markButtonItem;	// 64 = 0x40
    UIBarButtonItem *_saveButtonItem;	// 72 = 0x48
    UIBarButtonItem *_deleteButtonItem;	// 80 = 0x50
    NSIndexPath *_expandedIndexPath;	// 88 = 0x58
    long long _state;	// 96 = 0x60
    NSString *_emptyListMessage;	// 104 = 0x68
    id <MTViewControllerEditingNotificationDelegate> _editingNotificationDelegate;	// 112 = 0x70
    MTToolbar *_toolbarHeader;	// 120 = 0x78
    double _expandedSectionBottomInset;	// 128 = 0x80
    long long _expandedSection;	// 136 = 0x88
    MTCollectionViewFlowLayout *_transitioningToFlowLayout;	// 144 = 0x90
    UIButton *_doneButton;	// 152 = 0x98
    UIButton *_markButton;	// 160 = 0xa0
    UIButton *_saveButton;	// 168 = 0xa8
    UIButton *_deleteButton;	// 176 = 0xb0
    UICollectionViewCell *_sizingCell;	// 184 = 0xb8
}

+ (Class)sizingCellClass;	// IMP=0x00000001001a9bf8
+ (Class)flowLayoutClass;	// IMP=0x00000001001a9be4
@property(retain, nonatomic) UICollectionViewCell *sizingCell; // @synthesize sizingCell=_sizingCell;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIButton *markButton; // @synthesize markButton=_markButton;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) MTCollectionViewFlowLayout *transitioningToFlowLayout; // @synthesize transitioningToFlowLayout=_transitioningToFlowLayout;
@property(nonatomic) long long expandedSection; // @synthesize expandedSection=_expandedSection;
@property(nonatomic) double expandedSectionBottomInset; // @synthesize expandedSectionBottomInset=_expandedSectionBottomInset;
@property(retain, nonatomic) MTToolbar *toolbarHeader; // @synthesize toolbarHeader=_toolbarHeader;
@property __weak id <MTViewControllerEditingNotificationDelegate> editingNotificationDelegate; // @synthesize editingNotificationDelegate=_editingNotificationDelegate;
@property(nonatomic) _Bool inSwipeToDeleteMode; // @synthesize inSwipeToDeleteMode=_inSwipeToDeleteMode;
@property(nonatomic) _Bool showMarkButtonInsteadOfRemoveButton; // @synthesize showMarkButtonInsteadOfRemoveButton=_showMarkButtonInsteadOfRemoveButton;
@property(nonatomic) _Bool hidesFooterWhenEmpty; // @synthesize hidesFooterWhenEmpty=_hidesFooterWhenEmpty;
@property(copy, nonatomic) NSString *emptyListMessage; // @synthesize emptyListMessage=_emptyListMessage;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSIndexPath *expandedIndexPath; // @synthesize expandedIndexPath=_expandedIndexPath;
- (void).cxx_destruct;	// IMP=0x00000001001b0010
- (void)dismissAllModalsAnimated:(_Bool)arg1;	// IMP=0x00000001001afdac
- (void)cellDidPressMore:(id)arg1;	// IMP=0x00000001001afda8
- (void)cellDidPressDelete:(id)arg1;	// IMP=0x00000001001afca0
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x00000001001afb64
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001001afaec
- (void)collectionView:(id)arg1 didEndEditingItemAtIndexPath:(id)arg2;	// IMP=0x00000001001afaac
- (void)collectionView:(id)arg1 willBeginEditingItemAtIndexPath:(id)arg2;	// IMP=0x00000001001afa6c
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;	// IMP=0x00000001001af9d8
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001001af944
- (void)removeSelectedItems:(id)arg1;	// IMP=0x00000001001af6f8
- (void)markSelectedItemsAsSaved:(_Bool)arg1;	// IMP=0x00000001001af6f4
- (void)markSelectedItems:(_Bool)arg1;	// IMP=0x00000001001af6f0
- (_Bool)isSelectedMediaTypeVideo;	// IMP=0x00000001001af4e0
- (id)markAsPlayedTitleForCount:(long long)arg1;	// IMP=0x00000001001af3e4
- (id)markAsUnplayedTitleForCount:(long long)arg1;	// IMP=0x00000001001af2e8
- (void)saveButtonTapped:(id)arg1;	// IMP=0x00000001001af2d8
- (_Bool)hasBulkMarkAsUnplayedAction;	// IMP=0x00000001001af2d0
- (void)markButtonTapped:(id)arg1;	// IMP=0x00000001001aef6c
- (void)downloadAll:(id)arg1;	// IMP=0x00000001001aef68
- (void)finishEditing:(id)arg1;	// IMP=0x00000001001aef28
- (void)editButtonTapped:(id)arg1;	// IMP=0x00000001001aef14
- (id)downloadButton;	// IMP=0x00000001001aed88
@property(readonly, nonatomic) UIBarButtonItem *saveButtonItem; // @synthesize saveButtonItem=_saveButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *markButtonItem; // @synthesize markButtonItem=_markButtonItem;
@property(readonly, nonatomic) UIBarButtonItem *deleteButtonItem; // @synthesize deleteButtonItem=_deleteButtonItem;
- (id)editButton;	// IMP=0x00000001001ae3e8
@property(readonly, nonatomic) UIBarButtonItem *doneButtonItem; // @synthesize doneButtonItem=_doneButtonItem;
- (id)editingToolbarItems;	// IMP=0x00000001001ae370
- (id)toolbarButtonItems;	// IMP=0x00000001001ae368
- (id)rightEditingItems;	// IMP=0x00000001001ae2cc
- (id)leftEditingItems;	// IMP=0x00000001001ae2c4
- (id)leftButtonItems;	// IMP=0x00000001001ae2bc
- (id)rightButtonItems;	// IMP=0x00000001001ae220
- (_Bool)isEditingToolbarHidden;	// IMP=0x00000001001ae1d4
- (void)setEditingToolbarHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001ae02c
- (void)calculateSectionInsetDueToExpansion;	// IMP=0x00000001001adb4c
- (void)deselectedItemAtIndexPath:(id)arg1;	// IMP=0x00000001001adb10
- (void)selectedItemAtIndexPath:(id)arg1;	// IMP=0x00000001001adb0c
- (id)collectionViewLayout;	// IMP=0x00000001001adab8
- (void)transitionToState:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001ad694
- (void)updateListStateAnimated:(_Bool)arg1;	// IMP=0x00000001001ad574
- (id)emptyOverlay;	// IMP=0x00000001001ad35c
- (_Bool)hasItems;	// IMP=0x00000001001ad1b0
- (void)refreshBarButtons;	// IMP=0x00000001001ad048
- (id)navigationItem;	// IMP=0x00000001001acfb0
- (void)updateNavigationItemsForEditing:(_Bool)arg1;	// IMP=0x00000001001acc90
- (void)transitionControlsForEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001acc1c
- (_Bool)isEntireSelectionSaved;	// IMP=0x00000001001aca04
- (void)updateMarkButtons;	// IMP=0x00000001001ac348
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001001ac220
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x00000001001ac1cc
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001001ac070
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x00000001001abe2c
- (struct CGPoint)_collectionView:(id)arg1 targetContentOffsetForProposedContentOffset:(struct CGPoint)arg2;	// IMP=0x00000001001aba1c
- (struct CGSize)currentEstimatedCellSize;	// IMP=0x00000001001ab9c0
- (_Bool)shouldCalculateDynamicHeightForIndexPath:(id)arg1;	// IMP=0x00000001001ab9b8
- (double)calculateCellWidthForSize:(struct CGSize)arg1;	// IMP=0x00000001001ab7f0
- (double)calculateCellWidthForCurrentBounds;	// IMP=0x00000001001ab780
- (double)estimatedCellHeightForWidth:(double)arg1;	// IMP=0x00000001001ab76c
- (void)updateCellSizesWithSize:(struct CGSize)arg1;	// IMP=0x00000001001ab4fc
- (void)updateCellSizes;	// IMP=0x00000001001ab4a8
- (struct CGPoint)initialLayoutContentOffset;	// IMP=0x00000001001ab450
- (void)expandCollectionViewCell:(id)arg1;	// IMP=0x00000001001ab44c
- (void)collapseCollectionViewCell:(id)arg1;	// IMP=0x00000001001ab448
- (void)_didUpdateCollectionView:(id)arg1;	// IMP=0x00000001001ab258
- (void)setExpandedIndexPath:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001001aaad0
@property(nonatomic) unsigned long long numberOfColumns;
@property(retain, nonatomic) UIRefreshControl *refreshControl;
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x00000001001aa8a4
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x00000001001aa72c
- (void)viewDidLayoutSubviews;	// IMP=0x00000001001aa35c
- (void)viewDidLoad;	// IMP=0x00000001001aa220
- (id)_newCollectionViewWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;	// IMP=0x00000001001aa174
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001001aa104
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001a9ff8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001001a9ef4
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x00000001001a9e04
- (void)dealloc;	// IMP=0x00000001001a9d8c
- (void)setState:(long long)arg1;	// IMP=0x00000001001a9d7c
- (id)initWithCollectionViewLayout:(id)arg1 compositeFetchedResultsController:(id)arg2;	// IMP=0x00000001001a9cac
- (id)initWithCompositeFetchedResultsController:(id)arg1;	// IMP=0x00000001001a9c1c
- (id)init;	// IMP=0x00000001001a9c0c

// Remaining properties
@property(retain, nonatomic) MTCollectionView *collectionView; // @dynamic collectionView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

