//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTManifestResultsController.h"

@interface MTCurrentManifestResultsController : MTManifestResultsController
{
}

- (unsigned long long)startingIndexForDisplay;	// IMP=0x00000001001430dc
- (void)manifestDidChange;	// IMP=0x0000000100143060
- (id)title;	// IMP=0x0000000100142e9c
- (void)dealloc;	// IMP=0x0000000100142e24
- (id)init;	// IMP=0x0000000100142d1c

@end

