//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableViewCell.h"

#import "UITextFieldDelegate.h"

@class NSString, UITextField;

@interface MTEditableTextFieldCell : MTTableViewCell <UITextFieldDelegate>
{
    UITextField *_textField;	// 24 = 0x18
    CDUnknownBlockType _textChanged;	// 32 = 0x20
    id <UITextFieldDelegate> _delegate;	// 40 = 0x28
}

+ (id)textFont;	// IMP=0x0000000100100fc0
@property(nonatomic) __weak id <UITextFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType textChanged; // @synthesize textChanged=_textChanged;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;	// IMP=0x00000001001018b4
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x0000000100101798
- (_Bool)textFieldShouldClear:(id)arg1;	// IMP=0x00000001001016f0
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x000000010010160c
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x0000000100101518
- (_Bool)textFieldShouldEndEditing:(id)arg1;	// IMP=0x0000000100101470
- (void)textFieldDidBeginEditing:(id)arg1;	// IMP=0x00000001001013dc
- (_Bool)textFieldShouldBeginEditing:(id)arg1;	// IMP=0x0000000100101334
- (_Bool)canBecomeFirstResponder;	// IMP=0x000000010010132c
- (void)layoutSubviews;	// IMP=0x0000000100101228
- (void)setupCell;	// IMP=0x0000000100101058
- (void)updateFonts;	// IMP=0x0000000100100fe0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

