//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MTContentUnavailableView, NSString;

@interface MTEmptyContentViewController : UIViewController
{
    NSString *_emptyTitle;	// 8 = 0x8
    NSString *_emptyMessage;	// 16 = 0x10
    MTContentUnavailableView *_emptyView;	// 24 = 0x18
}

@property(retain, nonatomic) MTContentUnavailableView *emptyView; // @synthesize emptyView=_emptyView;
@property(copy, nonatomic) NSString *emptyMessage; // @synthesize emptyMessage=_emptyMessage;
@property(copy, nonatomic) NSString *emptyTitle; // @synthesize emptyTitle=_emptyTitle;
- (void).cxx_destruct;	// IMP=0x000000010003a9bc
- (void)didReceiveMemoryWarning;	// IMP=0x000000010003a534
- (void)viewDidLoad;	// IMP=0x000000010003a3a0

@end

