//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MTColorTheme, NSArray, NSMutableDictionary;

@interface MTEpisodeStateView : UIView
{
    NSMutableDictionary *_imageViewCache;	// 8 = 0x8
    NSArray *_imageViews;	// 16 = 0x10
    unsigned long long _icons;	// 24 = 0x18
    _Bool _needsIconUpdate;	// 32 = 0x20
    _Bool _needsSizeUpdate;	// 33 = 0x21
    _Bool _verticalLayout;	// 34 = 0x22
    _Bool _centeredLayout;	// 35 = 0x23
    MTColorTheme *_colorTheme;	// 40 = 0x28
    unsigned long long _playStatus;	// 48 = 0x30
    unsigned long long _assetStatus;	// 56 = 0x38
}

+ (double)imagePadding;	// IMP=0x00000001000ba194
+ (id)imageForIconKey:(id)arg1 theme:(id)arg2;	// IMP=0x00000001000b9b90
+ (id)orderedIconKeys;	// IMP=0x00000001000b98c4
+ (id)videoIcon;	// IMP=0x00000001000b9854
+ (id)explicitIcon;	// IMP=0x00000001000b97e4
@property(nonatomic, getter=isCenteredLayout) _Bool centeredLayout; // @synthesize centeredLayout=_centeredLayout;
@property(nonatomic, getter=isVerticalLayout) _Bool verticalLayout; // @synthesize verticalLayout=_verticalLayout;
@property(nonatomic) unsigned long long assetStatus; // @synthesize assetStatus=_assetStatus;
@property(nonatomic) unsigned long long playStatus; // @synthesize playStatus=_playStatus;
@property(retain, nonatomic) MTColorTheme *colorTheme; // @synthesize colorTheme=_colorTheme;
- (void).cxx_destruct;	// IMP=0x00000001000bb5e0
- (void)sizeToFit;	// IMP=0x00000001000bb544
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000bb324
- (void)layoutSubviews;	// IMP=0x00000001000bb034
- (void)applyThemeToImageViewWithKey:(id)arg1;	// IMP=0x00000001000bad7c
- (_Bool)_isRTL;	// IMP=0x00000001000bad34
- (id)_imageViewForKey:(id)arg1;	// IMP=0x00000001000bac08
- (id)_imageViews;	// IMP=0x00000001000baa20
- (void)_updateImageViews;	// IMP=0x00000001000ba73c
- (void)_updateIconsIfNeeded;	// IMP=0x00000001000ba71c
- (void)_setNeedsIconUpdate;	// IMP=0x00000001000ba6fc
- (void)_setEnabled:(_Bool)arg1 forFlag:(unsigned long long)arg2;	// IMP=0x00000001000ba6b8
- (_Bool)_airplaneMode;	// IMP=0x00000001000ba6a4
- (_Bool)_error;	// IMP=0x00000001000ba690
- (_Bool)_document;	// IMP=0x00000001000ba67c
- (_Bool)_streaming;	// IMP=0x00000001000ba668
- (void)_setAirplaneMode:(_Bool)arg1;	// IMP=0x00000001000ba658
- (void)_setError:(_Bool)arg1;	// IMP=0x00000001000ba648
- (void)_setDocument:(_Bool)arg1;	// IMP=0x00000001000ba638
- (void)_setStreaming:(_Bool)arg1;	// IMP=0x00000001000ba628
- (id)imagesForCurrentIconsExcludingPlayState;	// IMP=0x00000001000ba420
@property(nonatomic, getter=isVideo) _Bool video;
@property(nonatomic, getter=isSaved) _Bool saved;
@property(nonatomic, setter=setExplicit:) _Bool isExplicit;
- (_Bool)isNotEmpty;	// IMP=0x00000001000ba26c
- (void)updateSizeIfNeeded;	// IMP=0x00000001000ba24c
- (id)init;	// IMP=0x00000001000ba19c

@end

