//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPlayerManifest.h"

@class NSArray;

@interface MTItemListManifest : MTPlayerManifest
{
    NSArray *_items;	// 8 = 0x8
}

@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;	// IMP=0x000000010008d648
- (unsigned long long)count;	// IMP=0x000000010008d5ec
- (id)objectAtIndex:(unsigned long long)arg1;	// IMP=0x000000010008d570
- (id)initWithItems:(id)arg1;	// IMP=0x000000010008d35c

@end

