//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObjectContext.h"

@interface MTManagedObjectContext : NSManagedObjectContext
{
    long long _type;	// 8 = 0x8
}

@property(nonatomic) long long type; // @synthesize type=_type;
- (void)seedCacheWithObjectsInArray:(id)arg1 forUUIDKey:(id)arg2;	// IMP=0x0000000100183cd8
- (void)seedCacheWithObjectsInEntity:(id)arg1 predicateFormat:(id)arg2;	// IMP=0x0000000100183c44
- (void)seedCacheWithObjectsInEntity:(id)arg1 predicate:(id)arg2;	// IMP=0x00000001001839d8
- (void)performBlockAndWait:(CDUnknownBlockType)arg1;	// IMP=0x000000010018386c
- (void)validateConcurencyType;	// IMP=0x00000001001837d8
- (_Bool)_isInternalCoreDataQueue;	// IMP=0x00000001001836d8
- (_Bool)handleError:(id *)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x0000000100183608
- (id)existingObjectWithID:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100183400
- (id)objectWithID:(id)arg1;	// IMP=0x000000010018337c
- (id)objectRegisteredForID:(id)arg1;	// IMP=0x00000001001832f8
- (unsigned long long)countForFetchRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100183130
- (void)reset;	// IMP=0x00000001001830b4
- (id)executeFetchRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100182e94
- (void)insertObject:(id)arg1;	// IMP=0x0000000100182e20
- (void)deleteObject:(id)arg1;	// IMP=0x0000000100182d18

@end

