//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTListResultsController.h"

@class MTPlayerManifest;

@interface MTManifestResultsController : MTListResultsController
{
    MTPlayerManifest *_manifest;	// 8 = 0x8
}

@property(retain, nonatomic) MTPlayerManifest *manifest; // @synthesize manifest=_manifest;
- (void).cxx_destruct;	// IMP=0x00000001001bd680
- (void)_manifestDidChange;	// IMP=0x00000001001bd5f8
- (void)reloadData;	// IMP=0x00000001001bd45c
- (unsigned long long)startingIndexForDisplay;	// IMP=0x00000001001bd408
- (void)dealloc;	// IMP=0x00000001001bd2e4
- (id)init;	// IMP=0x00000001001bd1e8

@end

