//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMDebugDataProvider.h"

@class NSString;

@interface MTMediaLibraryDebugProvider : NSObject <IMDebugDataProvider>
{
}

- (id)debugDataFileName;	// IMP=0x000000010018f1d0
- (id)debugData;	// IMP=0x000000010018ee88

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

