//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IMActionSheetAction.h"

@interface MTMoreActionSheetAction : IMActionSheetAction
{
}

+ (id)moreIcon;	// IMP=0x00000001000b6810
+ (id)action;	// IMP=0x00000001000b62e8
- (id)init;	// IMP=0x00000001000b631c

@end

