//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTBasePlaylistEpisodeListViewController.h"

#import "UIViewControllerRestoration.h"

@interface MTPlaylistGroupByPodcastDetailViewController : MTBasePlaylistEpisodeListViewController <UIViewControllerRestoration>
{
}

+ (id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2;	// IMP=0x00000001001a2904
- (id)metricsName;	// IMP=0x00000001001a2994
- (void)decodeRestorableStateWithCoder:(id)arg1;	// IMP=0x00000001001a2960
- (void)encodeRestorableStateWithCoder:(id)arg1;	// IMP=0x00000001001a292c
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;	// IMP=0x00000001001a28fc
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001001a28f4
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x00000001001a2884
- (void)updateMarkButtonsAndTitle;	// IMP=0x00000001001a274c
- (id)emptyListMessage;	// IMP=0x00000001001a26dc
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001001a268c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001a23a8

@end

