//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayerItemAccessLogEvent, MTEpisodeMetricDataSource;

@interface MTPlayMetricsEvent : NSObject
{
    _Bool _recorded;	// 8 = 0x8
    AVPlayerItemAccessLogEvent *_accessLogEvent;	// 16 = 0x10
    MTEpisodeMetricDataSource *_dataSource;	// 24 = 0x18
}

+ (id)eventWithAccessLog:(id)arg1 dataSource:(id)arg2;	// IMP=0x00000001000a73bc
@property(nonatomic, getter=isRecorded) _Bool recorded; // @synthesize recorded=_recorded;
@property(retain, nonatomic) MTEpisodeMetricDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) AVPlayerItemAccessLogEvent *accessLogEvent; // @synthesize accessLogEvent=_accessLogEvent;
- (void).cxx_destruct;	// IMP=0x00000001000a806c
- (id)description;	// IMP=0x00000001000a7ef8
- (unsigned long long)hash;	// IMP=0x00000001000a7e6c
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000a7d18
- (id)_data;	// IMP=0x00000001000a75fc
- (void)record;	// IMP=0x00000001000a7528
- (id)initWithAccessLogEvent:(id)arg1 dataSource:(id)arg2;	// IMP=0x00000001000a7448

@end

