//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSFetchedResultsController, NSIndexPath;

@interface MTSpecialIndexPathTableViewController : UITableViewController
{
    NSFetchedResultsController *_frc;	// 8 = 0x8
    NSIndexPath *_specialPath;	// 16 = 0x10
    CDUnknownBlockType _cellFor_specialPathBlock;	// 24 = 0x18
    CDUnknownBlockType _didSelect_specialPathBlock;	// 32 = 0x20
    double _heightForSpecialPath;	// 40 = 0x28
}

@property(nonatomic) double heightForSpecialPath; // @synthesize heightForSpecialPath=_heightForSpecialPath;
@property(copy, nonatomic) CDUnknownBlockType didSelect_specialPathBlock; // @synthesize didSelect_specialPathBlock=_didSelect_specialPathBlock;
@property(copy, nonatomic) CDUnknownBlockType cellFor_specialPathBlock; // @synthesize cellFor_specialPathBlock=_cellFor_specialPathBlock;
@property(retain, nonatomic) NSIndexPath *specialPath; // @synthesize specialPath=_specialPath;
@property(retain, nonatomic) NSFetchedResultsController *frc; // @synthesize frc=_frc;
- (void).cxx_destruct;	// IMP=0x0000000100031c3c
- (void)main_configureCell:(id)arg1 forRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031b98
- (_Bool)main_tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031b90
- (void)main_tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031b8c
- (double)main_tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031b84
- (id)main_tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031b7c
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100031aa8
- (_Bool)tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x00000001000319c0
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000318c0
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100031850
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100031750
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010003163c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000315a0
- (id)offsetIndexPath:(id)arg1;	// IMP=0x0000000100031520
- (id)translateIndexPath:(id)arg1;	// IMP=0x00000001000314a0

@end

