//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MZKeyValueStoreTransactionProcessing.h"

@class NSMutableArray, NSMutableSet, NSString;

@interface MTSubscriptionSyncProcessor : NSObject <MZKeyValueStoreTransactionProcessing>
{
    NSMutableArray *_podcastKeysToRequest;	// 8 = 0x8
    NSMutableSet *_addedSubscriptions;	// 16 = 0x10
}

+ (void)initialize;	// IMP=0x00000001001b092c
@property(retain, nonatomic) NSMutableSet *addedSubscriptions; // @synthesize addedSubscriptions=_addedSubscriptions;
@property(retain, nonatomic) NSMutableArray *podcastKeysToRequest; // @synthesize podcastKeysToRequest=_podcastKeysToRequest;
- (void).cxx_destruct;	// IMP=0x00000001001b3c28
- (id)predicateForSyncablePodcasts;	// IMP=0x00000001001b3b4c
- (void)updateSettingsForPodcast:(id)arg1 podcastDict:(id)arg2 ctx:(id)arg3;	// IMP=0x00000001001b375c
- (void)subscribeFromCloudToPodcasts:(id)arg1;	// IMP=0x00000001001b3038
- (void)transaction:(id)arg1 didProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x00000001001b3020
- (void)transaction:(id)arg1 willProcessResponseWithDomainVersion:(id)arg2;	// IMP=0x00000001001b301c
- (id)_podcastSubscriptions;	// IMP=0x00000001001b29fc
- (id)syncDictionaryToMetricsDictionary:(id)arg1;	// IMP=0x00000001001b29e0
- (void)transaction:(id)arg1 mergeData:(id)arg2 forKey:(id)arg3 domainVersion:(id)arg4 version:(id)arg5 mismatch:(_Bool)arg6 finishedBlock:(CDUnknownBlockType)arg7;	// IMP=0x00000001001b0ff8
- (id)dataForSetTransaction:(id)arg1 key:(id)arg2 version:(id *)arg3;	// IMP=0x00000001001b0bfc
- (id)versionForGetTransaction:(id)arg1 key:(id)arg2;	// IMP=0x00000001001b0ac4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

