//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSpecialIndexPathTableViewController.h"

@class NSMutableSet, NSString;

@interface MTTVStationSelectPodcastsListViewController : MTSpecialIndexPathTableViewController
{
    _Bool _allPodcastsSelected;	// 8 = 0x8
    NSString *_playlistName;	// 16 = 0x10
    NSMutableSet *_podcastUuids;	// 24 = 0x18
    NSString *_playlistUuid;	// 32 = 0x20
    id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> _saveDelegate;	// 40 = 0x28
}

@property(nonatomic) __weak id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> saveDelegate; // @synthesize saveDelegate=_saveDelegate;
@property(retain, nonatomic) NSString *playlistUuid; // @synthesize playlistUuid=_playlistUuid;
@property(nonatomic) _Bool allPodcastsSelected; // @synthesize allPodcastsSelected=_allPodcastsSelected;
@property(retain, nonatomic) NSMutableSet *podcastUuids; // @synthesize podcastUuids=_podcastUuids;
@property(retain, nonatomic) NSString *playlistName; // @synthesize playlistName=_playlistName;
- (void).cxx_destruct;	// IMP=0x00000001000663ac
- (void)main_tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001000661a0
- (_Bool)main_tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x0000000100066180
- (double)main_tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100066174
- (void)main_configureCell:(id)arg1 forRowAtIndexPath:(id)arg2;	// IMP=0x0000000100066000
- (id)main_tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100065fa4
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x0000000100065f9c
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x0000000100065f2c
- (void)save;	// IMP=0x0000000100065cd8
- (_Bool)toggleUuid:(id)arg1;	// IMP=0x0000000100065ba4
- (void)toggleAllPodcastsSelected;	// IMP=0x0000000100065b3c
- (void)setupIncludeAllCell;	// IMP=0x0000000100065764
- (void)setupFRC;	// IMP=0x0000000100065584
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000652d0
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100065280
- (void)viewDidLoad;	// IMP=0x0000000100065190

@end

