//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MTTVStationsPlusButtonView, UILabel;

@interface MTTVStationPlusButtonCollectionViewCell : UICollectionViewCell
{
    MTTVStationsPlusButtonView *_plusButtonView;	// 8 = 0x8
    UILabel *_newStationLabel;	// 16 = 0x10
}

+ (id)reuseIdentifier;	// IMP=0x000000010015a524
@property(retain, nonatomic) UILabel *newStationLabel; // @synthesize newStationLabel=_newStationLabel;
@property(retain, nonatomic) MTTVStationsPlusButtonView *plusButtonView; // @synthesize plusButtonView=_plusButtonView;
- (void).cxx_destruct;	// IMP=0x000000010015ac8c
- (id)_textColor;	// IMP=0x000000010015aab0
- (void)_addNewStationLabel;	// IMP=0x000000010015a95c
- (void)_addPlusButtonView;	// IMP=0x000000010015a890
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010015a7c8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010015a6c0
- (void)layoutSubviews;	// IMP=0x000000010015a5bc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010015a540

@end

