//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTOptionsTableViewController.h"

@interface MTTVOptionsTableViewController : MTOptionsTableViewController
{
}

+ (id)footerFont;	// IMP=0x00000001000b3f38
- (void)_updateTextColorForCell:(id)arg1 selected:(_Bool)arg2;	// IMP=0x00000001000b43f4
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000b4368
- (void)viewWillLayoutSubviews;	// IMP=0x00000001000b3fbc
- (void)viewDidLoad;	// IMP=0x00000001000b3f58

@end

