//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTVEpisodeSplitViewController.h"

@class MTArtworkBackgroundView, MTColorTheme, MTPodcast, MTTVPodcastEpisodeListViewController, MTTVPodcastGoneDarkDetailViewController;

@interface MTTVPodcastDetailViewController : MTTVEpisodeSplitViewController
{
    MTPodcast *_podcast;	// 8 = 0x8
    MTTVPodcastGoneDarkDetailViewController *_goneDarkDetailViewController;	// 16 = 0x10
    MTArtworkBackgroundView *_backgroundView;	// 24 = 0x18
    MTColorTheme *_colorTheme;	// 32 = 0x20
}

@property(retain, nonatomic) MTColorTheme *colorTheme; // @synthesize colorTheme=_colorTheme;
@property(retain, nonatomic) MTArtworkBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) MTTVPodcastGoneDarkDetailViewController *goneDarkDetailViewController; // @synthesize goneDarkDetailViewController=_goneDarkDetailViewController;
@property(readonly, nonatomic) MTPodcast *podcast; // @synthesize podcast=_podcast;
- (void).cxx_destruct;	// IMP=0x00000001000d3fe0
- (void)_setupBackgroundView;	// IMP=0x00000001000d3d00
- (void)_showDetailsForIndexPath:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000d3bf8
- (id)overrideTraitCollectionForChildViewController:(id)arg1;	// IMP=0x00000001000d3924
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000d3708
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000d3638
- (void)viewDidLoad;	// IMP=0x00000001000d34f8
- (void)highlightEpisodeUuid:(id)arg1;	// IMP=0x00000001000d3344
- (id)initWithPodcast:(id)arg1;	// IMP=0x00000001000d3294

// Remaining properties
@property(retain, nonatomic) MTTVPodcastEpisodeListViewController *episodeList; // @dynamic episodeList;

@end

