//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface MTTVSettingsTableViewCell : UITableViewCell
{
}

+ (id)reuseIdentifier;	// IMP=0x0000000100004e98
+ (double)height;	// IMP=0x0000000100004e8c
- (void)updateColors;	// IMP=0x00000001000055b8
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100005540
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100005478
- (void)layoutSubviews;	// IMP=0x00000001000051e4
- (void)prepareForReuse;	// IMP=0x000000010000510c
- (void)configureSubviews;	// IMP=0x0000000100004f54
- (id)init;	// IMP=0x0000000100004ec4

@end

