//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (MTAdditions)
+ (id)mt_lessVerboseDateFormatter;	// IMP=0x0000000100038d1c
+ (id)mt_verboseDateFormatter;	// IMP=0x0000000100038c04
+ (id)mt_dateFormatterNoYearAbbrevMonth;	// IMP=0x0000000100038aec
+ (id)mt_dateFormatterNoYear;	// IMP=0x00000001000389d4
+ (id)mt_dateFormatterShortStyleWithYear;	// IMP=0x00000001000388e4
+ (id)mt_dateFormatterNoDayWithYear;	// IMP=0x00000001000387cc
+ (id)mt_dateFormatterJustYear;	// IMP=0x0000000100038684
+ (id)mt_dateFormatterWithYear;	// IMP=0x000000010003856c
+ (double)maxWidthForMicroFriendlyDateStringWithFont:(id)arg1;	// IMP=0x000000010003842c
+ (id)dayOfWeekFromDate:(id)arg1 abbreviated:(_Bool)arg2;	// IMP=0x0000000100037bd8
- (id)mt_dateWithDeltaDays:(long long)arg1;	// IMP=0x0000000100038f44
- (_Bool)isLessThanWeekOld;	// IMP=0x0000000100038e34
- (_Bool)isSameDayOfWeekAs:(id)arg1;	// IMP=0x0000000100038384
- (_Bool)inSameYearAs:(id)arg1;	// IMP=0x0000000100038290
- (_Bool)isThisYear;	// IMP=0x0000000100038230
- (id)timeString;	// IMP=0x0000000100038168
- (id)verboseDisplayStringWithoutTime;	// IMP=0x0000000100038104
- (id)lessVerboseDisplayString;	// IMP=0x0000000100037fd4
- (id)verboseDisplayString;	// IMP=0x0000000100037ea4
- (id)nanoFriendlyDisplayString;	// IMP=0x00000001000379b4
- (id)microFriendlyDisplayString;	// IMP=0x0000000100037790
- (id)abbreviatedFriendlyDisplayString;	// IMP=0x000000010003756c
- (id)yearString;	// IMP=0x0000000100037508
- (id)friendlyDisplayString;	// IMP=0x00000001000372e4
@end

