//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@interface NSOperation (BKBackgrounding)
+ (id)__backgroundTaskRegistry;	// IMP=0x00000001001e5758
- (void)endBackgroundTask;	// IMP=0x00000001001e5950
- (void)startBackgroundTask;	// IMP=0x00000001001e57cc
@end

