//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@interface UIBarButtonItem (MTAdditions)
+ (id)flexiblySpacedBarButtonItems:(id)arg1 spacersOnEdges:(_Bool)arg2;	// IMP=0x00000001001c55d4
+ (id)flexiblySpacedBarButtonItems:(id)arg1;	// IMP=0x00000001001c55c4
+ (id)flexibleSpace;	// IMP=0x00000001001c5560
@end

