//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (IMAdditions)
+ (id)roundedCornerRectangleWithColorNoTemplate:(id)arg1;	// IMP=0x00000001001eea2c
+ (id)roundedCornerRectangleWithColor:(id)arg1;	// IMP=0x00000001001ee974
+ (id)colorSliceImageWithColor:(id)arg1 height:(double)arg2;	// IMP=0x00000001001ee8dc
+ (id)scaledImageWithData:(id)arg1;	// IMP=0x00000001001ee7f4
+ (id)makeDottedLineImageinRect:(struct CGRect)arg1;	// IMP=0x00000001001ee560
+ (id)uncachedImageNamed:(id)arg1;	// IMP=0x00000001001ee498
+ (id)imageWithSolidColor:(id)arg1 atSize:(struct CGSize)arg2;	// IMP=0x00000001001ed714
+ (id)image:(id)arg1 inRect:(struct CGRect)arg2 withBacking:(id)arg3 opaque:(_Bool)arg4 scale:(double)arg5;	// IMP=0x00000001001ed58c
+ (id)image:(id)arg1 inRect:(struct CGRect)arg2 withBacking:(id)arg3;	// IMP=0x00000001001ed404
- (id)im_flatImageWithColor:(id)arg1;	// IMP=0x00000001001ee720
- (void)dumpAsPNGToCachesNamed:(id)arg1;	// IMP=0x00000001001ee3f4
- (void)debugShowInKeyWindow;	// IMP=0x00000001001ee33c
- (unsigned long long)colorAtPixelX:(unsigned long long)arg1 y:(unsigned long long)arg2;	// IMP=0x00000001001ee11c
- (id)mirroredImage;	// IMP=0x00000001001ee068
- (id)stretchableMirroredImage;	// IMP=0x00000001001ee018
- (id)imageByRemovingPath:(id)arg1;	// IMP=0x00000001001ede48
- (id)imageWithComposite:(id)arg1 blendMode:(int)arg2 dstRect:(struct CGRect)arg3;	// IMP=0x00000001001edcb8
- (id)imageWithComposite:(id)arg1 blendMode:(int)arg2;	// IMP=0x00000001001edc40
- (id)im_imageWithBackgroundColor:(id)arg1;	// IMP=0x00000001001edb6c
- (id)imageWithGradientAngle:(double)arg1 startColor:(id)arg2 endColor:(id)arg3;	// IMP=0x00000001001ed8ac
- (id)imageMaskWithColor:(id)arg1;	// IMP=0x00000001001ed2b4
- (id)imageWithTint:(id)arg1;	// IMP=0x00000001001ed198
- (id)squareImage;	// IMP=0x00000001001ed020
- (id)imageWithCropRect:(struct CGRect)arg1;	// IMP=0x00000001001ecf14
- (id)imageWithWidth:(double)arg1 leftCapWidth:(long long)arg2 rightCapWidth:(long long)arg3;	// IMP=0x00000001001eccec
- (id)imageWithWidth:(double)arg1 leftCapWidth:(long long)arg2;	// IMP=0x00000001001eccdc
- (id)imageWithMaxBounds:(struct CGSize)arg1;	// IMP=0x00000001001ecccc
- (id)imageWithSize:(struct CGSize)arg1 resizeOptions:(int)arg2;	// IMP=0x00000001001ec9bc
- (id)imageWithSize:(struct CGSize)arg1 preserveAspectRatio:(_Bool)arg2;	// IMP=0x00000001001ec9b0
- (id)imageWithSize:(struct CGSize)arg1;	// IMP=0x00000001001ec9a0
@end

