//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (MTAdditions)
- (_Bool)_hasRowAtIndexPath:(id)arg1 focusable:(_Bool)arg2;	// IMP=0x0000000100142504
- (id)_indexPathForRowBeforeIndexPath:(id)arg1 focusable:(_Bool)arg2;	// IMP=0x00000001001424c8
- (id)_indexPathForRowAfterIndexPath:(id)arg1 focusable:(_Bool)arg2;	// IMP=0x000000010014248c
- (id)_indexPathForClosestRowToIndexPath:(id)arg1 focusable:(_Bool)arg2;	// IMP=0x00000001001421f4
- (unsigned long long)numberOfRowsFromIndexPath:(id)arg1 toFromIndexPath:(id)arg2;	// IMP=0x0000000100141fbc
- (id)distanceFromIndexPath:(id)arg1 toIndexPath:(id)arg2;	// IMP=0x0000000100141ee4
- (id)indexPathForClosestFocusableRowToIndexPath:(id)arg1;	// IMP=0x0000000100141ed4
- (id)indexPathForClosestRowToIndexPath:(id)arg1;	// IMP=0x0000000100141ec4
- (id)indexPathForFocusableRowAfterIndexPath:(id)arg1;	// IMP=0x0000000100141d44
- (id)indexPathForRowAfterIndexPath:(id)arg1;	// IMP=0x0000000100141be8
- (id)indexPathForFocusableRowBeforeIndexPath:(id)arg1;	// IMP=0x0000000100141aac
- (id)indexPathForRowBeforeIndexPath:(id)arg1;	// IMP=0x000000010014195c
- (id)indexPathForFirstFocusableRow;	// IMP=0x0000000100141844
- (id)indexPathForLastRowInSection:(long long)arg1;	// IMP=0x00000001001417d4
- (id)indexPathForFirstRowInSection:(long long)arg1;	// IMP=0x0000000100141764
- (id)indexPathForLastRow;	// IMP=0x00000001001416d0
- (id)indexPathForFirstRow;	// IMP=0x0000000100141638
- (_Bool)canFocusRowAtIndexPath:(id)arg1;	// IMP=0x0000000100141550
- (_Bool)hasRowsInSectionAtIndex:(long long)arg1;	// IMP=0x00000001001414f8
- (_Bool)hasRowAtIndexPath:(id)arg1;	// IMP=0x0000000100141414
@end

