//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface UIView (IMAdditions)
- (_Bool)isVerticallyRegular;	// IMP=0x00000001001f3984
- (_Bool)isVerticallyCompact;	// IMP=0x00000001001f3954
- (_Bool)isVerticallySpecified;	// IMP=0x00000001001f3924
- (_Bool)isHorizontallyRegular;	// IMP=0x00000001001f38f4
- (_Bool)isHorizontallyCompact;	// IMP=0x00000001001f38c4
- (_Bool)isHorizontallySpecified;	// IMP=0x00000001001f3894
- (struct CGRect)adjustRectCenter:(struct CGRect)arg1 fromView:(id)arg2;	// IMP=0x00000001001f37f8
- (_Bool)isViewSizeFullScreenInWindow:(id)arg1 ignoreInWindowCheck:(_Bool)arg2;	// IMP=0x00000001001f36c0
@property(retain, nonatomic) UIColor *debugingBorderColor;
- (void)attachPopUpAnimation;	// IMP=0x00000001001f3340
- (void)setRoundedCorners:(long long)arg1 radius:(double)arg2;	// IMP=0x00000001001f3108
- (void)printResponderChain;	// IMP=0x00000001001f3070
- (id)findFirstResponder;	// IMP=0x00000001001f2f24
- (id)ancestorOfClass:(Class)arg1;	// IMP=0x00000001001f2eb4
- (id)subviewOfClass:(Class)arg1;	// IMP=0x00000001001f2ccc
- (id)imageSnapshot;	// IMP=0x00000001001f2bc8
- (id)snapshot_cg;	// IMP=0x00000001001f2adc
- (void)debugHighlightViewWithColor:(id)arg1 width:(double)arg2;	// IMP=0x00000001001f29f0
- (void)debugHighlightViewBlue;	// IMP=0x00000001001f29ac
- (void)debugHighlightView;	// IMP=0x00000001001f2968
@end

