//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSPowerMonitorObserver.h"

@class NSString, SSDisplay;

@interface PREIdleSleepManager : NSObject <BSPowerMonitorObserver>
{
    _Bool _displayDim;	// 8 = 0x8
    _Bool _allowIdleTimerToBeReset;	// 9 = 0x9
    SSDisplay *_display;	// 16 = 0x10
}

+ (id)sharedController;	// IMP=0x0000000100004124
@property(retain, nonatomic) SSDisplay *display; // @synthesize display=_display;
@property(nonatomic) _Bool allowIdleTimerToBeReset; // @synthesize allowIdleTimerToBeReset=_allowIdleTimerToBeReset;
@property(nonatomic, getter=isDisplayDim) _Bool displayDim; // @synthesize displayDim=_displayDim;
- (void).cxx_destruct;	// IMP=0x0000000100005158
- (void)powerMonitorSystemDidWakeFromSleep:(id)arg1;	// IMP=0x0000000100005088
- (void)powerMonitorSystemWillWakeFromSleep:(id)arg1;	// IMP=0x000000010000501c
- (void)powerMonitorSystemWillSleep:(id)arg1;	// IMP=0x0000000100004fb0
- (void)powerMonitorSystemSleepRequestAborted:(id)arg1;	// IMP=0x0000000100004f44
- (_Bool)powerMonitorSystemSleepRequested:(id)arg1;	// IMP=0x0000000100004ed4
- (void)_startAllowingIdleTimer;	// IMP=0x0000000100004eb4
- (void)_requestedUserEventNotificationOccurred;	// IMP=0x0000000100004eb0
- (void)_userEventPresenceTimerExpired;	// IMP=0x0000000100004eac
- (void)_userEventOccurred;	// IMP=0x0000000100004e9c
- (void)_userEventsDidIdle;	// IMP=0x0000000100004e90
- (void)resetIdleTimerAndUndim:(_Bool)arg1;	// IMP=0x0000000100004d24
- (double)_nextLockTimeDuration;	// IMP=0x0000000100004cdc
- (void)setPreventIdleSleep:(_Bool)arg1 forReason:(id)arg2;	// IMP=0x0000000100004c64
- (void)_preventIdleSleepForNumberOfSeconds:(float)arg1;	// IMP=0x0000000100004b74
- (void)_preventIdleSleep;	// IMP=0x0000000100004b1c
- (void)_allowIdleSleep;	// IMP=0x0000000100004ac4
- (void)dimDisplay;	// IMP=0x0000000100004910
- (void)undimDisplay;	// IMP=0x00000001000048f0
- (void)_undimDisplayForce;	// IMP=0x00000001000046f8
- (void)_setHIDUILockedState:(_Bool)arg1;	// IMP=0x00000001000046bc
- (id)init;	// IMP=0x00000001000041a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

