//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSArray, UIView;

@interface PREStackViewController : UIViewController
{
    struct NSArray *_viewControllers;	// 8 = 0x8
    UIView *_containerView;	// 16 = 0x10
}

@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
- (void).cxx_destruct;	// IMP=0x0000000100008618
- (void)didReceiveMemoryWarning;	// IMP=0x00000001000085d4
- (void)viewDidLoad;	// IMP=0x000000010000848c
- (void)showViewController:(id)arg1 sender:(id)arg2;	// IMP=0x0000000100008430
- (void)replaceViewController:(id)arg1 withViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x000000010000835c
- (void)removeViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000082c4
- (void)popToViewController:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100008244
- (void)popToRootViewControllerAnimated:(_Bool)arg1;	// IMP=0x00000001000081d4
- (void)popViewControllerAnimated:(_Bool)arg1;	// IMP=0x000000010000814c
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008094
@property(readonly, nonatomic) UIViewController *visibleViewController;
@property(readonly, nonatomic) UIViewController *topViewController;
- (void)_setViewControllers:(struct NSArray *)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000749c
- (void)setViewControllers:(struct NSArray *)arg1 animated:(_Bool)arg2;	// IMP=0x000000010000748c
- (void)loadView;	// IMP=0x00000001000073d4
- (id)initWithRootViewController:(id)arg1;	// IMP=0x0000000100007360
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000072f4

@end

