//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TVHomeSharing)
+ (id)tvh_localizedStringWithFormat:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010000a3c4
- (id)tvh_stringByDecodingXMLEntities;	// IMP=0x000000010000a88c
- (id)tvh_stringByEncodingXMLEntities;	// IMP=0x000000010000a854
@end

