//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DADevice.h"
#import "DADeviceWithUI.h"
#import "DATestQueueDelegate.h"

@class DADeviceState, DKDiagnosticManager, DSHardwareButtonEventMonitor, NSObject<DADeviceMaterialized>, NSString;

@interface DADeviceDecoratorWithUI : NSObject <DADeviceWithUI, DADevice, DATestQueueDelegate>
{
    float _originalScreenBrightness;	// 8 = 0x8
    id <DKVolumeHUDResponder> _volumeHUDResponder;	// 16 = 0x10
    id <DKBrightnessResponder> _brightnessResponder;	// 24 = 0x18
    id <DKViewControllerDelegate> _viewControllerDelegate;	// 32 = 0x20
    id <DADeviceWithUIDelegate> _delegate;	// 40 = 0x28
    DSHardwareButtonEventMonitor *_buttonEventMonitor;	// 48 = 0x30
    NSObject<DADeviceMaterialized> *_original;	// 56 = 0x38
}

+ (id)decorateWithDevice:(id)arg1;	// IMP=0x0000000100004a4c
@property(retain, nonatomic) NSObject<DADeviceMaterialized> *original; // @synthesize original=_original;
@property(retain, nonatomic) DSHardwareButtonEventMonitor *buttonEventMonitor; // @synthesize buttonEventMonitor=_buttonEventMonitor;
@property(nonatomic) float originalScreenBrightness; // @synthesize originalScreenBrightness=_originalScreenBrightness;
@property(nonatomic) __weak id <DADeviceWithUIDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <DKViewControllerDelegate> viewControllerDelegate; // @synthesize viewControllerDelegate=_viewControllerDelegate;
@property(nonatomic) __weak id <DKBrightnessResponder> brightnessResponder; // @synthesize brightnessResponder=_brightnessResponder;
@property(nonatomic) __weak id <DKVolumeHUDResponder> volumeHUDResponder; // @synthesize volumeHUDResponder=_volumeHUDResponder;
- (void).cxx_destruct;	// IMP=0x0000000100005f28
- (void)_reset;	// IMP=0x0000000100005da8
- (void)_startInterceptingButtonEvents;	// IMP=0x0000000100005c24
- (void)handleButtonEvent:(unsigned long long)arg1;	// IMP=0x0000000100005918
- (void)executeTestWithTestAttributes:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000053b8
- (void)end;	// IMP=0x00000001000052d4
- (void)resumeTests;	// IMP=0x0000000100005294
- (void)suspendTests;	// IMP=0x0000000100005254
- (void)idle;	// IMP=0x0000000100005214
- (void)start;	// IMP=0x000000010000516c
- (void)connect;	// IMP=0x000000010000512c
- (_Bool)isKindOfClass:(Class)arg1;	// IMP=0x0000000100004f34
- (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x0000000100004e88
- (void)forwardInvocation:(id)arg1;	// IMP=0x0000000100004cf8
- (id)forwardingTargetForSelector:(SEL)arg1;	// IMP=0x0000000100004b74
- (id)initWithDevice:(id)arg1;	// IMP=0x0000000100004ab0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) DKDiagnosticManager *diagnosticsManager; // @dynamic diagnosticsManager;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isLocal) _Bool local; // @dynamic local;
@property(readonly, nonatomic) DADeviceState *state; // @dynamic state;
@property(readonly) Class superclass;

@end

