//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, UILabel;

@interface DADeviceIdentifierView : UIView
{
    NSString *_deviceIdentifier;	// 8 = 0x8
    UILabel *_identifierLabel;	// 16 = 0x10
    NSLayoutConstraint *_identifierLabelHeightConstraint;	// 24 = 0x18
    UILabel *_serialNumberLabel;	// 32 = 0x20
    NSLayoutConstraint *_serialNumberLabelHeightConstraint;	// 40 = 0x28
}

@property(retain, nonatomic) NSLayoutConstraint *serialNumberLabelHeightConstraint; // @synthesize serialNumberLabelHeightConstraint=_serialNumberLabelHeightConstraint;
@property(retain, nonatomic) UILabel *serialNumberLabel; // @synthesize serialNumberLabel=_serialNumberLabel;
@property(retain, nonatomic) NSLayoutConstraint *identifierLabelHeightConstraint; // @synthesize identifierLabelHeightConstraint=_identifierLabelHeightConstraint;
@property(retain, nonatomic) UILabel *identifierLabel; // @synthesize identifierLabel=_identifierLabel;
@property(retain, nonatomic) NSString *deviceIdentifier; // @synthesize deviceIdentifier=_deviceIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100010bf8
- (void)setHeight;	// IMP=0x0000000100010a7c
- (void)setHidden:(_Bool)arg1;	// IMP=0x0000000100010a2c
- (void)updateConstraints;	// IMP=0x000000010001017c
- (void)updateWithDeviceState:(id)arg1;	// IMP=0x000000010001010c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010000fe30

@end

