//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHJSObject.h"

#import "TVHJSCollectionComparator.h"

@class TVHKCollectionComparator;

@interface TVHJSCollectionComparator : TVHJSObject <TVHJSCollectionComparator>
{
    TVHKCollectionComparator *_wrappedComparator;	// 8 = 0x8
}

+ (void)_populateMediaEntityIdentifiers:(id)arg1 forMediaEntities:(id)arg2;	// IMP=0x000000010001cd34
@property(retain, nonatomic) TVHKCollectionComparator *wrappedComparator; // @synthesize wrappedComparator=_wrappedComparator;
- (void).cxx_destruct;	// IMP=0x000000010001ceb8
- (id)mediaEntityChanges:(id)arg1:(id)arg2;	// IMP=0x000000010001ca50
- (id)mediaServersChanges:(id)arg1:(id)arg2;	// IMP=0x000000010001c848
- (id)changes:(id)arg1:(id)arg2;	// IMP=0x000000010001c714
- (id)initWithAppContext:(id)arg1;	// IMP=0x000000010001c694
- (id)init;	// IMP=0x000000010001c634

@end

