//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (TVHomeSharing)
- (void)tvh_setPositionalDurationTextForSecondsString:(id)arg1;	// IMP=0x0000000100037888
- (void)tvh_setDurationTextForSecondsString:(id)arg1;	// IMP=0x00000001000377c0
@end

